/* ===== Übersetzungen der spanischen Beispiele in Erklärungen & Resumen (Schalter „Übersetzung“, nur bei Erklärsprache Deutsch) =====
   Schlüssel = spanischer Text wie in der Erklärung (mit „Jonas“), Wert = Deutsch. Stand: A1 komplett; A2–C2 folgen. */
window.INFO_TR=Object.assign(window.INFO_TR||{},{
"Buenos días": "Guten Morgen / Guten Tag",
"Buenas tardes": "Guten Tag / Guten Abend (nachmittags)",
"Buenas noches": "Guten Abend / Gute Nacht",
"Hola": "Hallo",
"¡Hola, buenos días!": "Hallo, guten Morgen!",
"¿Cómo te llamas?": "Wie heißt du?",
"¿Cómo se llama usted?": "Wie heißen Sie?",
"Me llamo Jonas. ¿Y tú?": "Ich heiße Jonas. Und du?",
"Soy Jonas. ¿Y usted?": "Ich bin Jonas. Und Sie?",
"usted": "Sie (höflich)",
"¿Qué tal?": "Wie geht’s?",
"Bien, ¿y tú?": "Gut, und dir?",
"¿Cómo estás? (tú)": "Wie geht es dir? (du)",
"Muy bien, gracias. ¿Y tú?": "Sehr gut, danke. Und dir?",
"¿Cómo está usted? (usted)": "Wie geht es Ihnen? (Sie)",
"Bien, gracias. ¿Y usted?": "Gut, danke. Und Ihnen?",
"¡Hola! ¿Qué tal?": "Hallo! Wie geht’s?",
"encantado": "freut mich (Mann)",
"encantada": "freut mich (Frau)",
"queso": "Käse",
"Soy … / Me llamo … ¿Y tú?": "Ich bin … / Ich heiße … Und du?",
"Soy … / Me llamo … ¿Y usted?": "Ich bin … / Ich heiße … Und Sie?",
"¿Qué tal? / ¿Cómo estás?": "Wie geht’s? / Wie geht es dir?",
"Bien / Muy bien / Regular, ¿y tú?": "Gut / Sehr gut / Es geht, und dir?",
"¿Cómo está usted?": "Wie geht es Ihnen?",
"Muy bien, gracias. ¿Y usted?": "Sehr gut, danke. Und Ihnen?",
"Adiós · Hasta luego · Hasta pronto · Hasta mañana · Hasta la próxima": "Tschüss · Bis später · Bis bald · Bis morgen · Bis zum nächsten Mal",
"el producto, el equipo": "das Produkt, das Team",
"la empresa, la ciudad, la exposición": "die Firma, die Stadt, die Ausstellung",
"el hotel, la imagen, el arte": "das Hotel, das Bild, die Kunst",
"el día": "der Tag",
"el programa": "das Programm",
"la foto": "das Foto",
"la mano": "die Hand",
"el producto": "das Produkt",
"la página": "die Seite",
"los productos": "die Produkte",
"las páginas": "die Seiten",
"un producto": "ein Produkt",
"una página": "eine Seite",
"unos productos": "einige Produkte",
"unas páginas": "einige Seiten",
"equipo → equipos": "Team → Teams",
"hotel → hoteles": "Hotel → Hotels",
"ciudad → ciudades": "Stadt → Städte",
"exposición → exposiciones": "Ausstellung → Ausstellungen",
"jamón → jamones": "Schinken → Schinken (Pl.)",
"unos / unas": "einige (m / f)",
"¿Qué significa «red social»?": "Was bedeutet „red social“?",
"Creo que significa …": "Ich glaube, es bedeutet …",
"¿«Red» significa «Netz»?": "Bedeutet „red“ „Netz“?",
"Sí. / No. / No sé.": "Ja. / Nein. / Ich weiß nicht.",
"¿Cómo se dice «Messe» en español?": "Wie sagt man „Messe“ auf Spanisch?",
"Se dice «feria».": "Man sagt „feria“.",
"¿Puedes repetir, por favor?": "Kannst du das wiederholen, bitte?",
"Más despacio, por favor.": "Langsamer, bitte.",
"soy": "ich bin",
"eres": "du bist",
"es": "er/sie ist, Sie sind",
"somos": "wir sind",
"sois": "ihr seid",
"son": "sie sind, Sie sind (Pl.)",
"Soy de Alemania.": "Ich komme aus Deutschland.",
"Yo soy de Mannheim y ella es de Girona.": "Ich komme aus Mannheim und sie kommt aus Girona.",
"ustedes": "Sie (Plural, höflich)",
"vosotros": "ihr",
"¿De dónde eres?": "Woher kommst du?",
"¿De dónde es usted?": "Woher kommen Sie?",
"Soy de Holanda.": "Ich komme aus Holland.",
"¿Eres de España?": "Kommst du aus Spanien?",
"No, soy de Chile.": "Nein, ich komme aus Chile.",
"¿Sois de Colombia?": "Kommt ihr aus Kolumbien?",
"Sí, de Bogotá.": "Ja, aus Bogotá.",
"¿Son ustedes de Madrid?": "Kommen Sie aus Madrid?",
"No, somos de Vigo.": "Nein, wir kommen aus Vigo.",
"no": "nein / nicht",
"Messi no es de Barcelona.": "Messi kommt nicht aus Barcelona.",
"No, no soy de Madrid.": "Nein, ich komme nicht aus Madrid.",
"hablo": "ich spreche",
"hablas": "du sprichst",
"habla": "er/sie spricht, Sie sprechen",
"hablamos": "wir sprechen",
"habláis": "ihr sprecht",
"hablan": "sie sprechen, Sie sprechen (Pl.)",
"estudiar, trabajar, buscar, necesitar, usar, practicar, viajar, escuchar, tocar": "lernen/studieren, arbeiten, suchen, brauchen, benutzen, üben, reisen, hören, spielen (Instrument)",
"¿Qué?": "Was?",
"¿Qué idiomas hablas?": "Welche Sprachen sprichst du?",
"¿Quién? / ¿Quiénes?": "Wer? (Sg. / Pl.)",
"¿Quiénes estudian chino?": "Wer lernt Chinesisch?",
"¿Dónde?": "Wo?",
"¿Dónde trabajas?": "Wo arbeitest du?",
"¿De dónde?": "Woher?",
"¿De dónde es Marco?": "Woher kommt Marco?",
"¿Para qué?": "Wofür? / Wozu?",
"¿Para qué estudias español?": "Wozu lernst du Spanisch?",
"¿Cómo?": "Wie?",
"Hablo español.": "Ich spreche Spanisch.",
"Yo también. (ich auch)": "Ich auch.",
"Yo no. (ich nicht)": "Ich nicht.",
"No hablo francés.": "Ich spreche kein Französisch.",
"Yo tampoco. (ich auch nicht)": "Ich auch nicht.",
"Yo sí. (ich schon)": "Ich schon.",
"Lucas y Sarah no practican deporte, pero yo sí.": "Lucas und Sarah treiben keinen Sport, aber ich schon.",
"el / un producto": "das / ein Produkt",
"la / una empresa": "die / eine Firma",
"los / unos productos": "die / einige Produkte",
"las / unas empresas": "die / einige Firmen",
"¿Qué? · ¿Quién/es? · ¿Dónde? · ¿De dónde? · ¿Para qué? · ¿Cómo?": "Was? · Wer? · Wo? · Woher? · Wozu? · Wie?",
"Yo también. / Yo no.": "Ich auch. / Ich nicht.",
"Yo tampoco. / Yo sí.": "Ich auch nicht. / Ich schon.",
"cero, uno, dos, tres, cuatro, cinco, seis, siete, ocho, nueve, diez": "null, eins, zwei, drei, vier, fünf, sechs, sieben, acht, neun, zehn",
"Este es el señor Vega.": "Das ist Herr Vega.",
"Esta es Paula Díaz.": "Das ist Paula Díaz.",
"Estos son Andrés y Pablo.": "Das sind Andrés und Pablo.",
"Estas son Ana y Elena.": "Das sind Ana und Elena.",
"Encantado": "Freut mich (Mann)",
"Encantada": "Freut mich (Frau)",
"Mucho gusto": "Sehr erfreut",
"Estos son Laia y Marc.": "Das sind Laia und Marc.",
"¿Cómo se escribe?": "Wie schreibt man das?",
"¿Se escribe con hache?": "Schreibt man das mit h?",
"¿Con acento o sin acento?": "Mit oder ohne Akzent?",
"¿Con mayúscula?": "Großgeschrieben?",
"ingeniero, médico, informático": "Ingenieur, Arzt, Informatiker",
"ingeniera, médica, informática": "Ingenieurin, Ärztin, Informatikerin",
"profesor, programador, diseñador": "Lehrer, Programmierer, Designer",
"profesora, programadora, diseñadora": "Lehrerin, Programmiererin, Designerin",
"el estudiante, el analista": "der Student, der Analyst",
"la estudiante, la analista": "die Studentin, die Analystin",
"el jefe / la jefa": "der Chef / die Chefin",
"Soy ingeniero.": "Ich bin Ingenieur.",
"21 veintiuno": "21",
"22 veintidós": "22",
"23 veintitrés": "23",
"29 veintinueve": "29",
"30 treinta": "30",
"31 treinta y uno": "31",
"40 cuarenta": "40",
"50 cincuenta": "50",
"60 sesenta": "60",
"70 setenta": "70",
"80 ochenta": "80",
"90 noventa": "90",
"100 cien": "100",
"101 ciento uno": "101",
"200 doscientos": "200",
"500 quinientos": "500",
"1000 mil": "1000",
"2000 dos mil": "2000",
"2026 dos mil veintiséis": "2026",
"treinta y cinco": "35",
"cien": "hundert (allein)",
"ciento": "hundert… (vor Zahlen)",
"tengo": "ich habe",
"tienes": "du hast",
"tiene": "er/sie hat, Sie haben",
"tenemos": "wir haben",
"tenéis": "ihr habt",
"tienen": "sie haben, Sie haben (Pl.)",
"Tengo 23 años.": "Ich bin 23 Jahre alt.",
"¿Cuántos años tienes?": "Wie alt bist du?",
"¿Cuál es tu (número de) móvil?": "Wie ist deine Handynummer?",
"Es el 612 34 56 78.": "Sie ist 612 34 56 78.",
"¿Cuál es tu correo electrónico?": "Wie ist deine E-Mail-Adresse?",
"Es pablo.ruiz@correo.es": "Sie ist pablo.ruiz@correo.es",
"¿Cuál es tu dirección?": "Wie ist deine Adresse?",
"Calle Mallorca, número 40.": "Calle Mallorca, Nummer 40.",
"arroba": "@ (at)",
"punto": "Punkt",
"guion": "Bindestrich",
"guion bajo": "Unterstrich",
"c/": "Str. (calle)",
"av.": "Allee (avenida)",
"pl.": "Platz (plaza)",
"n.º": "Nr.",
"seis uno dos, treinta y cuatro, cincuenta y seis, setenta y ocho": "sechs eins zwei, vierunddreißig, sechsundfünfzig, achtundsiebzig",
"aprendo": "ich lerne",
"vivo": "ich wohne",
"aprendes": "du lernst",
"vives": "du wohnst",
"aprende": "er/sie lernt",
"vive": "er/sie wohnt",
"aprendemos": "wir lernen",
"vivimos": "wir wohnen",
"aprendéis": "ihr lernt",
"vivís": "ihr wohnt",
"aprenden": "sie lernen",
"viven": "sie wohnen",
"leer, comer, beber, responder · escribir, asistir, abrir": "lesen, essen, trinken, antworten · schreiben, teilnehmen, öffnen",
"¿Qué haces? / ¿A qué te dedicas?": "Was machst du? / Was machst du beruflich?",
"Soy estudiante. / Trabajo como analista.": "Ich bin Student. / Ich arbeite als Analyst.",
"Trabajo en un banco / en una consultora.": "Ich arbeite in einer Bank / in einer Beratungsfirma.",
"¿Qué estudias?": "Was studierst du?",
"Estudio Informática.": "Ich studiere Informatik.",
"¿Dónde estudias?": "Wo studierst du?",
"En la Universidad Politécnica de Cataluña.": "An der Polytechnischen Universität Katalonien.",
"¿Dónde vives?": "Wo wohnst du?",
"Vivo en Barcelona, en el barrio de Gràcia.": "Ich wohne in Barcelona, im Viertel Gràcia.",
"¿Qué hace usted? ¿Dónde trabaja usted?": "Was machen Sie? Wo arbeiten Sie?",
"Es responsable del contacto con clientes.": "Er/Sie ist für den Kundenkontakt zuständig.",
"Es responsable de la agenda.": "Er/Sie ist für den Terminkalender zuständig.",
"Es responsable de los empleados.": "Er/Sie ist für die Angestellten zuständig.",
"Es responsable de las empresas.": "Er/Sie ist für die Firmen zuständig.",
"Señor: Perdón, ustedes no son argentinos, ¿verdad?": "Herr: Entschuldigung, Sie sind keine Argentinier, oder?",
"Julia: No, no. Somos alemanes.": "Julia: Nein, nein. Wir sind Deutsche.",
"Señor: ¿Aprenden español en Alemania?": "Herr: Lernen Sie Spanisch in Deutschland?",
"Julia: Sí, en la Universidad Popular.": "Julia: Ja, an der Volkshochschule.",
"Paul: Yo trabajo en una empresa que vende tractores y ella escribe para un periódico.": "Paul: Ich arbeite in einer Firma, die Traktoren verkauft, und sie schreibt für eine Zeitung.",
"Señor: Yo vivo en Buenos Aires. Trabajo en una agencia de viajes.": "Herr: Ich wohne in Buenos Aires. Ich arbeite in einem Reisebüro.",
"El señor Garrido es cantante.": "Herr Garrido ist Sänger.",
"Un momento, señora Domínguez.": "Einen Moment, Frau Domínguez.",
"español": "Spanier / spanisch",
"Este es el señor Vega. / Esta es Paula.": "Das ist Herr Vega. / Das ist Paula.",
"Encantado / Encantada / Mucho gusto.": "Freut mich (m / w) / Sehr erfreut.",
"Estos son Andrés y Pablo. / Estas son Ana y Elena.": "Das sind Andrés und Pablo. / Das sind Ana und Elena.",
"¿Cómo se escribe …? · ¿Con hache? · ¿Con acento o sin acento? · ¿Con mayúscula?": "Wie schreibt man …? · Mit h? · Mit oder ohne Akzent? · Großgeschrieben?",
"¿Qué haces?": "Was machst du?",
"Soy ingeniera. / Trabajo como analista.": "Ich bin Ingenieurin. / Ich arbeite als Analystin.",
"En un banco.": "In einer Bank.",
"¿Qué estudias? ¿Dónde?": "Was studierst du? Wo?",
"Informática, en la UPC.": "Informatik, an der UPC.",
"Tengo 24 años.": "Ich bin 24 Jahre alt.",
"¿Cuál es tu móvil / correo?": "Wie ist deine Handynummer / E-Mail?",
"@ arroba · . punto · - guion · _ guion bajo": "@ at · . Punkt · - Bindestrich · _ Unterstrich",
"Es responsable del contacto con clientes / de la agenda.": "Er/Sie ist für den Kundenkontakt / den Terminkalender zuständig.",
"el padre + la madre": "der Vater + die Mutter",
"los padres": "die Eltern",
"el hermano + la hermana": "der Bruder + die Schwester",
"los hermanos": "die Geschwister",
"¿Tienes hermanos?": "Hast du Geschwister?",
"Sí, tengo un hermano.": "Ja, ich habe einen Bruder.",
"No, soy hijo único.": "Nein, ich bin Einzelkind.",
"mi tío / tía": "mein Onkel / meine Tante",
"mis tíos / tías": "meine Onkel / Tanten",
"tu tío / tía": "dein Onkel / deine Tante",
"tus tíos / tías": "deine Onkel / Tanten",
"su tío / tía": "sein/ihr/Ihr Onkel / seine/ihre/Ihre Tante",
"sus tíos / tías": "seine/ihre/Ihre Onkel / Tanten",
"nuestro tío / nuestra tía": "unser Onkel / unsere Tante",
"nuestros tíos / nuestras tías": "unsere Onkel / Tanten",
"vuestro tío / vuestra tía": "euer Onkel / eure Tante",
"vuestros tíos / vuestras tías": "eure Onkel / Tanten",
"mis padres": "meine Eltern",
"un hombre delgado": "ein schlanker Mann",
"una mujer delgada": "eine schlanke Frau",
"un niño alegre / un producto especial": "ein fröhlicher Junge / ein besonderes Produkt",
"una niña alegre / una persona especial": "ein fröhliches Mädchen / eine besondere Person",
"hombres delgados": "schlanke Männer",
"mujeres delgadas": "schlanke Frauen",
"Es muy alto.": "Er ist sehr groß.",
"Es bastante alto.": "Er ist ziemlich groß.",
"Es un poco vago.": "Er ist ein bisschen faul.",
"muy, bastante, un poco": "sehr, ziemlich, ein bisschen",
"estoy": "ich bin (Zustand, Ort)",
"estás": "du bist",
"está": "er/sie ist, Sie sind",
"estamos": "wir sind",
"estáis": "ihr seid",
"están": "sie sind, Sie sind (Pl.)",
"Es Juan. (Name)": "Das ist Juan.",
"Estoy en Barcelona. (Ort)": "Ich bin in Barcelona.",
"Es ingeniera. (Beruf)": "Sie ist Ingenieurin.",
"La FIB está en Campus Nord. (Ort)": "Die FIB ist auf dem Campus Nord.",
"Es de Cádiz. (Herkunft)": "Er/Sie kommt aus Cádiz.",
"¿Cómo estás? – Estoy bien. (Befinden)": "Wie geht es dir? – Mir geht es gut.",
"Es alto y simpático. (Eigenschaft)": "Er ist groß und sympathisch.",
"Estoy cansado. (Zustand gerade)": "Ich bin müde.",
"gusta la músicagusta viajar": "mir gefällt die Musik / ich reise gern",
"gustan los idiomasgustan las fiestas": "mir gefallen Sprachen / Partys",
"interesar": "interessieren",
"molestar": "stören",
"Me gusta la música": "Ich mag Musik.",
"¿Te gusta la rutina?": "Magst du Routine?",
"Sí, mucho. / Sí, bastante. / No, nada.": "Ja, sehr. / Ja, ziemlich. / Nein, gar nicht.",
"¿Le interesa viajar?": "Interessieren Sie sich fürs Reisen?",
"No mucho.": "Nicht besonders.",
"¿Te molestan las discusiones?": "Stören dich Diskussionen?",
"Un poco.": "Ein bisschen.",
"¿Cuánto tiempo pasas con tu familia?": "Wie viel Zeit verbringst du mit deiner Familie?",
"¿Cuánta gente trabaja aquí?": "Wie viele Leute arbeiten hier?",
"¿Cuántas horas trabajas?": "Wie viele Stunden arbeitest du?",
"José (el abuelo) y Amalia (la abuela)": "José (der Großvater) und Amalia (die Großmutter)",
"Alberto (el padre) y Ana (la madre)": "Alberto (der Vater) und Ana (die Mutter)",
"Teresa (la tía, hija de José y Amalia) y Pepe (el tío)": "Teresa (die Tante, Tochter von José und Amalia) und Pepe (der Onkel)",
"Marta y Roberto (el hermano)": "Marta und Roberto (der Bruder)",
"Laura (la prima) y Lucas (el primo)": "Laura (die Cousine) und Lucas (der Cousin)",
"el sobrino / la sobrina": "der Neffe / die Nichte",
"el marido / la mujer": "der Ehemann / die Ehefrau",
"el yerno": "der Schwiegersohn",
"la nuera": "die Schwiegertochter",
"el suegro / la suegra": "der Schwiegervater / die Schwiegermutter",
"el cuñado / la cuñada": "der Schwager / die Schwägerin",
"el nieto": "der Enkel",
"el padre · la madre · los padres · el hermano · la hermana · el hijo · la hija · el abuelo · la abuela · el tío · la tía · el primo · la prima": "der Vater · die Mutter · die Eltern · der Bruder · die Schwester · der Sohn · die Tochter · der Großvater · die Großmutter · der Onkel · die Tante · der Cousin · die Cousine",
"Es cocinero. Es de Cádiz.": "Er ist Koch. Er kommt aus Cádiz.",
"Está en Novelda. ¿Cómo estás?": "Er/Sie ist in Novelda. Wie geht es dir?",
"gusta + Sg. / Infinitiv · gustan + Pl.": "gusta + Singular / Infinitiv · gustan + Plural",
"Me gusta la rutina. Te molesta trabajar con estrés. Le interesan las discusiones.": "Ich mag Routine. Dich stört Arbeit unter Stress. Ihn/Sie interessieren die Diskussionen.",
"¿Cuánto tiempo? · ¿Cuánta gente? · ¿Cuántos años? · ¿Cuántas horas?": "Wie viel Zeit? · Wie viele Leute? · Wie viele Jahre? · Wie viele Stunden?",
"el desayuno": "das Frühstück",
"desayunar": "frühstücken",
"el almuerzo": "das Mittagessen (leichtes)",
"almorzar": "zu Mittag essen",
"la comida": "das Essen / Mittagessen",
"comer": "essen",
"la merienda": "der Nachmittagssnack",
"merendar": "nachmittags etwas essen",
"la cena": "das Abendessen",
"cenar": "zu Abend essen",
"¿Dónde comes hoy?": "Wo isst du heute?",
"siempre": "immer",
"todos los días": "jeden Tag",
"muchas veces": "oft",
"a veces": "manchmal",
"pocas veces": "selten",
"nunca": "nie",
"dos veces a la semana": "zweimal pro Woche",
"cinco veces al día": "fünfmal am Tag",
"Nunca tomo pescado.": "Ich esse nie Fisch.",
"No tomo nunca pescado.": "Ich esse nie Fisch.",
"el lunes": "am Montag (diesen)",
"los lunes": "montags (jeden)",
"De lunes a viernes": "von Montag bis Freitag",
"puedo": "ich kann",
"quiero": "ich will",
"prefiero": "ich ziehe vor",
"puedes": "du kannst",
"quieres": "du willst",
"prefieres": "du ziehst vor",
"puede": "er/sie kann",
"quiere": "er/sie will",
"prefiere": "er/sie zieht vor",
"podemos": "wir können",
"queremos": "wir wollen",
"preferimos": "wir ziehen vor",
"podéis": "ihr könnt",
"queréis": "ihr wollt",
"preferís": "ihr zieht vor",
"pueden": "sie können",
"quieren": "sie wollen",
"prefieren": "sie ziehen vor",
"almorzar (almuerzo), costar (cuesta), volver (vuelvo), empezar (empiezo), pensar (pienso)": "zu Mittag essen (ich esse), kosten (es kostet), zurückkommen (ich komme zurück), anfangen (ich fange an), denken (ich denke)",
"Es la una.": "Es ist ein Uhr.",
"Son las dos.": "Es ist zwei Uhr.",
"Son las dos y cuarto.": "Es ist Viertel nach zwei.",
"Son las dos y media.": "Es ist halb drei.",
"Son las tres menos cuarto.": "Es ist Viertel vor drei.",
"Son las tres menos diez.": "Es ist zehn vor drei.",
"Son las dos y diez.": "Es ist zehn nach zwei.",
"¿A qué hora comes?": "Um wie viel Uhr isst du?",
"A las dos y media.": "Um halb drei.",
"El martes por la tarde tengo una reunión.": "Am Dienstagnachmittag habe ich eine Besprechung.",
"a las nueve de la mañana / de la noche": "um neun Uhr morgens / abends",
"de dos a diez": "von zwei bis zehn",
"por la mañana / por la tarde / por la noche": "morgens / nachmittags / abends",
"de la mañana": "morgens (bei Uhrzeit)",
"lo": "ihn / es",
"la": "sie",
"los": "sie (m. Pl.)",
"las": "sie (f. Pl.)",
"¿Quién compra la carne? – La compro yo.": "Wer kauft das Fleisch? – Ich kaufe es.",
"¿Tomas el café con leche? – No, lo tomo solo.": "Trinkst du den Kaffee mit Milch? – Nein, ich trinke ihn schwarz.",
"No las compro.": "Ich kaufe sie nicht.",
"Se puede pagar con tarjeta.": "Man kann mit Karte bezahlen.",
"El gazpacho se come frío.": "Gazpacho isst man kalt.",
"Aquí se beben vinos italianos.": "Hier trinkt man italienische Weine.",
"un kilo de patatas": "ein Kilo Kartoffeln",
"cien gramos de jamón": "hundert Gramm Schinken",
"medio litro de zumo": "ein halber Liter Saft",
"un kilo y medio de carne": "anderthalb Kilo Fleisch",
"una botella de agua · una lata de cerveza · un paquete de café": "eine Flasche Wasser · eine Dose Bier · ein Päckchen Kaffee",
"suizo / suiza": "Schweizer / Schweizerin",
"español / española": "Spanier / Spanierin",
"belga": "Belgier/in",
"argentino / argentina": "Argentinier / Argentinierin",
"alemán / alemana": "Deutscher / Deutsche",
"marroquí": "Marokkaner/in",
"italiano / italiana": "Italiener / Italienerin",
"inglés / inglesa": "Engländer / Engländerin",
"estadounidense": "US-Amerikaner/in",
"austriaco / austriaca": "Österreicher / Österreicherin",
"francés / francesa": "Franzose / Französin",
"canadiense": "Kanadier/in",
"alemán → alemana": "deutsch → deutsch (f)",
"en punto": "genau / Punkt (Uhrzeit)",
"y cinco / y diez": "fünf nach / zehn nach",
"y cuarto": "Viertel nach",
"y veinte / y veinticinco": "zwanzig nach / fünf vor halb",
"y media": "halb",
"menos veinticinco / menos veinte": "fünf nach halb / zehn nach halb",
"menos cuarto": "Viertel vor",
"menos diez / menos cinco": "zehn vor / fünf vor",
"Normalmente como en la cantina, aunque prefiero comer en casa.": "Normalerweise esse ich in der Kantine, obwohl ich lieber zu Hause esse.",
"Desayuno todos los días. · Como de todo. · Soy vegetariano/-a. · No puedo beber alcohol. · Prefiero el café sin leche.": "Ich frühstücke jeden Tag. · Ich esse alles. · Ich bin Vegetarier/in. · Ich darf keinen Alkohol trinken. · Ich trinke den Kaffee lieber ohne Milch.",
"siempre · todos los días · muchas veces · a veces · pocas veces · nunca · dos veces a la semana": "immer · jeden Tag · oft · manchmal · selten · nie · zweimal pro Woche",
"lunes · martes · miércoles · jueves · viernes · sábado · domingo — el lunes (diesen) / los lunes (jeden)": "Montag · Dienstag · Mittwoch · Donnerstag · Freitag · Samstag · Sonntag — am Montag (diesen) / montags (jeden)",
"Es la una. · Son las dos y cuarto / y media / menos cuarto.": "Es ist ein Uhr. · Es ist Viertel nach zwei / halb drei / Viertel vor drei.",
"¿A qué hora …? – A las tres. · por la mañana / tarde / noche": "Um wie viel Uhr …? – Um drei. · morgens / nachmittags / abends",
"¿Hay mesas libres? · ¿Para cuántas personas? · ¿A nombre de quién?": "Gibt es freie Tische? · Für wie viele Personen? · Auf welchen Namen?",
"De primero … · De segundo … · ¿Y para beber? · La cuenta, por favor.": "Als Vorspeise … · Als Hauptgericht … · Und zu trinken? · Die Rechnung, bitte.",
"La compro yo. No lo tomo.": "Ich kaufe sie. Ich trinke ihn nicht.",
"un kilo de · cien gramos de · medio litro de · una botella de": "ein Kilo · hundert Gramm · ein halber Liter · eine Flasche",
"En Barcelona hay una catedral famosa.": "In Barcelona gibt es eine berühmte Kathedrale.",
"La Sagrada Família está en el Eixample.": "Die Sagrada Família ist im Eixample.",
"Hay muchos bares y restaurantes.": "Es gibt viele Bars und Restaurants.",
"Mi hotel está en el casco antiguo.": "Mein Hotel ist in der Altstadt.",
"Hay más de 300 ferias al año.": "Es gibt mehr als 300 Messen im Jahr.",
"Los servicios están al lado del restaurante.": "Die Toiletten sind neben dem Restaurant.",
"hay dos parques": "es gibt zwei Parks",
"mucho tráfico · mucha gente · muchos trenes · muchas obras": "viel Verkehr · viele Leute · viele Züge · viele Baustellen",
"Es muy difícil llegar. · Está muy cerca.": "Es ist sehr schwer hinzukommen. · Es ist sehr nah.",
"mucho": "viel",
"No uso mucho la bicicleta. ¿Te gusta? – Sí, mucho.": "Ich fahre nicht viel Fahrrad. Gefällt es dir? – Ja, sehr.",
"voy": "ich gehe / fahre",
"vas": "du gehst",
"va": "er/sie geht",
"vamos": "wir gehen",
"vais": "ihr geht",
"van": "sie gehen",
"Voy a Guadalajara. · Vamos a la oficina.": "Ich fahre nach Guadalajara. · Wir gehen ins Büro.",
"Voy en metro / en tren / en coche / en bici / en avión": "Ich fahre mit der U-Bahn / dem Zug / dem Auto / dem Rad / dem Flugzeug",
"Voy a pie / andando.": "Ich gehe zu Fuß.",
"Voy al aeropuerto.": "Ich fahre zum Flughafen.",
"a la estación": "zum Bahnhof",
"sigo · sigues · sigue · seguimos · seguís · siguen": "ich folge · du folgst · er folgt · wir folgen · ihr folgt · sie folgen",
"Tienes que tomar el autobús. Tenéis que bajar en la próxima parada.": "Du musst den Bus nehmen. Ihr müsst an der nächsten Haltestelle aussteigen.",
"primero … después … luego … al final …": "zuerst … danach … dann … am Ende …",
"Primero sigue todo recto. Después gira a la derecha. Luego cruza la plaza y al final está el museo, a la izquierda.": "Geh zuerst geradeaus. Dann bieg rechts ab. Dann überquer den Platz, und am Ende ist das Museum, links.",
"cerca de ↔ lejos de": "nahe bei ↔ weit weg von",
"delante de ↔ detrás de": "vor ↔ hinter",
"a la izquierda de ↔ a la derecha de": "links von ↔ rechts von",
"al lado de · enfrente de · entre … y …": "neben · gegenüber · zwischen … und …",
"al lado del hotel": "neben dem Hotel",
"cerca del metro": "in der Nähe der Metro",
"porque": "weil",
"Es fácil llegar porque está cerca del aeropuerto.": "Es ist leicht hinzukommen, weil es nahe am Flughafen ist.",
"por eso": "deshalb",
"Está cerca del aeropuerto, por eso es fácil llegar.": "Es ist nahe am Flughafen, deshalb ist es leicht hinzukommen.",
"pero": "aber",
"El metro es rápido, pero hay mucha gente.": "Die Metro ist schnell, aber es sind viele Leute da.",
"y / también": "und / auch",
"Hay parques y también playas.": "Es gibt Parks und auch Strände.",
"¿Sabe dónde está la biblioteca? – Sí, está …": "Wissen Sie, wo die Bibliothek ist? – Ja, sie ist …",
"¿Sabe si hay algún correo aquí cerca? – Sí, hay uno …": "Wissen Sie, ob es hier in der Nähe eine Post gibt? – Ja, es gibt eine …",
"¿Sabe si la biblioteca está cerca de aquí?": "Wissen Sie, ob die Bibliothek hier in der Nähe ist?",
"¿Hay algún café cerca de aquí? – No, no hay ninguno.": "Gibt es hier in der Nähe ein Café? – Nein, es gibt keins.",
"Barcelona es una ciudad atractiva. Hay muchos bares y restaurantes. La catedral está en el casco antiguo.": "Barcelona ist eine attraktive Stadt. Es gibt viele Bars und Restaurants. Die Kathedrale ist in der Altstadt.",
"Hay una catedral famosa.": "Es gibt eine berühmte Kathedrale.",
"¿Dónde está la Sagrada Família?": "Wo ist die Sagrada Família?",
"mucho tráfico, mucha gente, muchos trenes · Es muy fácil. · Trabajo mucho.": "viel Verkehr, viele Leute, viele Züge · Es ist sehr leicht. · Ich arbeite viel.",
"Perdone, ¿sabe dónde está …? · Sigue todo recto. · Gira a la derecha / izquierda. · Cruza la calle. · Primero … después … luego … al final …": "Entschuldigung, wissen Sie, wo … ist? · Geh geradeaus. · Bieg rechts / links ab. · Überquer die Straße. · Zuerst … danach … dann … am Ende …",
"cerca de / lejos de · delante de / detrás de · a la derecha de / a la izquierda de · al lado de · enfrente de · entre … y …": "nahe bei / weit weg von · vor / hinter · rechts / links von · neben · gegenüber · zwischen … und …",
"porque (weil) · por eso (deshalb) · pero (aber)": "weil · deshalb · aber"
});
