/* ================= GESCHICHTEN: „Nuevo en Barcelona“ – Serie zum Lesen & Hören =================
   Ben, ein deutscher Student, zieht nach Barcelona. Jede Geschichte nutzt nur Grammatik bis zur Unidad in `after`.
   text: {Wort|Übersetzung} = antippbar. qs: Verständnisfragen (Multiple Choice, a = Index der richtigen Antwort). */
window.STORIES=[
{id:'s1',after:'u1',title:'¡Hola, Barcelona!',sub:'Ben kommt an',text:`Me llamo Ben. Soy {alemán|Deutscher}, de Hamburgo. Estudio informática y ahora {vivo|wohne} en Barcelona. ¡Es mi primer día!

En el aeropuerto hablo con una chica. Se llama Laia y es de Barcelona. Laia estudia {inglés|Englisch} y alemán. Habla muy bien. —¿Hablas español? —pregunta Laia. —Un poco —digo yo—. Necesito practicar. —¡Yo también necesito practicar alemán! —dice ella.

Laia y yo {tomamos|nehmen} el autobús al centro. Es fantástico: ¡ya tengo una amiga!`,
de:`Ich heiße Ben. Ich bin Deutscher, aus Hamburg. Ich studiere Informatik und wohne jetzt in Barcelona. Es ist mein erster Tag!\n\nAm Flughafen spreche ich mit einem Mädchen. Sie heißt Laia und ist aus Barcelona. Laia studiert Englisch und Deutsch. Sie spricht sehr gut. „Sprichst du Spanisch?“, fragt Laia. „Ein bisschen“, sage ich. „Ich muss üben.“ „Ich muss auch Deutsch üben!“, sagt sie.\n\nLaia und ich nehmen den Bus ins Zentrum. Es ist fantastisch: Ich habe schon eine Freundin!`,
qs:[{q:'¿De dónde es Ben?',opts:['de Hamburgo','de Barcelona','de Berlín'],a:0},{q:'¿Qué estudia Laia?',opts:['inglés y alemán','informática','español'],a:0},{q:'¿Cómo van al centro?',opts:['en autobús','en metro','a pie'],a:0}]},

{id:'s2',after:'u3',title:'El piso de Nuria',sub:'Die neue WG',text:`Mi piso está en Gràcia, un barrio muy bonito. {Comparto|Ich teile} el piso con Nuria y Pablo. Nuria es de Valencia. Es alta, {morena|dunkelhaarig} y muy simpática. Trabaja en una agencia de publicidad. Pablo es de Sevilla, es estudiante y es un poco caótico.

El piso es pequeño pero tiene un balcón. A Nuria le gusta mucho {cocinar|kochen}. A Pablo le gusta la música... ¡a las dos de la mañana! A mí me gustan las plantas del balcón y el {ambiente|die Atmosphäre} del barrio.

Nuria tiene una hermana y dos hermanos. Su familia es muy grande y siempre llama por teléfono. —Mi madre está {preocupada|besorgt} —dice Nuria—. ¡Siempre pregunta si como bien!`,
de:`Meine Wohnung ist in Gràcia, einem sehr schönen Viertel. Ich teile die Wohnung mit Nuria und Pablo. Nuria ist aus Valencia. Sie ist groß, dunkelhaarig und sehr sympathisch. Sie arbeitet in einer Werbeagentur. Pablo ist aus Sevilla, Student und ein bisschen chaotisch.\n\nDie Wohnung ist klein, aber sie hat einen Balkon. Nuria kocht sehr gern. Pablo mag Musik … um zwei Uhr morgens! Mir gefallen die Pflanzen auf dem Balkon und die Atmosphäre im Viertel.\n\nNuria hat eine Schwester und zwei Brüder. Ihre Familie ist sehr groß und ruft immer an. „Meine Mutter ist besorgt“, sagt Nuria. „Sie fragt immer, ob ich gut esse!“`,
qs:[{q:'¿Cómo es Pablo?',opts:['un poco caótico','muy ordenado','tímido'],a:0},{q:'¿Qué le gusta a Nuria?',opts:['cocinar','la música por la noche','las plantas'],a:0},{q:'¿Cuántos hermanos tiene Nuria?',opts:['tres','dos','uno'],a:0}]},

{id:'s3',after:'u4',title:'Una cena a las diez',sub:'Essen wie die Spanier',text:`Hoy Marc, un compañero de la universidad, me invita a cenar. —¿A qué hora quedamos? —pregunto. —¿A las diez? —dice Marc. ¡A las diez! En Alemania a las diez ya {estoy en la cama|liege ich im Bett}.

Vamos a un bar de tapas en el Born. Hay mucha gente. Pedimos patatas bravas, pan con tomate, croquetas y {calamares|Tintenfisch}. Para beber, Marc toma una cerveza y yo un agua con gas. —¿Y de postre? —pregunta el camarero. —Una crema catalana, por favor —dice Marc—. Es típica de aquí.

Al final pedimos la cuenta. Son treinta euros. —Hoy pago yo —dice Marc—. ¡{Bienvenido|Willkommen} a Barcelona!`,
de:`Heute lädt mich Marc, ein Kommilitone, zum Abendessen ein. „Um wie viel Uhr treffen wir uns?“, frage ich. „Um zehn?“, sagt Marc. Um zehn! In Deutschland liege ich um zehn schon im Bett.\n\nWir gehen in eine Tapas-Bar im Born. Es sind viele Leute da. Wir bestellen Patatas bravas, Pan con tomate, Kroketten und Tintenfisch. Zu trinken nimmt Marc ein Bier und ich ein Wasser mit Kohlensäure. „Und als Nachtisch?“, fragt der Kellner. „Eine Crema catalana, bitte“, sagt Marc. „Die ist typisch für hier.“\n\nZum Schluss bitten wir um die Rechnung. Es sind dreißig Euro. „Heute zahle ich“, sagt Marc. „Willkommen in Barcelona!“`,
qs:[{q:'¿A qué hora cenan?',opts:['a las diez','a las ocho','a las siete'],a:0},{q:'¿Qué toma Ben para beber?',opts:['agua con gas','cerveza','vino'],a:0},{q:'¿Quién paga?',opts:['Marc','Ben','los dos'],a:0}]},

{id:'s4',after:'u5',title:'Perdido en el metro',sub:'Der falsche Weg',text:`El sábado quiero ir a la playa de la Barceloneta. Tomo el metro en Fontana, la línea verde. Pero no {cambio|steige um} de línea en Passeig de Gràcia y llego a... ¡Zona Universitaria! Estoy muy lejos de la playa.

Pregunto a una señora: —Perdone, ¿sabe dónde está la playa? —¡Uy, está muy lejos! —dice ella—. Tome la línea verde otra vez y cambie a la línea amarilla en Passeig de Gràcia. Baje en Barceloneta. Después siga todo recto unos diez minutos.

Una hora después estoy en la playa. Hace sol, hay mucha gente y el mar es azul. —Bueno —pienso—, ahora conozco muy bien el metro de Barcelona.`,
de:`Am Samstag will ich an den Strand von Barceloneta. Ich nehme die Metro in Fontana, die grüne Linie. Aber ich steige in Passeig de Gràcia nicht um und komme an … Zona Universitaria! Ich bin sehr weit weg vom Strand.\n\nIch frage eine Dame: „Entschuldigung, wissen Sie, wo der Strand ist?“ „Oh, der ist sehr weit weg!“, sagt sie. „Nehmen Sie wieder die grüne Linie und steigen Sie in Passeig de Gràcia in die gelbe Linie um. Steigen Sie in Barceloneta aus. Danach gehen Sie etwa zehn Minuten geradeaus.“\n\nEine Stunde später bin ich am Strand. Die Sonne scheint, es sind viele Leute da und das Meer ist blau. „Na ja“, denke ich, „jetzt kenne ich die Metro von Barcelona sehr gut.“`,
qs:[{q:'¿Qué error hace Ben?',opts:['No cambia de línea.','Toma un taxi.','Baja en Barceloneta.'],a:0},{q:'¿En qué estación tiene que cambiar?',opts:['Passeig de Gràcia','Fontana','Zona Universitaria'],a:0},{q:'¿Cuánto tiempo necesita para llegar a la playa?',opts:['una hora','diez minutos','todo el día'],a:0}]},

{id:'s5',after:'u6',title:'Un fin de semana en Sitges',sub:'Was haben sie gemacht?',text:`Este fin de semana Laia y yo hemos ido a Sitges, un pueblo en la costa, a cuarenta minutos de Barcelona en tren. ¡Ha sido genial!

Hemos llegado el sábado por la mañana. Primero hemos paseado por el casco antiguo, con sus casas blancas y sus calles {estrechas|eng}. Después hemos comido una paella en un restaurante al lado del mar. Por la tarde hemos nadado un poco, aunque el agua estaba fría.

Laia me ha preguntado: —¿Has estado alguna vez en un pueblo así? —No, nunca —he dicho yo—. En Hamburgo también hay mar, pero no hay palmeras. Hemos vuelto a casa muy tarde y muy cansados, pero muy {contentos|zufrieden}.`,
de:`Dieses Wochenende sind Laia und ich nach Sitges gefahren, einem Ort an der Küste, vierzig Minuten mit dem Zug von Barcelona. Es war genial!\n\nWir sind am Samstagmorgen angekommen. Zuerst sind wir durch die Altstadt spaziert, mit ihren weißen Häusern und engen Gassen. Danach haben wir in einem Restaurant am Meer Paella gegessen. Am Nachmittag sind wir ein bisschen geschwommen, obwohl das Wasser kalt war.\n\nLaia hat mich gefragt: „Warst du schon einmal in so einem Ort?“ „Nein, nie“, habe ich gesagt. „In Hamburg gibt es auch Meer, aber keine Palmen.“ Wir sind sehr spät und sehr müde, aber sehr zufrieden nach Hause gekommen.`,
qs:[{q:'¿Cómo han ido a Sitges?',opts:['en tren','en coche','en autobús'],a:0},{q:'¿Qué han hecho por la tarde?',opts:['Han nadado.','Han visitado un museo.','Han dormido.'],a:0},{q:'¿Qué no hay en Hamburgo, según Ben?',opts:['palmeras','mar','restaurantes'],a:0}]},

{id:'s6',after:'u7',title:'Un día normal... o no',sub:'Bens Alltag',text:`Normalmente me levanto a las siete y media. Me ducho, me visto y desayuno un café con leche y una tostada. A las nueve tengo clase en la universidad. Mi compañero Marc siempre llega tarde: es más simpático que yo, pero menos {puntual|pünktlich}.

Pero hoy no es un día normal. Hoy me he despertado a las nueve menos cuarto. ¡La alarma no ha {sonado|geklingelt}! Me he vestido en dos minutos, no he desayunado y he corrido al metro.

Cuando he llegado a clase, el profesor estaba explicando algo en la pizarra. Marc me ha mirado y ha dicho en voz baja: —Hoy tú eres el que llega tarde. ¡Por fin no soy el único!`,
de:`Normalerweise stehe ich um halb acht auf. Ich dusche, ziehe mich an und frühstücke einen Milchkaffee und einen Toast. Um neun habe ich Unterricht an der Uni. Mein Kommilitone Marc kommt immer zu spät: Er ist sympathischer als ich, aber weniger pünktlich.\n\nAber heute ist kein normaler Tag. Heute bin ich um Viertel vor neun aufgewacht. Der Wecker hat nicht geklingelt! Ich habe mich in zwei Minuten angezogen, nicht gefrühstückt und bin zur Metro gerannt.\n\nAls ich im Unterricht angekommen bin, hat der Professor gerade etwas an der Tafel erklärt. Marc hat mich angeschaut und leise gesagt: „Heute bist du derjenige, der zu spät kommt. Endlich bin ich nicht der Einzige!“`,
qs:[{q:'¿A qué hora se levanta Ben normalmente?',opts:['a las siete y media','a las nueve','a las nueve menos cuarto'],a:0},{q:'¿Por qué llega tarde hoy?',opts:['La alarma no ha sonado.','Ha perdido el metro.','Ha desayunado mucho.'],a:0},{q:'¿Cómo es Marc, comparado con Ben?',opts:['más simpático pero menos puntual','más puntual','menos simpático'],a:0}]},

{id:'s7',after:'u8',title:'Planes para el puente',sub:'Ein langes Wochenende',text:`El jueves es {festivo|Feiertag} y muchos catalanes hacen «puente»: no trabajan el viernes y tienen cuatro días libres. Nuria va a visitar a su familia en Valencia. Pablo va a ir a un festival de música. ¿Y yo?

—¿Qué vas a hacer tú? —me pregunta Laia. —No sé. ¿Tienes ganas de ir a los Pirineos? —¡Me encanta la idea! Pero mira el tiempo: el jueves va a llover y va a hacer frío. —Pues {llevamos|wir nehmen mit} chaquetas y botas —digo yo.

Al final vamos a ir a Puigcerdà, un pueblo en la montaña. Vamos a hacer {senderismo|Wandern} el viernes y el sábado. El domingo, si hace buen tiempo, vamos a volver por la costa. —¡Va a ser un puente perfecto! —dice Laia.`,
de:`Am Donnerstag ist Feiertag und viele Katalanen machen eine „Brücke“: Sie arbeiten am Freitag nicht und haben vier freie Tage. Nuria wird ihre Familie in Valencia besuchen. Pablo wird auf ein Musikfestival gehen. Und ich?\n\n„Was machst du?“, fragt mich Laia. „Weiß nicht. Hast du Lust, in die Pyrenäen zu fahren?“ „Ich liebe die Idee! Aber schau dir das Wetter an: Am Donnerstag wird es regnen und kalt sein.“ „Dann nehmen wir Jacken und Stiefel mit“, sage ich.\n\nAm Ende fahren wir nach Puigcerdà, einem Dorf in den Bergen. Am Freitag und Samstag werden wir wandern. Am Sonntag fahren wir, wenn das Wetter gut ist, über die Küste zurück. „Das wird eine perfekte Brücke!“, sagt Laia.`,
qs:[{q:'¿Qué significa «hacer puente»?',opts:['tener días libres entre un festivo y el fin de semana','construir un puente','trabajar el fin de semana'],a:0},{q:'¿Qué tiempo va a hacer el jueves?',opts:['Va a llover y hacer frío.','Va a hacer sol.','Va a nevar.'],a:0},{q:'¿Qué van a hacer en Puigcerdà?',opts:['senderismo','ir a la playa','visitar a la familia'],a:0}]},

{id:'s8',after:'u9',title:'Cuando la abuela era joven',sub:'Barcelona früher',text:`El domingo Nuria y yo visitamos al señor Puig, nuestro {casero|Vermieter}. Tiene ochenta años y vive en el primer piso. Nos invita a un café y nos enseña fotos antiguas.

—Cuando yo era joven, Gràcia era muy diferente —dice—. No había tantos turistas. Todos los vecinos se conocían. Los niños jugaban en la calle y las {abuelas|Großmütter} se sentaban delante de las puertas por la tarde. Mi padre tenía una pequeña tienda de {zapatos|Schuhe} en esta calle.

—¿Y qué hacían los jóvenes los fines de semana? —pregunto yo. —Íbamos a bailar a la plaza del Sol. No teníamos móviles, así que quedábamos siempre a la misma hora en el mismo lugar. ¡Y nadie llegaba tarde! —dice, y se ríe.`,
de:`Am Sonntag besuchen Nuria und ich Herrn Puig, unseren Vermieter. Er ist achtzig Jahre alt und wohnt im ersten Stock. Er lädt uns auf einen Kaffee ein und zeigt uns alte Fotos.\n\n„Als ich jung war, war Gràcia ganz anders“, sagt er. „Es gab nicht so viele Touristen. Alle Nachbarn kannten sich. Die Kinder spielten auf der Straße und die Großmütter setzten sich nachmittags vor die Türen. Mein Vater hatte in dieser Straße einen kleinen Schuhladen.“\n\n„Und was machten die jungen Leute am Wochenende?“, frage ich. „Wir gingen auf der Plaza del Sol tanzen. Wir hatten keine Handys, also trafen wir uns immer zur selben Zeit am selben Ort. Und keiner kam zu spät!“, sagt er und lacht.`,
qs:[{q:'¿Qué tenía el padre del señor Puig?',opts:['una tienda de zapatos','un bar','una panadería'],a:0},{q:'¿Dónde jugaban los niños?',opts:['en la calle','en el parque','en casa'],a:0},{q:'¿Por qué quedaban siempre a la misma hora?',opts:['porque no tenían móviles','porque trabajaban mucho','porque eran puntuales'],a:0}]},

{id:'s9',after:'u10',title:'La entrevista de Marc',sub:'Ein wichtiger Tag',text:`Marc buscaba unas prácticas desde hacía meses. La semana pasada por fin lo llamaron de una empresa de tecnología en el 22@, el barrio de las {startups|Start-ups}.

El día de la entrevista se levantó a las seis, se puso su mejor camisa y repasó su currículum tres veces. Llegó media hora antes. La entrevistadora era muy amable. Le preguntó por sus estudios, por sus puntos fuertes y por qué quería trabajar allí. Marc contestó con calma, aunque estaba muy nervioso.

Al final ella le preguntó: —¿Habla usted otros idiomas? —Catalán, castellano, inglés... y estoy aprendiendo alemán con un amigo —dijo Marc. Ella sonrió. Dos días después lo llamaron otra vez: ¡consiguió el puesto! Esa noche lo celebramos en el bar de siempre.`,
de:`Marc suchte seit Monaten ein Praktikum. Letzte Woche rief ihn endlich ein Technologieunternehmen im 22@ an, dem Start-up-Viertel.\n\nAm Tag des Vorstellungsgesprächs stand er um sechs auf, zog sein bestes Hemd an und ging seinen Lebenslauf dreimal durch. Er kam eine halbe Stunde zu früh. Die Interviewerin war sehr freundlich. Sie fragte ihn nach seinem Studium, nach seinen Stärken und warum er dort arbeiten wollte. Marc antwortete ruhig, obwohl er sehr nervös war.\n\nZum Schluss fragte sie ihn: „Sprechen Sie andere Sprachen?“ „Katalanisch, Spanisch, Englisch … und ich lerne gerade Deutsch mit einem Freund“, sagte Marc. Sie lächelte. Zwei Tage später riefen sie ihn wieder an: Er bekam die Stelle! An diesem Abend feierten wir in der üblichen Bar.`,
qs:[{q:'¿Qué buscaba Marc?',opts:['unas prácticas','un piso','un curso de alemán'],a:0},{q:'¿Cómo estaba Marc durante la entrevista?',opts:['nervioso pero tranquilo al hablar','muy relajado','enfadado'],a:0},{q:'¿Qué pasó dos días después?',opts:['Le dieron el puesto.','Tuvo otra entrevista.','Lo llamaron para decir que no.'],a:0}]},

{id:'s10',after:'u11',title:'Fiebre en la Mercè',sub:'Krank zur Fiesta',text:`La Mercè es la gran fiesta de Barcelona, en septiembre. Hay conciertos, {castellers|Menschentürme} y el «correfoc», con fuego y música por las calles. Yo tenía muchas ganas de verlo todo.

Pero el viernes me desperté con fiebre. Me dolía la cabeza y la garganta. Nuria me miró y dijo: —Tienes muy mala cara. Quédate en la cama, bebe mucha agua y toma un ibuprofeno. Y no salgas esta noche. —¡Pero es el correfoc! —dije yo. —El año que viene hay otro —contestó ella.

Nuria fue a la farmacia y me trajo un jarabe y una sopa de su madre. El domingo ya me encontraba mejor y pude ver los castellers en la plaza Sant Jaume. Eran increíbles: ¡nueve {pisos|Etagen} de personas!`,
de:`Die Mercè ist das große Fest von Barcelona, im September. Es gibt Konzerte, Menschentürme und den „Correfoc“ mit Feuer und Musik durch die Straßen. Ich hatte große Lust, alles zu sehen.\n\nAber am Freitag wachte ich mit Fieber auf. Mir taten Kopf und Hals weh. Nuria sah mich an und sagte: „Du siehst echt schlecht aus. Bleib im Bett, trink viel Wasser und nimm ein Ibuprofen. Und geh heute Abend nicht raus.“ „Aber es ist der Correfoc!“, sagte ich. „Nächstes Jahr gibt es wieder einen“, antwortete sie.\n\nNuria ging in die Apotheke und brachte mir einen Hustensaft und eine Suppe von ihrer Mutter. Am Sonntag ging es mir schon besser und ich konnte die Menschentürme auf der Plaza Sant Jaume sehen. Sie waren unglaublich: neun Stockwerke aus Menschen!`,
qs:[{q:'¿Qué le pasaba a Ben el viernes?',opts:['Tenía fiebre y le dolía la garganta.','Se había roto una pierna.','Estaba muy cansado de bailar.'],a:0},{q:'¿Qué le dijo Nuria?',opts:['Quédate en la cama.','Ve al correfoc.','Ve al médico enseguida.'],a:0},{q:'¿Qué vio Ben el domingo?',opts:['los castellers','el correfoc','un concierto'],a:0}]},

{id:'s11',after:'u16',title:'Ojalá no llueva',sub:'Besuch aus Deutschland',text:`Mañana llega mi amigo Lukas desde Mannheim y quiero que todo sea perfecto. Le he escrito una lista de consejos: «Te recomiendo que traigas ropa ligera, pero también una chaqueta. Es importante que compres una tarjeta de transporte en el aeropuerto. Y no dejes la mochila sola en la playa».

Nuria se ríe cuando ve la lista. —Pareces su madre —me dice—. Déjale que descubra la ciudad solo. —Ya, pero quiero que le guste Barcelona tanto como a mí —contesto.

Miro el {pronóstico|die Vorhersage} del tiempo: dicen que el sábado puede llover. Ojalá no llueva, porque quiero que subamos al {búnker|Bunker} del Carmel para ver la puesta de sol. Nuria me da una {palmada|Klaps} en el hombro: —Tranquilo. Si llueve, os llevo a comer el mejor arroz de la ciudad. Espero que tenga hambre.`,
de:`Morgen kommt mein Freund Lukas aus Mannheim und ich will, dass alles perfekt ist. Ich habe ihm eine Liste mit Tipps geschrieben: „Ich empfehle dir, leichte Kleidung mitzubringen, aber auch eine Jacke. Es ist wichtig, dass du am Flughafen eine Fahrkarte kaufst. Und lass den Rucksack am Strand nicht allein.“\n\nNuria lacht, als sie die Liste sieht. „Du wirkst wie seine Mutter“, sagt sie. „Lass ihn die Stadt allein entdecken.“ „Ja, aber ich will, dass ihm Barcelona so gut gefällt wie mir“, antworte ich.\n\nIch schaue mir die Wettervorhersage an: Es heißt, am Samstag könnte es regnen. Hoffentlich regnet es nicht, denn ich will, dass wir auf den Bunker des Carmel steigen, um den Sonnenuntergang zu sehen. Nuria klopft mir auf die Schulter: „Ganz ruhig. Wenn es regnet, nehme ich euch mit zum besten Reis der Stadt. Ich hoffe, er hat Hunger.“`,
qs:[{q:'¿Por qué se ríe Nuria?',opts:['Porque la lista de Ben parece de una madre.','Porque Lukas no viene.','Porque va a llover.'],a:0},{q:'¿Qué quiere hacer Ben si hace buen tiempo?',opts:['ver la puesta de sol desde el Carmel','ir a la playa','comer arroz'],a:0},{q:'«Ojalá no llueva» – ¿por qué subjuntivo?',opts:['Es un deseo.','Es una costumbre.','Es una acción terminada.'],a:0}]},

{id:'s12',after:'u17',title:'La noche que se fue la luz',sub:'Eine dunkle Nacht in Gràcia',text:`Era un martes de noviembre y llovía mucho. Nuria estaba cocinando, Pablo veía una serie y yo estaba escribiendo un trabajo para la universidad. De repente, se fue la luz en todo el barrio.

Al principio nadie dijo nada. Luego Pablo gritó desde el sofá: —¡Justo en el último capítulo! Yo estaba peor: no había guardado mi trabajo desde hacía dos horas. Nuria encontró unas {velas|Kerzen} en la cocina y las encendimos.

Como no podíamos hacer nada, nos sentamos los tres en el suelo del salón y empezamos a contar historias. Pablo nos contó que de pequeño se había perdido en la Feria de Abril de Sevilla. Nuria nos contó cómo había conocido a su mejor amiga. Cuando volvió la luz, a las once, nos dimos cuenta de que habíamos estado hablando tres horas. —Deberíamos apagar la luz más a menudo —dijo Nuria. Y, por suerte, mi ordenador había guardado el trabajo {automáticamente|automatisch}.`,
de:`Es war ein Dienstag im November und es regnete stark. Nuria kochte gerade, Pablo schaute eine Serie und ich schrieb an einer Arbeit für die Uni. Plötzlich fiel im ganzen Viertel der Strom aus.\n\nZuerst sagte niemand etwas. Dann rief Pablo vom Sofa: „Ausgerechnet in der letzten Folge!“ Mir ging es schlechter: Ich hatte meine Arbeit seit zwei Stunden nicht gespeichert. Nuria fand ein paar Kerzen in der Küche und wir zündeten sie an.\n\nWeil wir nichts tun konnten, setzten wir uns zu dritt auf den Boden im Wohnzimmer und fingen an, Geschichten zu erzählen. Pablo erzählte uns, dass er sich als Kind auf der Feria de Abril in Sevilla verlaufen hatte. Nuria erzählte, wie sie ihre beste Freundin kennengelernt hatte. Als um elf der Strom zurückkam, merkten wir, dass wir drei Stunden geredet hatten. „Wir sollten öfter das Licht ausmachen“, sagte Nuria. Und zum Glück hatte mein Computer die Arbeit automatisch gespeichert.`,
qs:[{q:'¿Qué estaba haciendo Ben cuando se fue la luz?',opts:['Estaba escribiendo un trabajo.','Estaba cocinando.','Estaba viendo una serie.'],a:0},{q:'¿Qué le había pasado a Pablo de pequeño?',opts:['Se había perdido en la Feria de Abril.','Había conocido a su mejor amiga.','Se había ido a vivir a Barcelona.'],a:0},{q:'¿Cuánto tiempo estuvieron hablando?',opts:['tres horas','dos horas','toda la noche'],a:0}]}
];
