/* Vocabulario A1 – freiwillige Zusatzlektionen (Extras-Kachel, plus:true + ab:true: zählen nicht für Fortschritt und Tagesplan).
   Schließen die Lücken zur A1-Liste des Plan Curricular (Instituto Cervantes, „Nociones específicas A1“), passend zum Thema der Unidad.
   Abdeckung prüfen: python3 test/a1_check.py --kurs es --liste quellen/pcic_a1_es.json --bis u5 */
(function(){
function P(uid,l){var u=COURSE.units.filter(function(x){return x.id===uid;})[0];if(u)u.lessons.push(Object.assign({ab:true,plus:true,icon:'📗'},l));}
P('u0',{id:'lx',title:'Vocabulario A1: en clase',desc:'Wörter für den Unterricht',steps:[
 {t:'vocab',title:'En clase',items:[['el ejercicio','die Übung'],['la actividad','die Aktivität / Aufgabe'],['la lección','die Lektion'],['la página','die Seite'],['la pregunta','die Frage'],['la respuesta','die Antwort'],['entender','verstehen'],['comprender','verstehen, begreifen'],['repetir','wiederholen'],['los deberes','die Hausaufgaben'],['en parejas','zu zweit'],['en grupos','in Gruppen'],['el diccionario','das Wörterbuch'],['el papel','das Papier'],['el bolígrafo','der Kugelschreiber'],['el lápiz','der Bleistift'],['la goma','der Radiergummi'],['la fotocopia','die Kopie'],['la pizarra','die Tafel']]},
 {t:'match',q:'Ordne zu.',pairs:[['el bolígrafo','der Kugelschreiber'],['la pizarra','die Tafel'],['los deberes','die Hausaufgaben'],['la pregunta','die Frage'],['repetir','wiederholen']]},
 {t:'mc',q:'Du hast etwas nicht verstanden. Was sagst du?',opts:['No entiendo. ¿Puede repetir, por favor?','No tengo deberes.','Es una pizarra.'],a:0},
 {t:'gap',q:'Abrid el libro en la ___ 25. (Seite)',a:['página']},
 {t:'tr',de:'Wir machen die Übung zu zweit.',a:['Hacemos el ejercicio en parejas.']}]});
P('u1',{id:'lx',title:'Vocabulario A1: datos personales',desc:'Nationalität, Familienstand, Dokumente',steps:[
 {t:'vocab',title:'Datos personales',items:[['el apellido','der Nachname'],['la dirección','die Adresse'],['el código postal','die Postleitzahl'],['el correo electrónico','die E-Mail'],['la arroba','das @-Zeichen'],['la edad','das Alter'],['la nacionalidad','die Staatsangehörigkeit'],['el extranjero / la extranjera','der Ausländer / die Ausländerin'],['mexicano / mexicana','mexikanisch, Mexikaner/in'],['japonés / japonesa','japanisch, Japaner/in'],['soltero / soltera','ledig'],['casado / casada','verheiratet'],['divorciado / divorciada','geschieden'],['separado / separada','getrennt lebend'],['viudo / viuda','verwitwet'],['el pasaporte','der Reisepass'],['el carné de identidad','der Personalausweis'],['firmar','unterschreiben']]},
 {t:'match',q:'Ordne zu.',pairs:[['el apellido','der Nachname'],['soltero','ledig'],['firmar','unterschreiben'],['la edad','das Alter'],['el pasaporte','der Reisepass']]},
 {t:'gap',q:'Formular: Nombre: Ana · ___: López García (Nachname)',a:['Apellido|Apellidos']},
 {t:'mc',q:'„jonas@correo.es“ – wie sagt man „@“?',opts:['arroba','punto','guion'],a:0},
 {t:'tr',de:'Ich bin ledig und habe keine Kinder.',a:['Soy soltero y no tengo hijos.','Estoy soltero y no tengo hijos.']}]});
P('u2',{id:'lx',title:'Vocabulario A1: trabajo',desc:'Berufe, Arbeit, Büro',steps:[
 {t:'vocab',title:'Profesiones y trabajo',items:[['la profesión','der Beruf'],['el abogado / la abogada','der Anwalt / die Anwältin'],['el / la taxista','der Taxifahrer / die Taxifahrerin'],['el agricultor / la agricultora','der Landwirt / die Landwirtin'],['el empresario / la empresaria','der Unternehmer / die Unternehmerin'],['el científico / la científica','der Wissenschaftler / die Wissenschaftlerin'],['dedicarse a','beruflich machen, tätig sein in'],['estar en paro','arbeitslos sein'],['la fábrica','die Fabrik'],['la tienda','das Geschäft, der Laden'],['el ordenador','der Computer'],['internet','das Internet'],['vender','verkaufen'],['el vendedor / la vendedora','der Verkäufer / die Verkäuferin']]},
 {t:'match',q:'Ordne zu.',pairs:[['el ordenador','der Computer'],['la fábrica','die Fabrik'],['estar en paro','arbeitslos sein'],['vender','verkaufen'],['el abogado','der Anwalt']]},
 {t:'mc',q:'„¿A qué te dedicas?“ bedeutet …',opts:['Was machst du beruflich?','Wem gibst du das?','Wo wohnst du?'],a:0},
 {t:'tr',de:'Meine Schwester ist Anwältin.',a:['Mi hermana es abogada.']}]});
P('u3',{id:'lx',title:'Vocabulario A1: aspecto y carácter',desc:'Aussehen, Charakter, Gefühle',steps:[
 {t:'vocab',title:'El aspecto físico',items:[['el pelo','die Haare'],['los ojos','die Augen'],['la nariz','die Nase'],['la barba','der Bart'],['el bigote','der Schnurrbart'],['las gafas','die Brille'],['feo / fea','hässlich'],['rizado / rizada','lockig'],['liso / lisa','glatt (Haare)'],['tener el pelo largo / corto','lange / kurze Haare haben'],['llevar gafas','eine Brille tragen']]},
 {t:'vocab',title:'Carácter y sentimientos',items:[['simpático / simpática','sympathisch, nett'],['antipático / antipática','unsympathisch'],['inteligente','intelligent'],['serio / seria','ernst'],['tímido / tímida','schüchtern'],['sociable','gesellig'],['contento / contenta','froh, zufrieden'],['triste','traurig'],['enfadado / enfadada','verärgert'],['nervioso / nerviosa','nervös'],['preocupado / preocupada','besorgt'],['tener miedo','Angst haben']]},
 {t:'vocab',title:'Más personas',items:[['el sobrino / la sobrina','der Neffe / die Nichte'],['el vecino / la vecina','der Nachbar / die Nachbarin']]},
 {t:'info',title:'ser oder estar?',html:`<p><b>ser</b> + Charakter/Aussehen (dauerhaft): <span class="es-t">Laia es simpática y tiene el pelo rizado.</span></p><p><b>estar</b> + Gefühl/Zustand (jetzt): <span class="es-t">Hoy Laia está nerviosa porque tiene un examen.</span></p>`},
 {t:'mc',q:'Mi primo ___ muy tímido, pero hoy ___ contento.',opts:['es · está','está · es','es · es'],a:0},
 {t:'gap',q:'Mi abuela lleva ___ para leer. (Brille)',a:['gafas']},
 {t:'match',q:'Ordne die Gegenteile zu.',pairs:[['simpático','antipático'],['contento','triste'],['rizado','liso'],['largo','corto'],['tímido','sociable']]},
 {t:'tr',de:'Mein Nachbar ist sehr nett.',a:['Mi vecino es muy simpático.']}]});
P('u3',{id:'ly',title:'Vocabulario A1: el cuerpo y la salud',desc:'Körper, Schmerzen, beim Arzt',steps:[
 {t:'vocab',title:'El cuerpo y la salud',items:[['la cabeza','der Kopf'],['el cuello','der Hals / Nacken'],['la espalda','der Rücken'],['el estómago','der Magen'],['los dientes','die Zähne'],['doler','wehtun'],['me duele la cabeza','ich habe Kopfschmerzen'],['el dolor','der Schmerz'],['la fiebre','das Fieber'],['la tos','der Husten'],['estar enfermo / enferma','krank sein'],['la farmacia','die Apotheke'],['el enfermero / la enfermera','der Krankenpfleger / die Krankenschwester'],['el jabón','die Seife'],['lavarse los dientes','sich die Zähne putzen'],['bañarse','baden']]},
 {t:'info',title:'doler wie gustar',html:`<p><b>doler</b> funktioniert wie <b>gustar</b>: <span class="es-t">Me duele la cabeza.</span> (eine Sache) – <span class="es-t">Me duelen los dientes.</span> (mehrere).</p><p>Auch: <span class="es-t">Tengo dolor de espalda.</span> · <span class="es-t">Tengo fiebre y tos.</span></p>`},
 {t:'mc',q:'„Mir tun die Füße weh.“',opts:['Me duelen los pies.','Me duele los pies.','Tengo duelen los pies.'],a:0},
 {t:'gap',q:'Estoy enfermo: tengo ___ (Fieber) y ___ (Husten).',a:['fiebre','tos']},
 {t:'tr',de:'Ich habe Kopfschmerzen.',a:['Me duele la cabeza.','Tengo dolor de cabeza.']}]});
P('u4',{id:'lx',title:'Vocabulario A1: comida y compras',desc:'Lebensmittel, Mengen, Geschirr',steps:[
 {t:'vocab',title:'Comida y compras',items:[['el té','der Tee'],['el sándwich','das Sandwich'],['la hamburguesa','der Hamburger'],['la tortilla','das Omelett (span. Kartoffeltortilla)'],['el ingrediente','die Zutat'],['la galleta','der Keks'],['la mermelada','die Marmelade'],['la taza','die Tasse'],['la servilleta','die Serviette'],['una docena de huevos','ein Dutzend Eier'],['una lata de atún','eine Dose Thunfisch'],['una caja de galletas','eine Schachtel Kekse'],['un bote de tomate','ein Glas Tomaten'],['un paquete de arroz','eine Packung Reis'],['pesar','wiegen'],['tener hambre','Hunger haben'],['tener sed','Durst haben'],['tener sueño','müde sein'],['tener frío / calor','frieren / schwitzen']]},
 {t:'match',q:'Ordne zu.',pairs:[['una lata de','eine Dose'],['un paquete de','eine Packung'],['una docena de','ein Dutzend'],['tener sed','Durst haben'],['la taza','die Tasse']]},
 {t:'mc',q:'„Ich habe Hunger.“',opts:['Tengo hambre.','Estoy hambre.','Soy hambre.'],a:0,why:'Hunger, Durst, Kälte, Angst: <b>tener</b> + Nomen.'},
 {t:'tr',de:'Ich möchte eine Tasse Tee, bitte.',a:['Quiero una taza de té, por favor.','Quería una taza de té, por favor.','Una taza de té, por favor.']}]});
P('u5',{id:'lx',title:'Vocabulario A1: ciudad y servicios',desc:'Verkehr, Bank, Post, Polizei',steps:[
 {t:'vocab',title:'Ciudad y transporte',items:[['la estación de tren','der Bahnhof'],['el autobús','der Bus'],['el avión','das Flugzeug'],['el conductor / la conductora','der Fahrer / die Fahrerin'],['la carretera','die Landstraße'],['el aparcamiento','der Parkplatz'],['el garaje','die Garage'],['el billete de ida y vuelta','das Hin- und Rückticket'],['la iglesia','die Kirche'],['el monumento','das Denkmal'],['el quiosco','der Kiosk']]},
 {t:'vocab',title:'Servicios',items:[['el banco','die Bank'],['el dinero','das Geld'],['el céntimo','der Cent'],['cambiar dinero','Geld wechseln'],['pagar con tarjeta','mit Karte zahlen'],['el sobre','der Briefumschlag'],['el sello','die Briefmarke'],['la postal','die Postkarte'],['la policía','die Polizei'],['el bombero / la bombera','der Feuerwehrmann / die Feuerwehrfrau'],['el teléfono de emergencia','die Notrufnummer']]},
 {t:'mc',q:'Wo kaufst du eine Briefmarke?',opts:['en Correos o en un estanco','en la iglesia','en el aparcamiento'],a:0},
 {t:'gap',q:'Un billete de ida y ___ a Madrid, por favor. (zurück)',a:['vuelta']},
 {t:'tr',de:'Kann ich mit Karte zahlen?',a:['¿Puedo pagar con tarjeta?']}]});
P('u5',{id:'ly',title:'Vocabulario A1: tiempo y naturaleza',desc:'Wetter, Jahreszeiten, Natur',steps:[
 {t:'vocab',title:'El tiempo y las estaciones',items:[['la primavera','der Frühling'],['el verano','der Sommer'],['el otoño','der Herbst'],['el invierno','der Winter'],['hace calor','es ist heiß'],['hace frío','es ist kalt'],['hace sol','die Sonne scheint'],['hace viento','es ist windig'],['hace buen / mal tiempo','das Wetter ist gut / schlecht'],['llover','regnen'],['nevar','schneien']]},
 {t:'vocab',title:'La naturaleza',items:[['el mar','das Meer'],['el río','der Fluss'],['la montaña','die Berge'],['la playa','der Strand'],['el campo','das Land (nicht Stadt)'],['el árbol','der Baum'],['la flor','die Blume'],['el animal','das Tier'],['el norte','der Norden'],['el sur','der Süden'],['el este','der Osten'],['el oeste','der Westen']]},
 {t:'info',title:'Wetter mit hacer',html:`<p>Spanisch sagt das Wetter meist mit <b>hacer</b>: <span class="es-t">Hace frío. Hace sol. Hace buen tiempo.</span> Aber: <span class="es-t">Llueve.</span> (es regnet) · <span class="es-t">Nieva.</span> (es schneit)</p><div class="ojo">In Barcelona ist <span class="es-t">el invierno</span> mild – <span class="es-t">en verano hace mucho calor</span>.</div>`},
 {t:'mc',q:'„Es regnet.“',opts:['Llueve.','Hace lluvia.','Está lloviendo mucho calor.'],a:0},
 {t:'gap',q:'En invierno ___ frío y a veces nieva.',a:['hace']},
 {t:'match',q:'Ordne zu.',pairs:[['el río','der Fluss'],['la montaña','die Berge'],['el árbol','der Baum'],['el sur','der Süden'],['la primavera','der Frühling']]},
 {t:'tr',de:'Im Sommer fahre ich ans Meer.',a:['En verano voy al mar.','En verano voy a la playa.']}]});
})();
