/* Vocabulario A1 – zusätzliche Pflichtlektionen am Ende der Unidad (für Lernende, die schon weiter sind, erscheinen sie unter „Nachholen“).
   Schließen die Lücken zur A1-Liste des Plan Curricular (Instituto Cervantes, „Nociones específicas A1“), passend zum Thema der Unidad.
   Abdeckung prüfen: python3 test/a1_check.py --kurs es --liste quellen/pcic_a1_es.json --bis u5 */
(function(){
function P(uid,l){var u=COURSE.units.filter(function(x){return x.id===uid;})[0];if(u)u.lessons.push(l);}
P('u0',{id:'lx',title:'Vocabulario A1: en clase',desc:'Wörter für den Unterricht',steps:[
 {t:'vocab',title:'En clase',items:[['el ejercicio','die Übung'],['la actividad','die Aktivität / Aufgabe'],['la lección','die Lektion'],['la página','die Seite'],['la pregunta','die Frage'],['la respuesta','die Antwort'],['entender','verstehen'],['comprender','verstehen, begreifen'],['repetir','wiederholen'],['los deberes','die Hausaufgaben'],['en parejas','zu zweit'],['en grupos','in Gruppen'],['el diccionario','das Wörterbuch'],['el papel','das Papier'],['el bolígrafo','der Kugelschreiber'],['el lápiz','der Bleistift'],['la goma','der Radiergummi'],['la fotocopia','die Kopie'],['la pizarra','die Tafel']]},
 {t:'match',q:'Ordne zu.',pairs:[['el bolígrafo','der Kugelschreiber'],['la pizarra','die Tafel'],['los deberes','die Hausaufgaben'],['la pregunta','die Frage'],['repetir','wiederholen']]},
 {t:'mc',q:'Du hast etwas nicht verstanden. Was sagst du?',opts:['No entiendo. ¿Puede repetir, por favor?','No tengo deberes.','Es una pizarra.'],a:0},
 {t:'gap',q:'Abrid el libro en la ___ 25. (Seite)',a:['página']},
 {t:'tr',de:'Wir machen die Übung zu zweit.',a:['Hacemos el ejercicio en parejas.']}]});
P('u1',{id:'lx',title:'Vocabulario A1: datos personales',desc:'Nationalität, Familienstand, Dokumente',steps:[
 {t:'vocab',title:'Datos personales',items:[['el apellido','der Nachname'],['la dirección','die Adresse'],['el código postal','die Postleitzahl'],['el correo electrónico','die E-Mail'],['la arroba','das @-Zeichen'],['la edad','das Alter'],['la nacionalidad','die Staatsangehörigkeit'],['el extranjero / la extranjera','der Ausländer / die Ausländerin'],['mexicano / mexicana','mexikanisch, Mexikaner/in'],['japonés / japonesa','japanisch, Japaner/in'],['soltero / soltera','ledig'],['casado / casada','verheiratet'],['divorciado / divorciada','geschieden'],['separado / separada','getrennt lebend'],['viudo / viuda','verwitwet'],['el pasaporte','der Reisepass'],['el carné de identidad','der Personalausweis'],['firmar','unterschreiben']]},
 {t:'match',q:'Ordne zu.',pairs:[['el apellido','der Nachname'],['soltero','ledig'],['firmar','unterschreiben'],['la edad','das Alter'],['el pasaporte','der Reisepass']]},
 {t:'gap',q:'Formular: Nombre: Ana · ___: López García (Nachname)',a:['Apellido|Apellidos']},
 {t:'mc',q:'„jonas@correo.es“ – wie sagt man „@“?',opts:['arroba','punto','guion'],a:0},
 {t:'tr',de:'Ich bin ledig und habe keine Kinder.',a:['Soy soltero y no tengo hijos.','Estoy soltero y no tengo hijos.']}]});
P('u2',{id:'lx',title:'Vocabulario A1: trabajo',desc:'Berufe, Arbeit, Büro',steps:[
 {t:'vocab',title:'Profesiones y trabajo',items:[['la profesión','der Beruf'],['el abogado / la abogada','der Anwalt / die Anwältin'],['el / la taxista','der Taxifahrer / die Taxifahrerin'],['el agricultor / la agricultora','der Landwirt / die Landwirtin'],['el empresario / la empresaria','der Unternehmer / die Unternehmerin'],['el científico / la científica','der Wissenschaftler / die Wissenschaftlerin'],['dedicarse a','beruflich machen, tätig sein in'],['estar en paro','arbeitslos sein'],['la fábrica','die Fabrik'],['la tienda','das Geschäft, der Laden'],['el ordenador','der Computer'],['internet','das Internet'],['vender','verkaufen'],['el vendedor / la vendedora','der Verkäufer / die Verkäuferin']]},
 {t:'match',q:'Ordne zu.',pairs:[['el ordenador','der Computer'],['la fábrica','die Fabrik'],['estar en paro','arbeitslos sein'],['vender','verkaufen'],['el abogado','der Anwalt']]},
 {t:'mc',q:'„¿A qué te dedicas?“ bedeutet …',opts:['Was machst du beruflich?','Wem gibst du das?','Wo wohnst du?'],a:0},
 {t:'tr',de:'Meine Schwester ist Anwältin.',a:['Mi hermana es abogada.']}]});
P('u3',{id:'lx',title:'Vocabulario A1: aspecto y carácter',desc:'Aussehen, Charakter, Gefühle',steps:[
 {t:'vocab',title:'El aspecto físico',items:[['el pelo','die Haare'],['los ojos','die Augen'],['la nariz','die Nase'],['la barba','der Bart'],['el bigote','der Schnurrbart'],['las gafas','die Brille'],['feo / fea','hässlich'],['rizado / rizada','lockig'],['liso / lisa','glatt (Haare)'],['tener el pelo largo / corto','lange / kurze Haare haben'],['llevar gafas','eine Brille tragen']]},
 {t:'vocab',title:'Carácter y sentimientos',items:[['simpático / simpática','sympathisch, nett'],['antipático / antipática','unsympathisch'],['inteligente','intelligent'],['serio / seria','ernst'],['tímido / tímida','schüchtern'],['sociable','gesellig'],['contento / contenta','froh, zufrieden'],['triste','traurig'],['enfadado / enfadada','verärgert'],['nervioso / nerviosa','nervös'],['preocupado / preocupada','besorgt'],['tener miedo','Angst haben']]},
 {t:'vocab',title:'Más personas',items:[['el sobrino / la sobrina','der Neffe / die Nichte'],['el vecino / la vecina','der Nachbar / die Nachbarin']]},
 {t:'info',title:'ser oder estar?',html:`<p><b>ser</b> + Charakter/Aussehen (dauerhaft): <span class="es-t">Laia es simpática y tiene el pelo rizado.</span></p><p><b>estar</b> + Gefühl/Zustand (jetzt): <span class="es-t">Hoy Laia está nerviosa porque tiene un examen.</span></p>`},
 {t:'mc',q:'Mi primo ___ muy tímido, pero hoy ___ contento.',opts:['es · está','está · es','es · es'],a:0},
 {t:'gap',q:'Mi abuela lleva ___ para leer. (Brille)',a:['gafas']},
 {t:'match',q:'Ordne die Gegenteile zu.',pairs:[['simpático','antipático'],['contento','triste'],['rizado','liso'],['largo','corto'],['tímido','sociable']]},
 {t:'tr',de:'Mein Nachbar ist sehr nett.',a:['Mi vecino es muy simpático.']}]});
P('u3',{id:'ly',title:'Vocabulario A1: el cuerpo y la salud',desc:'Körper, Schmerzen, beim Arzt',steps:[
 {t:'vocab',title:'El cuerpo y la salud',items:[['la cabeza','der Kopf'],['el cuello','der Hals / Nacken'],['la espalda','der Rücken'],['el estómago','der Magen'],['los dientes','die Zähne'],['doler','wehtun'],['me duele la cabeza','ich habe Kopfschmerzen'],['el dolor','der Schmerz'],['la fiebre','das Fieber'],['la tos','der Husten'],['estar enfermo / enferma','krank sein'],['la farmacia','die Apotheke'],['el enfermero / la enfermera','der Krankenpfleger / die Krankenschwester'],['el jabón','die Seife'],['lavarse los dientes','sich die Zähne putzen'],['bañarse','baden']]},
 {t:'info',title:'doler wie gustar',html:`<p><b>doler</b> funktioniert wie <b>gustar</b>: <span class="es-t">Me duele la cabeza.</span> (eine Sache) – <span class="es-t">Me duelen los dientes.</span> (mehrere).</p><p>Auch: <span class="es-t">Tengo dolor de espalda.</span> · <span class="es-t">Tengo fiebre y tos.</span></p>`},
 {t:'mc',q:'„Mir tun die Füße weh.“',opts:['Me duelen los pies.','Me duele los pies.','Tengo duelen los pies.'],a:0},
 {t:'gap',q:'Estoy enfermo: tengo ___ (Fieber) y ___ (Husten).',a:['fiebre','tos']},
 {t:'tr',de:'Ich habe Kopfschmerzen.',a:['Me duele la cabeza.','Tengo dolor de cabeza.']}]});
P('u4',{id:'lx',title:'Vocabulario A1: comida y compras',desc:'Lebensmittel, Mengen, Geschirr',steps:[
 {t:'vocab',title:'Comida y compras',items:[['el té','der Tee'],['el sándwich','das Sandwich'],['la hamburguesa','der Hamburger'],['la tortilla','das Omelett (span. Kartoffeltortilla)'],['el ingrediente','die Zutat'],['la galleta','der Keks'],['la mermelada','die Marmelade'],['la taza','die Tasse'],['la servilleta','die Serviette'],['una docena de huevos','ein Dutzend Eier'],['una lata de atún','eine Dose Thunfisch'],['una caja de galletas','eine Schachtel Kekse'],['un bote de tomate','ein Glas Tomaten'],['un paquete de arroz','eine Packung Reis'],['pesar','wiegen'],['tener hambre','Hunger haben'],['tener sed','Durst haben'],['tener sueño','müde sein'],['tener frío / calor','frieren / schwitzen']]},
 {t:'match',q:'Ordne zu.',pairs:[['una lata de','eine Dose'],['un paquete de','eine Packung'],['una docena de','ein Dutzend'],['tener sed','Durst haben'],['la taza','die Tasse']]},
 {t:'mc',q:'„Ich habe Hunger.“',opts:['Tengo hambre.','Estoy hambre.','Soy hambre.'],a:0,why:'Hunger, Durst, Kälte, Angst: <b>tener</b> + Nomen.'},
 {t:'tr',de:'Ich möchte eine Tasse Tee, bitte.',a:['Quiero una taza de té, por favor.','Quería una taza de té, por favor.','Una taza de té, por favor.']}]});
P('u5',{id:'lx',title:'Vocabulario A1: ciudad y servicios',desc:'Verkehr, Bank, Post, Polizei',steps:[
 {t:'vocab',title:'Ciudad y transporte',items:[['la estación de tren','der Bahnhof'],['el autobús','der Bus'],['el avión','das Flugzeug'],['el conductor / la conductora','der Fahrer / die Fahrerin'],['la carretera','die Landstraße'],['el aparcamiento','der Parkplatz'],['el garaje','die Garage'],['el billete de ida y vuelta','das Hin- und Rückticket'],['la iglesia','die Kirche'],['el monumento','das Denkmal'],['el quiosco','der Kiosk']]},
 {t:'vocab',title:'Servicios',items:[['el banco','die Bank'],['el dinero','das Geld'],['el céntimo','der Cent'],['cambiar dinero','Geld wechseln'],['pagar con tarjeta','mit Karte zahlen'],['el sobre','der Briefumschlag'],['el sello','die Briefmarke'],['la postal','die Postkarte'],['la policía','die Polizei'],['el bombero / la bombera','der Feuerwehrmann / die Feuerwehrfrau'],['el teléfono de emergencia','die Notrufnummer']]},
 {t:'mc',q:'Wo kaufst du eine Briefmarke?',opts:['en Correos o en un estanco','en la iglesia','en el aparcamiento'],a:0},
 {t:'gap',q:'Un billete de ida y ___ a Madrid, por favor. (zurück)',a:['vuelta']},
 {t:'tr',de:'Kann ich mit Karte zahlen?',a:['¿Puedo pagar con tarjeta?']}]});
P('u5',{id:'ly',title:'Vocabulario A1: tiempo y naturaleza',desc:'Wetter, Jahreszeiten, Natur',steps:[
 {t:'vocab',title:'El tiempo y las estaciones',items:[['la primavera','der Frühling'],['el verano','der Sommer'],['el otoño','der Herbst'],['el invierno','der Winter'],['hace calor','es ist heiß'],['hace frío','es ist kalt'],['hace sol','die Sonne scheint'],['hace viento','es ist windig'],['hace buen / mal tiempo','das Wetter ist gut / schlecht'],['llover','regnen'],['nevar','schneien']]},
 {t:'vocab',title:'La naturaleza',items:[['el mar','das Meer'],['el río','der Fluss'],['la montaña','die Berge'],['la playa','der Strand'],['el campo','das Land (nicht Stadt)'],['el árbol','der Baum'],['la flor','die Blume'],['el animal','das Tier'],['el norte','der Norden'],['el sur','der Süden'],['el este','der Osten'],['el oeste','der Westen']]},
 {t:'info',title:'Wetter mit hacer',html:`<p>Spanisch sagt das Wetter meist mit <b>hacer</b>: <span class="es-t">Hace frío. Hace sol. Hace buen tiempo.</span> Aber: <span class="es-t">Llueve.</span> (es regnet) · <span class="es-t">Nieva.</span> (es schneit)</p><div class="ojo">In Barcelona ist <span class="es-t">el invierno</span> mild – <span class="es-t">en verano hace mucho calor</span>.</div>`},
 {t:'mc',q:'„Es regnet.“',opts:['Llueve.','Hace lluvia.','Está lloviendo mucho calor.'],a:0},
 {t:'gap',q:'En invierno ___ frío y a veces nieva.',a:['hace']},
 {t:'match',q:'Ordne zu.',pairs:[['el río','der Fluss'],['la montaña','die Berge'],['el árbol','der Baum'],['el sur','der Süden'],['la primavera','der Frühling']]},
 {t:'tr',de:'Im Sommer fahre ich ans Meer.',a:['En verano voy al mar.','En verano voy a la playa.']}]});
P('u5',{id:'lz',icon:'🎯',title:'Prueba DELE A1',desc:'Übungstest im DELE-Format',steps:[
 {t:'info',title:'Das DELE A1',html:`<p>Das <b>DELE A1</b> ist die offizielle Spanischprüfung des Instituto Cervantes. Sie hat vier Teile:</p>
 <table><tr><th>Teil</th><th>Dauer</th><th>Aufgaben</th></tr>
 <tr><td>Comprensión de lectura</td><td>45 Min.</td><td>E-Mail/Postkarte, kurze Notizen und Schilder, Anzeigen, Info-Text</td></tr>
 <tr><td>Comprensión auditiva</td><td>25 Min.</td><td>kurze Dialoge, Durchsagen, Aussagen einer Person, ein Gespräch – alles zweimal</td></tr>
 <tr><td>Expresión e interacción escritas</td><td>25 Min.</td><td>ein Formular (15–25 Wörter) und eine Nachricht (30–40 Wörter)</td></tr>
 <tr><td>Expresión e interacción orales</td><td>10 Min. + 10 Min. Vorbereitung</td><td>dich vorstellen, über ein Thema sprechen, Gespräch mit zwei eigenen Fragen</td></tr></table>
 <p>Bestanden („Apto“) ist man mit je <b>30 von 50 Punkten</b> in Lesen + Schreiben und in Hören + Sprechen. Dieser Übungstest hat dasselbe Format, aber eigene Texte.</p>`},
 {t:'read',kind:'Lectura · Tarea 1',title:'Un correo de Carmen',text:`Hola, Jonas:
¿Qué tal en Barcelona? Yo estoy muy contenta en mi nuevo trabajo en Valencia. Trabajo en una escuela de idiomas, de lunes a viernes, de nueve a tres. Por las tardes voy a la playa o leo en un café. Mi piso es pequeño, pero tiene una terraza con mucho sol.
El sábado 14 es mi cumpleaños y hago una fiesta en casa. ¿Puedes venir? Hay tren desde Barcelona: tarda tres horas. Puedes dormir en el sofá.
Un beso,
Carmen`,de:`Hallo Jonas,
wie läuft es in Barcelona? Ich bin sehr froh mit meinem neuen Job in Valencia. Ich arbeite in einer Sprachschule, montags bis freitags von neun bis drei. Nachmittags gehe ich an den Strand oder lese in einem Café. Meine Wohnung ist klein, aber sie hat eine Terrasse mit viel Sonne.
Am Samstag, dem 14., habe ich Geburtstag und mache eine Party zu Hause. Kannst du kommen? Es gibt einen Zug von Barcelona: Er braucht drei Stunden. Du kannst auf dem Sofa schlafen.
Liebe Grüße,
Carmen`},
 {t:'mc',kind:'Lectura · Tarea 1',q:'¿Dónde trabaja Carmen?',opts:['en una escuela de idiomas','en un café','en una playa'],a:0},
 {t:'mc',kind:'Lectura · Tarea 1',q:'¿Cómo es el piso de Carmen?',opts:['pequeño, con terraza','grande, con jardín','pequeño y sin sol'],a:0},
 {t:'mc',kind:'Lectura · Tarea 1',q:'¿Qué hace Carmen el sábado 14?',opts:['una fiesta en casa','un viaje a Barcelona','un examen'],a:0},
 {t:'mc',kind:'Lectura · Tarea 2',q:'Nota en la puerta: «Volvemos a las 17:00. Paquetes en la tienda de al lado.» – ¿Qué significa?',opts:['La tienda está cerrada ahora.','La tienda abre a las siete.','Los paquetes están en la calle.'],a:0},
 {t:'mc',kind:'Lectura · Tarea 2',q:'Cartel en el metro: «Prohibido comer y beber en los vagones.» – ¿Qué significa?',opts:['En el metro no se puede comer.','En el metro hay un bar.','Se puede comer en el andén y en el vagón.'],a:0},
 {t:'mc',kind:'Lectura · Tarea 2',q:'Agenda de Jonas: «Jueves: dentista 10:30 – ¡llevar la tarjeta sanitaria!» – ¿Qué tiene que hacer Jonas el jueves?',opts:['ir al médico de los dientes','ir a clase a las diez','comprar una tarjeta'],a:0},
 {t:'mc',kind:'Lectura · Tarea 3',q:'Laura: «Quiero aprender a cocinar platos españoles, pero solo tengo tiempo los fines de semana.» – ¿Qué anuncio es para ella? a) Curso de cocina mediterránea: sábados de 10 a 13 h · b) Clases de paella: martes y jueves por la tarde · c) Restaurante El Puerto: menú del día 12 €',opts:['a','b','c'],a:0},
 {t:'mc',kind:'Lectura · Tarea 3',q:'Marc: «Busco una habitación barata cerca de la universidad.» – ¿Qué anuncio es para él? a) Se alquila piso de 4 dormitorios en el centro, 1.400 € · b) Habitación en piso compartido, 5 minutos de la universidad, 350 € · c) Se vende bicicleta casi nueva',opts:['b','a','c'],a:0},
 {t:'read',kind:'Lectura · Tarea 4',title:'Biblioteca del barrio',text:`Biblioteca Municipal Gràcia. Horario: de lunes a viernes de 9:00 a 21:00; sábados de 10:00 a 14:00; domingos cerrado. Para sacar libros necesitas el carné de la biblioteca: es gratis, solo tienes que traer tu pasaporte o tu carné de identidad. Puedes llevarte cinco libros durante tres semanas. Hay wifi gratis y ordenadores para todos. Los martes a las 18:00 hay intercambio de idiomas en la sala 2.`,de:`Stadtbibliothek Gràcia. Öffnungszeiten: montags bis freitags 9–21 Uhr; samstags 10–14 Uhr; sonntags geschlossen. Um Bücher auszuleihen, brauchst du den Bibliotheksausweis: Er ist kostenlos, du musst nur deinen Reisepass oder Personalausweis mitbringen. Du kannst fünf Bücher für drei Wochen mitnehmen. Es gibt kostenloses WLAN und Computer für alle. Dienstags um 18 Uhr gibt es einen Sprachaustausch in Raum 2.`},
 {t:'mc',kind:'Lectura · Tarea 4',q:'¿Cuándo está cerrada la biblioteca?',opts:['el domingo','el sábado por la mañana','el martes por la tarde'],a:0},
 {t:'mc',kind:'Lectura · Tarea 4',q:'Para hacer el carné de la biblioteca hay que …',opts:['traer un documento de identidad','pagar cinco euros','tener un ordenador'],a:0},
 {t:'mc',kind:'Lectura · Tarea 4',q:'¿Cuántos libros puedes llevarte?',opts:['cinco','tres','dos'],a:0},
 {t:'read',hideText:true,kind:'Comprensión auditiva · Tarea 1',title:'Diálogo 1',intro:'Escucha el diálogo y responde.',text:`– Perdona, ¿a qué hora sale el autobús para el aeropuerto? – Sale cada veinte minutos. El próximo, a las diez y cuarto. – ¿Y cuánto cuesta el billete? – Cinco euros noventa.`,de:`– Entschuldigung, wann fährt der Bus zum Flughafen? – Er fährt alle zwanzig Minuten. Der nächste um Viertel nach zehn. – Und was kostet die Fahrkarte? – Fünf Euro neunzig.`},
 {t:'mc',kind:'Comprensión auditiva · Tarea 1',q:'¿A qué hora sale el próximo autobús?',opts:['a las 10:15','a las 10:20','a las 10:45'],a:0},
 {t:'read',hideText:true,kind:'Comprensión auditiva · Tarea 2',title:'Aviso',intro:'Escucha el aviso.',text:`Señores clientes: les informamos de que hoy, por ser festivo, el supermercado cierra a las tres de la tarde. Mañana abrimos a las nueve, como siempre. Gracias.`,de:`Liebe Kundinnen und Kunden: Wir informieren Sie, dass der Supermarkt heute wegen des Feiertags um drei Uhr nachmittags schließt. Morgen öffnen wir wie immer um neun. Danke.`},
 {t:'mc',kind:'Comprensión auditiva · Tarea 2',q:'¿Qué pasa hoy en el supermercado?',opts:['Cierra antes porque es festivo.','Abre a las tres.','Está cerrado todo el día.'],a:0},
 {t:'read',hideText:true,kind:'Comprensión auditiva · Tarea 3',title:'Ana habla de su familia',intro:'Escucha a Ana.',text:`Me llamo Ana y vivo en Sevilla con mi marido y mis dos hijos. Mi hijo mayor tiene doce años y le encanta el fútbol. La pequeña tiene siete años y toca el piano. Los domingos comemos siempre en casa de mis padres.`,de:`Ich heiße Ana und wohne mit meinem Mann und meinen zwei Kindern in Sevilla. Mein älterer Sohn ist zwölf und liebt Fußball. Die Kleine ist sieben und spielt Klavier. Sonntags essen wir immer bei meinen Eltern.`},
 {t:'mc',kind:'Comprensión auditiva · Tarea 3',q:'La hija de Ana …',opts:['toca el piano.','juega al fútbol.','tiene doce años.'],a:0},
 {t:'mc',kind:'Comprensión auditiva · Tarea 3',q:'Los domingos Ana …',opts:['come con sus padres.','va al estadio.','trabaja en Sevilla.'],a:0},
 {t:'read',hideText:true,kind:'Comprensión auditiva · Tarea 4',title:'Un plan para el sábado',intro:'Escucha la conversación entre Pablo y Lucía.',text:`– Lucía, ¿qué haces el sábado? – Por la mañana voy al gimnasio, pero por la tarde estoy libre. – ¿Vamos al cine? Hay una película argentina muy buena. – Vale. ¿A qué hora? – La sesión es a las siete y media. Quedamos a las siete en la puerta del cine. – Perfecto. Y después podemos cenar en el restaurante mexicano de la plaza. – ¡Buena idea!`,de:`– Lucía, was machst du am Samstag? – Vormittags gehe ich ins Fitnessstudio, aber nachmittags habe ich frei. – Gehen wir ins Kino? Es gibt einen sehr guten argentinischen Film. – Okay. Um wie viel Uhr? – Die Vorstellung ist um halb acht. Wir treffen uns um sieben vor dem Kino. – Perfekt. Und danach können wir im mexikanischen Restaurant am Platz essen. – Gute Idee!`},
 {t:'mc',kind:'Comprensión auditiva · Tarea 4',q:'El sábado por la mañana Lucía …',opts:['va al gimnasio.','va al cine.','cena con Pablo.'],a:0},
 {t:'mc',kind:'Comprensión auditiva · Tarea 4',q:'Pablo y Lucía quedan a las …',opts:['siete.','siete y media.','ocho.'],a:0},
 {t:'free',kind:'Expresión escrita · Tarea 1',task:'Formulario de inscripción en un gimnasio – füll die Felder mit deinen Daten aus (15–25 Wörter): Nombre y apellido · País de origen · Dirección · Teléfono · ¿Qué deporte practicas y cuándo?',hint:'Nombre y apellido: … · País de origen: … · Dirección: Calle …, n.º … · Teléfono: … · Deporte: Juego al … / Nado los …',focus:'Datos personales, Zahlen, Adresse, Sport mit jugar/hacer',model:'Nombre y apellido: Jonas Gross · País de origen: Alemania · Dirección: calle Verdi 12, Barcelona · Teléfono: 612 345 678 · Deporte: Juego al fútbol los martes y nado los sábados.'},
 {t:'free',kind:'Expresión escrita · Tarea 2',task:'Escribe un correo a Carmen (30–40 palabras): dale las gracias por la invitación a la fiesta, di si vas a ir y a qué hora llegas, y pregúntale qué puedes llevar.',hint:'Hola, Carmen: Gracias por … Sí, voy a ir … / Lo siento, no puedo … Llego a las … ¿Qué llevo? Un beso, …',focus:'Correo informal: saludo, 3 puntos, despedida; ir a + Infinitiv, llegar, llevar',model:'Hola, Carmen:\nMuchas gracias por la invitación. ¡Claro que voy a tu fiesta! Llego en tren el sábado a las seis de la tarde. ¿Qué llevo? ¿Una tarta o unas bebidas?\nUn beso,\nJonas'},
 {t:'speak',kind:'Expresión oral · Tarea 1',es:'Hola, me llamo Jonas. Tengo veintiséis años y soy alemán, de Mannheim. Ahora vivo en Barcelona. Hablo alemán, inglés y un poco de español. Estudio un máster en la universidad.',de:'Presentación personal (1–2 minutos): nombre, edad, nacionalidad, ciudad, idiomas, profesión/estudios.',tip:'In der Prüfung sprichst du ein bis zwei Minuten über dich: Name, Alter, Herkunft, Wohnort, Sprachen, Beruf oder Studium.'},
 {t:'free',kind:'Expresión oral · Tarea 2',task:'Exposición de un tema (2–3 minutos): Mi casa. Bereite in Stichpunkten oder ganzen Sätzen vor: Wo wohnst du? Wie ist deine Wohnung? Mit wem wohnst du? Was gefällt dir (nicht)?',hint:'Vivo en un piso en … Tiene … habitaciones. Vivo con … Me gusta … porque … No me gusta …',focus:'hay, ser/estar, gustar, Möbel und Zimmer, Adjektive',model:'Vivo en un piso compartido en Gràcia, en Barcelona. Tiene tres habitaciones, una cocina pequeña y un baño. Vivo con dos compañeros, Nuria y Marc. Me gusta mucho mi habitación porque es grande y tiene mucha luz. No me gusta el ruido de la calle por la noche.'},
 {t:'tr',kind:'Expresión oral · Tarea 3',de:'Stell dem Prüfer eine Frage zu seiner Wohnung: Wo wohnen Sie?',a:['¿Dónde vive usted?','¿Dónde vive?','¿Dónde vives?']},
 {t:'tr',kind:'Expresión oral · Tarea 3',de:'Zweite Frage: Mit wem wohnen Sie?',a:['¿Con quién vive usted?','¿Con quién vive?','¿Con quién vives?']},
 {t:'info',title:'¡Enhorabuena! 🎉',html:`<p>Wenn du hier etwa 60 % geschafft hast, bist du auf einem guten Weg zum <b>DELE A1</b>. Termine und Anmeldung: <span class="es-t">examenes.cervantes.es</span> oder beim Instituto Cervantes in deiner Nähe.</p>`}]});
})();
