/* Vocabulario A2 – zusätzliche Pflichtlektionen am Ende der Unidad (für Lernende, die schon weiter sind, erscheinen sie unter „Nachholen“).
   Schließen die Lücken zur A2-Liste des Plan Curricular (Instituto Cervantes, „Nociones específicas A2“), passend zum Thema der Unidad.
   Abdeckung prüfen: python3 test/a1_check.py --kurs es --liste quellen/pcic_a2_es.json --bis u15 */
(function(){
function P(uid,l){var u=COURSE.units.filter(function(x){return x.id===uid;})[0];if(u)u.lessons.push(l);}
P('u6',{id:'lx',title:'Vocabulario A2: viajes y ocio',desc:'Reisen, Unterkunft, Freizeit',steps:[
 {t:'vocab',title:'De viaje',items:[['hacer las maletas','die Koffer packen'],['la mochila','der Rucksack'],['el / la guía turístico/a','der Reiseführer / die Reiseführerin'],['la pensión completa','die Vollpension'],['la media pensión','die Halbpension'],['el piloto / la piloto','der Pilot / die Pilotin'],['el azafato / la azafata','der Flugbegleiter / die Flugbegleiterin'],['la moto','das Motorrad'],['el / la ciclista','der Radfahrer / die Radfahrerin'],['la isla','die Insel'],['el bosque','der Wald'],['el desierto','die Wüste'],['el castillo','die Burg, das Schloss'],['el palacio','der Palast'],['la estatua','die Statue']]},
 {t:'vocab',title:'Tiempo libre',items:[['la afición','das Hobby, die Leidenschaft'],['el parque de atracciones','der Freizeitpark'],['el zoo','der Zoo'],['la ópera','die Oper'],['el musical','das Musical'],['jugar a las cartas','Karten spielen'],['el ajedrez','das Schach']]},
 {t:'match',q:'Ordne zu.',pairs:[['la mochila','der Rucksack'],['la isla','die Insel'],['el bosque','der Wald'],['el ajedrez','das Schach'],['la media pensión','die Halbpension']]},
 {t:'gap',q:'Mañana salimos de viaje y esta noche tengo que hacer las ___.',a:['maletas']},
 {t:'tr',de:'Wir möchten ein Zimmer mit Halbpension.',a:['Queremos una habitación con media pensión.','Quisiéramos una habitación con media pensión.']}]});
P('u7',{id:'lx',title:'Vocabulario A2: el mundo laboral',desc:'Berufe, Arbeitsplatz, Arbeitsleben',steps:[
 {t:'vocab',title:'Profesiones y lugares de trabajo',items:[['el / la dependiente/a','der Verkäufer / die Verkäuferin (im Laden)'],['el funcionario / la funcionaria','der Beamte / die Beamtin'],['el / la periodista','der Journalist / die Journalistin'],['el presentador / la presentadora','der Moderator / die Moderatorin'],['el mecánico / la mecánica','der Mechaniker / die Mechanikerin'],['hacer de canguro','babysitten'],['la peluquería','der Friseursalon'],['la librería','die Buchhandlung'],['la multinacional','der internationale Konzern'],['la impresora','der Drucker'],['la fotocopiadora','der Kopierer'],['la corbata','die Krawatte'],['el uniforme','die Uniform'],['ganar dinero','Geld verdienen'],['estar jubilado / jubilada','in Rente sein']]},
 {t:'match',q:'Ordne zu.',pairs:[['la librería','die Buchhandlung'],['la peluquería','der Friseursalon'],['estar jubilado','in Rente sein'],['la impresora','der Drucker'],['hacer de canguro','babysitten']]},
 {t:'mc',q:'„librería“ bedeutet …',opts:['Buchhandlung','Bibliothek','Bücherregal'],a:0,why:'Falscher Freund! Bibliothek = <i>biblioteca</i>.'},
 {t:'tr',de:'Mein Opa ist in Rente.',a:['Mi abuelo está jubilado.']}]});
P('u8',{id:'lx',title:'Vocabulario A2: ropa y tiempo',desc:'Kleidung, Accessoires, Himmel & Wetter',steps:[
 {t:'vocab',title:'Ropa y complementos',items:[['la gorra','die Kappe'],['el sombrero','der Hut'],['el gorro','die Mütze'],['el pañuelo','das Halstuch, Taschentuch'],['la bufanda','der Schal'],['los guantes','die Handschuhe'],['los calcetines','die Socken'],['el pijama','der Schlafanzug'],['la cazadora','die Jacke (kurz)'],['el bañador','die Badehose, der Badeanzug'],['el biquini','der Bikini'],['el probador','die Umkleidekabine'],['quitarse','ausziehen (Kleidung)']]},
 {t:'vocab',title:'El cielo y el tiempo',items:[['el cielo','der Himmel'],['la luna','der Mond'],['la estrella','der Stern']]},
 {t:'match',q:'Ordne zu.',pairs:[['la bufanda','der Schal'],['los guantes','die Handschuhe'],['el cielo','der Himmel'],['la luna','der Mond'],['el probador','die Umkleidekabine']]},
 {t:'gap',q:'Esta camiseta es pequeña. ¿La puedo ___? (umtauschen)',a:['devolver|cambiar']},
 {t:'tr',de:'Im Winter trage ich eine Mütze und einen Schal.',a:['En invierno llevo un gorro y una bufanda.']}]});
P('u9',{id:'lx',title:'Vocabulario A2: casa, barrio y animales',desc:'Wohnung, Geräte, Viertel, Haustiere',steps:[
 {t:'vocab',title:'La casa',items:[['el chalé','das Einfamilienhaus'],['el pasillo','der Flur'],['la habitación de invitados','das Gästezimmer'],['el propietario / la propietaria','der Eigentümer / die Eigentümerin'],['la lavadora','die Waschmaschine'],['el lavaplatos','die Spülmaschine'],['el microondas','die Mikrowelle'],['la esquina','die Ecke'],['la calle peatonal','die Fußgängerzone'],['el / la habitante','der Einwohner / die Einwohnerin']]},
 {t:'vocab',title:'Animales',items:[['el gato','die Katze'],['el pájaro','der Vogel'],['el pez','der Fisch (lebend)'],['el caballo','das Pferd'],['la mosca','die Fliege'],['el mosquito','die Mücke'],['la araña','die Spinne']]},
 {t:'info',title:'pez oder pescado?',html:`<p><span class="es-t">el pez</span> = der Fisch, der lebt (im Wasser, im Aquarium). <span class="es-t">el pescado</span> = der Fisch, den man isst.</p>`},
 {t:'mc',q:'Im Restaurant: „Hoy tenemos ___ fresco.“',opts:['pescado','pez','pájaro'],a:0},
 {t:'match',q:'Ordne zu.',pairs:[['la lavadora','die Waschmaschine'],['el pasillo','der Flur'],['la esquina','die Ecke'],['el caballo','das Pferd'],['el pájaro','der Vogel']]},
 {t:'tr',de:'Die Wohnung hat eine Spülmaschine und eine Mikrowelle.',a:['El piso tiene lavaplatos y microondas.','El piso tiene un lavaplatos y un microondas.','El apartamento tiene lavaplatos y microondas.']}]});
P('u10',{id:'lx',title:'Vocabulario A2: estudios y vida',desc:'Schule, Kurse, Lebensabschnitte',steps:[
 {t:'vocab',title:'Estudiar',items:[['la academia','die private Schule, das Institut'],['el aula','der Unterrichtsraum'],['el alumno / la alumna','der Schüler / die Schülerin'],['el diploma','das Diplom, Zeugnis'],['aprobar','bestehen'],['suspender','durchfallen'],['contestar','antworten'],['completar','ergänzen'],['repasar','wiederholen (Lernstoff)'],['cometer un error','einen Fehler machen'],['la redacción','der Aufsatz'],['el cuaderno','das Heft'],['la hoja','das Blatt'],['la regla','das Lineal; die Regel'],['dibujar','zeichnen'],['adivinar','raten']]},
 {t:'vocab',title:'Etapas de la vida',items:[['el bebé','das Baby'],['el / la adolescente','der / die Jugendliche'],['crecer','wachsen, aufwachsen'],['casarse','heiraten'],['morir','sterben']]},
 {t:'mc',q:'„Suspendí el examen.“ bedeutet …',opts:['Ich bin durch die Prüfung gefallen.','Ich habe die Prüfung verschoben.','Ich habe die Prüfung bestanden.'],a:0},
 {t:'gap',q:'Estudié mucho y ___ el examen con un 9. (bestehen, Indefinido)',a:['aprobé']},
 {t:'match',q:'Ordne zu.',pairs:[['el cuaderno','das Heft'],['crecer','aufwachsen'],['casarse','heiraten'],['la redacción','der Aufsatz'],['adivinar','raten']]},
 {t:'tr',de:'Ich bin in Mannheim aufgewachsen.',a:['Crecí en Mannheim.','Me crie en Mannheim.']}]});
P('u11',{id:'lx',title:'Vocabulario A2: salud e higiene',desc:'Körperpflege, Notfall, Gesundheit',steps:[
 {t:'vocab',title:'Higiene',items:[['el dedo','der Finger'],['afeitarse','sich rasieren'],['peinarse','sich kämmen'],['cepillarse los dientes','sich die Zähne putzen'],['el cepillo de dientes','die Zahnbürste'],['la pasta de dientes','die Zahnpasta'],['el champú','das Shampoo'],['el gel','das Duschgel'],['la colonia','das Parfüm, Eau de Cologne'],['el desodorante','das Deo'],['la bañera','die Badewanne'],['la toalla','das Handtuch']]},
 {t:'vocab',title:'Salud',items:[['la enfermedad','die Krankheit'],['el medicamento','das Medikament'],['las urgencias','die Notaufnahme'],['la ambulancia','der Krankenwagen'],['llevar una vida sana','gesund leben']]},
 {t:'match',q:'Ordne zu.',pairs:[['la toalla','das Handtuch'],['afeitarse','sich rasieren'],['la ambulancia','der Krankenwagen'],['las urgencias','die Notaufnahme'],['el dedo','der Finger']]},
 {t:'gap',q:'Todas las mañanas me ducho, me ___ (kämmen) y me cepillo los dientes.',a:['peino']},
 {t:'tr',de:'Ich versuche, gesund zu leben.',a:['Intento llevar una vida sana.']}]});
P('u12',{id:'lx',title:'Vocabulario A2: dinero y emergencias',desc:'Geld, Bezahlen, Hilfe',steps:[
 {t:'vocab',title:'Dinero',items:[['la moneda','die Münze; die Währung'],['el cajero automático','der Geldautomat'],['pagar en efectivo','bar zahlen'],['la propina','das Trinkgeld'],['el cheque','der Scheck'],['pobre','arm']]},
 {t:'vocab',title:'Emergencias',items:[['la comisaría','die Polizeiwache'],['¡Socorro!','Hilfe!'],['el paraguas','der Regenschirm'],['la cabina (de teléfono)','die Telefonzelle']]},
 {t:'mc',q:'Man hat dir in der Metro das Portemonnaie gestohlen. Wohin gehst du?',opts:['a la comisaría','al cajero automático','a la peluquería'],a:0},
 {t:'gap',q:'En España no siempre se deja ___, pero en los restaurantes es normal. (Trinkgeld)',a:['propina']},
 {t:'tr',de:'Kann ich bar zahlen?',a:['¿Puedo pagar en efectivo?']}]});
P('u13',{id:'lx',title:'Vocabulario A2: en el mercado',desc:'Obst, Gemüse, Fisch, Fleisch, Desserts',steps:[
 {t:'vocab',title:'Fruta y verdura',items:[['la lechuga','der Salat (Kopf)'],['la zanahoria','die Karotte'],['el plátano','die Banane'],['la fresa','die Erdbeere'],['el perejil','die Petersilie']]},
 {t:'vocab',title:'Más alimentos',items:[['el yogur','der Joghurt'],['la mayonesa','die Mayonnaise'],['el salmón','der Lachs'],['las gambas','die Garnelen'],['la ternera','das Kalbfleisch'],['el filete','das Steak, Filet'],['los cereales','das Müsli, die Cornflakes'],['el chocolate','die Schokolade'],['el helado de vainilla','das Vanilleeis'],['el aperitivo','der Aperitif, der Snack vor dem Essen'],['la infusión','der Kräutertee'],['el hielo','das Eis (Würfel)'],['el cava','der Sekt (aus Katalonien)']]},
 {t:'vocab',title:'Tiendas',items:[['la frutería','der Obstladen'],['la carnicería','die Metzgerei'],['el carnicero / la carnicera','der Metzger / die Metzgerin'],['la pizzería','die Pizzeria']]},
 {t:'match',q:'Ordne zu.',pairs:[['la zanahoria','die Karotte'],['las gambas','die Garnelen'],['la carnicería','die Metzgerei'],['la fresa','die Erdbeere'],['el hielo','das Eis (Würfel)']]},
 {t:'gap',q:'Para la ensalada necesito una ___ (Kopfsalat) y dos tomates.',a:['lechuga']},
 {t:'tr',de:'Ich nehme einen Kräutertee ohne Zucker.',a:['Tomo una infusión sin azúcar.','Para mí, una infusión sin azúcar.','Quiero una infusión sin azúcar.']}]});
P('u14',{id:'lx',title:'Vocabulario A2: fiestas y arte',desc:'Familie & Feste, Musik, Kunst',steps:[
 {t:'vocab',title:'Familia y fiestas',items:[['papá','Papa'],['mamá','Mama'],['los gemelos','die Zwillinge'],['la Navidad','Weihnachten'],['creer en Dios','an Gott glauben'],['el ramo de flores','der Blumenstrauß'],['la margarita','das Gänseblümchen'],['la papelería','das Schreibwarengeschäft'],['el maletín','die Aktentasche']]},
 {t:'vocab',title:'Música y arte',items:[['el / la artista','der Künstler / die Künstlerin'],['el pintor / la pintora','der Maler / die Malerin'],['pintar','malen'],['el fotógrafo / la fotógrafa','der Fotograf / die Fotografin'],['la cámara (de fotos)','die Kamera'],['la literatura','die Literatur'],['el violín','die Geige'],['el jazz','der Jazz'],['el tango','der Tango'],['el arquitecto / la arquitecta','der Architekt / die Architektin']]},
 {t:'match',q:'Ordne zu.',pairs:[['los gemelos','die Zwillinge'],['el ramo de flores','der Blumenstrauß'],['pintar','malen'],['el violín','die Geige'],['la Navidad','Weihnachten']]},
 {t:'tr',de:'Zum Geburtstag schenke ich ihr einen Blumenstrauß.',a:['Para su cumpleaños le regalo un ramo de flores.','Le regalo un ramo de flores para su cumpleaños.']}]});
P('u15',{id:'lx',title:'Vocabulario A2: sociedad y mundo',desc:'Politik, Welt, Internet',steps:[
 {t:'vocab',title:'Sociedad',items:[['el gobierno','die Regierung'],['el ministro / la ministra','der Minister / die Ministerin'],['el ayuntamiento','das Rathaus, die Stadtverwaltung'],['el juez / la jueza','der Richter / die Richterin'],['el príncipe / la princesa','der Prinz / die Prinzessin'],['la educación','die Bildung; die Erziehung'],['la región','die Region'],['el planeta','der Planet']]},
 {t:'vocab',title:'Internet',items:[['navegar por internet','im Internet surfen'],['chatear','chatten'],['el chat','der Chat'],['el virus','der Virus']]},
 {t:'match',q:'Ordne zu.',pairs:[['el gobierno','die Regierung'],['el ministro','der Minister'],['chatear','chatten'],['el planeta','der Planet'],['el juez','der Richter']]},
 {t:'mc',q:'„la educación“ heißt Bildung – und auch …',opts:['gutes Benehmen / Erziehung','Ausbildungsplatz','Universität'],a:0},
 {t:'tr',de:'In Zukunft werden wir mehr im Internet surfen.',a:['En el futuro navegaremos más por internet.']}]});
P('u15',{id:'lz',icon:'🎯',title:'Prueba DELE A2',desc:'Übungstest im DELE-Format',steps:[
 {t:'info',title:'Das DELE A2',html:`<p>Das <b>DELE A2</b> hat dieselben vier Teile wie das A1, ist aber länger und verlangt mehr eigene Sätze:</p>
 <table><tr><th>Teil</th><th>Dauer</th><th>Aufgaben</th></tr>
 <tr><td>Comprensión de lectura</td><td>60 Min.</td><td>Brief/E-Mail, acht kurze Texte (Anzeigen, Hinweise), drei Texte ↔ sechs Aussagen, ein längerer Text</td></tr>
 <tr><td>Comprensión auditiva</td><td>40 Min.</td><td>Durchsagen, kurze Gespräche, Radiobeiträge – alles zweimal</td></tr>
 <tr><td>Expresión e interacción escritas</td><td>45 Min.</td><td>Antwort auf eine Nachricht (60–70 Wörter) und ein kurzer Text über Erlebnisse (70–80 Wörter)</td></tr>
 <tr><td>Expresión e interacción orales</td><td>12 Min. + 12 Min. Vorbereitung</td><td>kurzer Vortrag über deinen Alltag, ein Foto beschreiben, ein Rollenspiel</td></tr></table>
 <p>Bestanden ist man wie beim A1 mit je <b>30 von 50 Punkten</b> in Lesen + Schreiben und Hören + Sprechen.</p>`},
 {t:'read',kind:'Lectura · Tarea 1',title:'Un correo de Marcos',text:`Hola, Jonas:
¡Por fin tengo tiempo para escribirte! El mes pasado empecé a trabajar en un hotel en Mallorca. Trabajo en la recepción y hablo inglés y alemán todos los días, así que estoy aprendiendo mucho. Los primeros días fueron difíciles porque no conocía a nadie, pero ahora tengo un grupo de amigos muy simpático. Los domingos, que es mi día libre, vamos a la playa o hacemos excursiones por la montaña.
En verano voy a tener una semana de vacaciones y me gustaría visitarte en Barcelona. ¿Te va bien en julio? Ya he mirado los barcos: hay uno que sale de Palma por la noche y llega a Barcelona a las siete de la mañana.
Escríbeme pronto,
Marcos`,de:`Hallo Jonas,
endlich habe ich Zeit, dir zu schreiben! Letzten Monat habe ich angefangen, in einem Hotel auf Mallorca zu arbeiten. Ich arbeite an der Rezeption und spreche jeden Tag Englisch und Deutsch, also lerne ich sehr viel. Die ersten Tage waren schwierig, weil ich niemanden kannte, aber jetzt habe ich eine sehr nette Gruppe von Freunden. Sonntags, an meinem freien Tag, gehen wir an den Strand oder machen Ausflüge in die Berge.
Im Sommer habe ich eine Woche Urlaub und würde dich gern in Barcelona besuchen. Passt dir der Juli? Ich habe schon nach Fähren geschaut: Es gibt eine, die nachts in Palma ablegt und um sieben Uhr morgens in Barcelona ankommt.
Schreib mir bald,
Marcos`},
 {t:'mc',kind:'Lectura · Tarea 1',q:'¿Dónde trabaja Marcos?',opts:['en la recepción de un hotel','en una escuela de idiomas','en un barco'],a:0},
 {t:'mc',kind:'Lectura · Tarea 1',q:'¿Por qué fueron difíciles los primeros días?',opts:['porque no conocía a nadie','porque no hablaba alemán','porque trabajaba los domingos'],a:0},
 {t:'mc',kind:'Lectura · Tarea 1',q:'¿Cómo quiere viajar Marcos a Barcelona?',opts:['en barco, de noche','en avión, por la mañana','en tren'],a:0},
 {t:'mc',kind:'Lectura · Tarea 2',q:'Anuncio: «Curso de fotografía para principiantes. Ocho sesiones, los jueves de 19 a 21 h. Trae tu propia cámara (también sirve el móvil). Precio: 90 €, materiales incluidos.» – ¿Qué necesitas para el curso?',opts:['una cámara o un móvil','comprar los materiales','experiencia en fotografía'],a:0},
 {t:'mc',kind:'Lectura · Tarea 2',q:'Aviso en un edificio: «Del 3 al 7 de marzo no funcionará el ascensor por obras. Disculpen las molestias.» – ¿Qué pasa del 3 al 7 de marzo?',opts:['Hay que usar la escalera.','El edificio está cerrado.','Hay una fiesta de vecinos.'],a:0},
 {t:'mc',kind:'Lectura · Tarea 2',q:'Foro: «¿Alguien conoce un restaurante vegetariano barato cerca de la Sagrada Familia? Somos seis y queremos ir el sábado. – Laura» – ¿Qué busca Laura?',opts:['un restaurante sin carne y no muy caro','un hotel para seis personas','una visita a la Sagrada Familia'],a:0},
 {t:'mc',kind:'Lectura · Tarea 3',q:'Tres anuncios de pisos: A) piso céntrico, 2 habitaciones, sin muebles, 950 €; B) habitación en piso compartido con estudiantes, wifi y limpieza incluidos, 400 €; C) chalé con jardín a 20 km de la ciudad, 1.300 €. – «Tengo un perro grande y no me importa vivir fuera de la ciudad.»',opts:['C','A','B'],a:0},
 {t:'mc',kind:'Lectura · Tarea 3',q:'Mismos anuncios – «Acabo de llegar, no tengo muebles y quiero conocer gente.»',opts:['B','A','C'],a:0},
 {t:'read',kind:'Lectura · Tarea 4',title:'Las bicicletas de la ciudad',text:`Desde hace diez años, Barcelona tiene un servicio público de bicicletas. Para usarlo, hay que hacerse socio por internet y pagar una cuota anual. Después, con una tarjeta o con el móvil, se puede coger una bicicleta en cualquiera de las más de quinientas estaciones de la ciudad. Los primeros treinta minutos están incluidos en la cuota; después hay que pagar un poco más. Muchas personas usan las bicicletas para ir al trabajo, porque es más rápido que el autobús en las horas punta. Desde el año pasado también hay bicicletas eléctricas, muy prácticas para subir a los barrios altos. Los turistas, sin embargo, no pueden usar este servicio: para ellos hay tiendas de alquiler de bicicletas.`,de:`Seit zehn Jahren hat Barcelona ein öffentliches Fahrradverleihsystem. Um es zu nutzen, muss man sich im Internet anmelden und einen Jahresbeitrag bezahlen. Danach kann man mit einer Karte oder dem Handy an jeder der über fünfhundert Stationen der Stadt ein Fahrrad nehmen. Die ersten dreißig Minuten sind im Beitrag enthalten; danach muss man etwas mehr bezahlen. Viele nutzen die Räder für den Weg zur Arbeit, weil es in der Rushhour schneller ist als der Bus. Seit letztem Jahr gibt es auch E-Bikes, sehr praktisch, um in die höher gelegenen Viertel zu fahren. Touristen können diesen Dienst dagegen nicht nutzen: Für sie gibt es Fahrradverleihe.`},
 {t:'mc',kind:'Lectura · Tarea 4',q:'Para usar las bicicletas públicas hay que …',opts:['pagar una cuota anual','ir a una tienda de alquiler','tener una bicicleta eléctrica'],a:0},
 {t:'mc',kind:'Lectura · Tarea 4',q:'Según el texto, mucha gente usa las bicicletas porque …',opts:['son más rápidas que el autobús en horas punta','son gratis para siempre','los autobuses no funcionan'],a:0},
 {t:'mc',kind:'Lectura · Tarea 4',q:'Los turistas …',opts:['tienen que alquilar bicicletas en tiendas','pueden usar el servicio con el móvil','pagan menos'],a:0},
 {t:'read',hideText:true,kind:'Comprensión auditiva · Tarea 1',title:'Aviso en la estación',intro:'Escucha el aviso.',text:`Atención, señores viajeros: el tren regional con destino a Girona, con salida prevista a las 16:40, saldrá con un retraso de veinticinco minutos por problemas técnicos. El tren saldrá de la vía cuatro. Disculpen las molestias.`,de:`Achtung, liebe Reisende: Der Regionalzug nach Girona, planmäßige Abfahrt 16:40 Uhr, fährt wegen technischer Probleme mit fünfundzwanzig Minuten Verspätung. Der Zug fährt von Gleis vier ab. Entschuldigen Sie die Unannehmlichkeiten.`},
 {t:'mc',kind:'Comprensión auditiva · Tarea 1',q:'¿A qué hora sale ahora el tren a Girona?',opts:['a las 17:05','a las 16:40','a las 16:15'],a:0},
 {t:'read',hideText:true,kind:'Comprensión auditiva · Tarea 2',title:'En la farmacia',intro:'Escucha la conversación.',text:`– Buenas tardes. Desde ayer me duele mucho la garganta y tengo un poco de fiebre. – ¿Tiene tos? – No, tos no. – Entonces le doy estas pastillas. Tome una cada ocho horas, después de comer. Y beba mucha agua. Si en tres días no está mejor, vaya al médico.`,de:`– Guten Tag. Seit gestern tut mir der Hals sehr weh und ich habe etwas Fieber. – Haben Sie Husten? – Nein, Husten nicht. – Dann gebe ich Ihnen diese Tabletten. Nehmen Sie alle acht Stunden eine, nach dem Essen. Und trinken Sie viel Wasser. Wenn es Ihnen in drei Tagen nicht besser geht, gehen Sie zum Arzt.`},
 {t:'mc',kind:'Comprensión auditiva · Tarea 2',q:'¿Cada cuánto tiene que tomar las pastillas?',opts:['cada ocho horas','tres veces por semana','antes de comer'],a:0},
 {t:'read',hideText:true,kind:'Comprensión auditiva · Tarea 3',title:'Un programa de radio',intro:'Escucha el programa.',text:`Y ahora, la agenda del fin de semana. El sábado, en el parque de la Ciutadella, hay un mercado de productos ecológicos de diez de la mañana a dos de la tarde. Por la noche, concierto de jazz gratuito en la plaza del Rey. Y el domingo, para los más pequeños, teatro de marionetas en la biblioteca del barrio. La entrada es libre, pero hay que reservar por teléfono.`,de:`Und jetzt die Termine fürs Wochenende. Am Samstag gibt es im Ciutadella-Park von zehn bis zwei Uhr einen Markt mit Bio-Produkten. Abends ein kostenloses Jazzkonzert auf der Plaça del Rei. Und am Sonntag für die Kleinsten Marionettentheater in der Stadtteilbibliothek. Der Eintritt ist frei, aber man muss telefonisch reservieren.`},
 {t:'mc',kind:'Comprensión auditiva · Tarea 3',q:'¿Qué hay el sábado por la noche?',opts:['un concierto de jazz gratis','un mercado ecológico','teatro para niños'],a:0},
 {t:'mc',kind:'Comprensión auditiva · Tarea 3',q:'Para el teatro de marionetas hay que …',opts:['reservar por teléfono','pagar la entrada','ir el sábado'],a:0},
 {t:'read',hideText:true,kind:'Comprensión auditiva · Tarea 4',title:'Dos amigas hablan',intro:'Escucha la conversación entre Elena y Sara.',text:`– Sara, ¿qué tal tu nuevo trabajo? – Muy bien, aunque está lejos de casa. Tardo una hora en llegar. – ¡Una hora! ¿Y cómo vas? – Primero en metro y después en autobús. Por eso estoy pensando en comprarme una moto. – ¿Una moto? A mí me da miedo. ¿Por qué no te cambias de piso? – Porque mi piso me encanta y es muy barato. Además, el año que viene la empresa se va a cambiar al centro.`,de:`– Sara, wie ist dein neuer Job? – Sehr gut, obwohl er weit weg von zu Hause ist. Ich brauche eine Stunde hin. – Eine Stunde! Und wie fährst du? – Erst mit der Metro und dann mit dem Bus. Deshalb überlege ich, mir ein Motorrad zu kaufen. – Ein Motorrad? Davor hätte ich Angst. Warum ziehst du nicht um? – Weil ich meine Wohnung liebe und sie sehr günstig ist. Außerdem zieht die Firma nächstes Jahr ins Zentrum.`},
 {t:'mc',kind:'Comprensión auditiva · Tarea 4',q:'Sara está pensando en …',opts:['comprarse una moto','cambiarse de piso','dejar su trabajo'],a:0},
 {t:'mc',kind:'Comprensión auditiva · Tarea 4',q:'¿Qué va a pasar el año que viene?',opts:['La empresa se va al centro.','Sara se cambia de piso.','Sara deja el metro.'],a:0},
 {t:'free',kind:'Expresión escrita · Tarea 1',task:'Contesta al correo de Marcos (60–70 palabras): dile si te va bien que venga en julio, qué podéis hacer juntos en Barcelona y dónde puede dormir. Pregúntale también por su trabajo.',hint:'Hola, Marcos: ¡Qué alegría …! Julio me va … Podemos … Puedes dormir … ¿Y qué tal …? Un abrazo, …',focus:'informeller Brief, alle Punkte, Futur/ir a, poder + Infinitiv, Fragen',model:'Hola, Marcos:\n¡Qué alegría recibir tu correo! Julio me va muy bien, porque en verano tengo menos trabajo. Podemos ir a la playa, visitar el Park Güell y cenar tapas en mi barrio. Puedes dormir en mi piso: tengo un sofá cama en el salón. ¿Y qué tal en el hotel? ¿Sigues contento con tus compañeros?\nUn abrazo,\nJonas'},
 {t:'free',kind:'Expresión escrita · Tarea 2',task:'Escribe un texto (70–80 palabras) sobre un viaje que hiciste: adónde fuiste y con quién, cómo era el lugar, qué hiciste y qué fue lo mejor.',hint:'El año pasado fui a … con … Era un lugar … Allí visitamos … / comimos … Lo mejor fue …',focus:'Indefinido (fui, visitamos) + Imperfecto (era, hacía), Zeitangaben',model:'El verano pasado fui a Lisboa con dos amigos de la universidad. Era una ciudad preciosa, con muchas cuestas y casas de colores. Hacía mucho calor, así que por las mañanas visitábamos museos y por las tardes íbamos a la playa. Un día cogimos el tranvía 28 y vimos toda la ciudad. Lo mejor fue la última noche: cenamos pescado en un restaurante pequeño y escuchamos fado.'},
 {t:'free',kind:'Expresión oral · Tarea 1',task:'Presentación (2–3 minutos): Tu tiempo libre. Bereite vor: Was machst du in deiner Freizeit? Mit wem? Wie oft? Was hast du letztes Wochenende gemacht? Was möchtest du gern ausprobieren?',hint:'En mi tiempo libre me gusta … Normalmente … El fin de semana pasado … Me gustaría probar …',focus:'gustar, Häufigkeit, Indefinido, me gustaría',model:'En mi tiempo libre me gusta mucho hacer deporte: juego al fútbol con unos compañeros dos veces por semana. También me encanta cocinar para mis amigos. El fin de semana pasado hicimos una excursión a Montserrat y comimos en un pueblo. Me gustaría aprender a bailar salsa, porque en Barcelona hay muchas clases.'},
 {t:'free',kind:'Expresión oral · Tarea 2',task:'Descripción de una imagen (2–3 minutos): Stell dir dieses Foto vor 🛒🍅🧀👩‍🦰👨‍🦳: ein Marktstand, eine junge Frau mit roten Haaren kauft Tomaten, ein älterer Verkäufer wiegt sie, im Hintergrund viele Leute. Beschreibe: Wo sind sie? Wer ist da? Was machen sie? Was glaubst du: Was sagen sie?',hint:'En la foto hay … Está en … La chica lleva … y está comprando … El vendedor … Creo que …',focus:'hay, estar + Gerundium, llevar, Ortsangaben, creo que',model:'En la foto hay un mercado con mucha gente. En primer plano hay una chica joven con el pelo rojo; está comprando tomates. El vendedor es un señor mayor y está pesando los tomates. Detrás hay más puestos con fruta y queso. Creo que es sábado por la mañana. La chica seguramente pregunta: «¿Cuánto cuestan?».'},
 {t:'dialog',kind:'Expresión oral · Tarea 3',place:'Tienda de ropa',title:'Situación simulada: cambiar una prenda',scene:'Du hast gestern eine Jacke gekauft, aber sie ist zu klein. Der Prüfer spielt den Verkäufer.',lines:[
  {n:'Dependiente',es:'Buenos días, ¿en qué puedo ayudarle?',de:'Guten Tag, wie kann ich Ihnen helfen?'},
  {you:true,opts:[{es:'Ayer compré esta chaqueta, pero me queda pequeña. ¿Puedo cambiarla?',ok:true},{es:'Ayer compro esta chaqueta y es grande.',ok:false,why:'Gestern → Indefinido: <i>compré</i>. Und das Problem ist, dass sie <b>zu klein</b> ist.'}]},
  {n:'Dependiente',es:'Claro. ¿Tiene el tique?',de:'Natürlich. Haben Sie den Kassenbon?'},
  {you:true,opts:[{es:'Sí, aquí está. ¿La tienen en una talla más grande?',ok:true},{es:'No, gracias, no tengo hambre.',ok:false,why:'<i>el tique</i> = der Kassenbon 😉'}]},
  {n:'Dependiente',es:'Sí, en la talla L. ¿Quiere probársela?',de:'Ja, in Größe L. Möchten Sie sie anprobieren?'},
  {you:true,opts:[{es:'Sí, por favor. ¿Dónde está el probador?',ok:true},{es:'Sí, me la pruebo mañana en casa.',ok:false,why:'Im Laden probiert man im <i>probador</i> an.'}]}]},
 {t:'info',title:'¡Enhorabuena! 🎉',html:`<p>Damit hast du alle Teile des <b>DELE A2</b> geübt. Wenn du etwa 60 % geschafft hast, bist du bereit für die Prüfung – Termine unter <span class="es-t">examenes.cervantes.es</span>.</p>`}]});
})();
