/* Vocabulario B1 – freiwillige Zusatzlektionen (Extras-Kachel, plus:true + ab:true: zählen nicht für Fortschritt und Tagesplan).
   Schließen die Lücken zur B1-Liste des Plan Curricular (Instituto Cervantes, „Nociones específicas B1“), passend zum Thema der Unidad.
   Abdeckung prüfen: python3 test/a1_check.py --kurs es --liste quellen/pcic_b1_es.json (lokal) */
(function(){
function P(uid,l){var u=COURSE.units.filter(function(x){return x.id===uid;})[0];if(u)u.lessons.push(Object.assign({ab:true,plus:true,icon:'📙'},l));}
P('u16',{id:'lx',title:'Vocabulario B1: cuerpo, salud y deporte',desc:'Körper, Arzt & Klinik, Ernährung, Sport',steps:[
 {t:'vocab',title:'El cuerpo',items:[['el músculo','der Muskel'],['el hueso','der Knochen'],['el corazón','das Herz'],['el pulmón','die Lunge'],['la cintura','die Taille'],['la barriga','der Bauch'],['el tobillo','der Knöchel'],['el codo','der Ellbogen'],['la postura','die Haltung']]},
 {t:'vocab',title:'Médicos y tratamientos',items:[['la clínica','die Klinik'],['el / la dentista','der Zahnarzt / die Zahnärztin'],['el cirujano / la cirujana','der Chirurg / die Chirurgin'],['el psicólogo / la psicóloga','der Psychologe / die Psychologin'],['ingresar en el hospital','ins Krankenhaus eingeliefert werden'],['el análisis de sangre','die Blutuntersuchung'],['la vacuna','der Impfstoff'],['el antibiótico','das Antibiotikum'],['la aspirina','das Aspirin'],['el termómetro','das Fieberthermometer'],['la tirita','das Pflaster'],['curar','heilen'],['agotado / agotada','erschöpft']]},
 {t:'vocab',title:'Alimentación',items:[['la alimentación','die Ernährung'],['equilibrado / equilibrada','ausgewogen'],['el alimento','das Nahrungsmittel'],['ligero / ligera','leicht (Essen)'],['la caloría','die Kalorie'],['la vitamina','das Vitamin'],['la proteína','das Eiweiß, Protein'],['diabético / diabética','zuckerkrank'],['hacer régimen','Diät machen'],['adelgazar','abnehmen'],['engordar','zunehmen']]},
 {t:'vocab',title:'Deporte',items:[['el / la deportista','der Sportler / die Sportlerin'],['el árbitro / la árbitra','der Schiedsrichter / die Schiedsrichterin'],['el ganador / la ganadora','der Gewinner / die Gewinnerin'],['empatar','unentschieden spielen'],['el balón','der Ball (groß)'],['la raqueta','der Schläger'],['el chándal','der Trainingsanzug'],['el atletismo','die Leichtathletik'],['el ciclismo','der Radsport'],['la natación','das Schwimmen'],['el esquí','das Skifahren'],['el boxeo','das Boxen']]},
 {t:'match',q:'Ordne zu.',pairs:[['el corazón','das Herz'],['adelgazar','abnehmen'],['la vacuna','der Impfstoff'],['empatar','unentschieden spielen'],['el codo','der Ellbogen']]},
 {t:'gap',q:'El médico me recomienda que haga una alimentación más ___ (ausgewogen) y que coma menos calorías.',a:['equilibrada']},
 {t:'tr',de:'Ich bin erschöpft, ich brauche Urlaub.',a:['Estoy agotado, necesito vacaciones.','Estoy agotada, necesito vacaciones.']}]});
P('u17',{id:'lx',title:'Vocabulario B1: carácter y etapas de la vida',desc:'Charakter, Gefühle, Lebensabschnitte, Feste',steps:[
 {t:'vocab',title:'Carácter',items:[['introvertido / introvertida','introvertiert'],['hablador / habladora','gesprächig'],['arrogante','arrogant'],['conservador / conservadora','konservativ'],['travieso / traviesa','frech (Kinder)'],['sensible','sensibel'],['paciente','geduldig'],['la paciencia','die Geduld'],['educado / educada','höflich, gut erzogen'],['maleducado / maleducada','unhöflich'],['distraído / distraída','zerstreut'],['el sentido del humor','der Humor'],['el optimismo','der Optimismus'],['el pesimismo','der Pessimismus'],['la actitud','die Einstellung'],['positivo / positiva','positiv']]},
 {t:'vocab',title:'Estados de ánimo',items:[['estresado / estresada','gestresst'],['deprimido / deprimida','deprimiert'],['asustado / asustada','erschrocken, verängstigt'],['aburrirse','sich langweilen'],['la tranquilidad','die Ruhe']]},
 {t:'vocab',title:'Etapas de la vida',items:[['la infancia','die Kindheit'],['la madurez','die Reife'],['la vejez','das Alter'],['envejecer','älter werden'],['adoptar','adoptieren'],['estar embarazada','schwanger sein'],['obedecer','gehorchen'],['tutear','duzen'],['la separación','die Trennung']]},
 {t:'vocab',title:'Fiestas y regalos',items:[['típico / típica','typisch'],['tradicional','traditionell'],['el disfraz','das Kostüm'],['felicitar','gratulieren'],['envolver un regalo','ein Geschenk einpacken'],['el abrazo','die Umarmung'],['el álbum de fotos','das Fotoalbum'],['la joya','das Schmuckstück'],['el collar','die Halskette'],['los pendientes','die Ohrringe'],['la pulsera','das Armband']]},
 {t:'match',q:'Ordne die Gegenteile zu.',pairs:[['educado','maleducado'],['introvertido','hablador'],['el optimismo','el pesimismo'],['la infancia','la vejez'],['aburrirse','divertirse']]},
 {t:'gap',q:'Cuando era pequeño era muy ___ (frech) y nunca ___ (gehorchte, Imperfecto) a mis padres.',a:['travieso','obedecía']},
 {t:'tr',de:'In Spanien duzt man sich fast immer.',a:['En España casi siempre se tutea.','En España la gente casi siempre se tutea.','En España casi siempre nos tuteamos.']}]});
P('u18',{id:'lx',title:'Vocabulario B1: casa, aparatos y cocina',desc:'Einrichtung, Geräte, Garten, Kochen',steps:[
 {t:'vocab',title:'Decoración y aparatos',items:[['la decoración','die Einrichtung, Deko'],['la alfombra','der Teppich'],['la cortina','der Vorhang'],['el florero','die Vase'],['el electrodoméstico','das Haushaltsgerät'],['el frigorífico','der Kühlschrank'],['el congelador','der Gefrierschrank'],['la cafetera','die Kaffeemaschine'],['el secador','der Föhn'],['el aparato','das Gerät'],['encender','einschalten'],['apagar','ausschalten'],['enchufar','einstecken'],['el enchufe','die Steckdose, der Stecker'],['el interruptor','der Schalter'],['la bombilla','die Glühbirne'],['la linterna','die Taschenlampe'],['el timbre','die Klingel'],['roto / rota','kaputt']]},
 {t:'vocab',title:'Bricolaje y jardín',items:[['el bricolaje','das Heimwerken'],['la herramienta','das Werkzeug'],['el destornillador','der Schraubenzieher'],['la jardinería','die Gartenarbeit'],['el césped','der Rasen'],['regar','gießen'],['soleado / soleada','sonnig'],['las afueras','der Stadtrand'],['la zona residencial','das Wohngebiet'],['la hipoteca','die Hypothek']]},
 {t:'vocab',title:'En la cocina',items:[['el tenedor','die Gabel'],['el cuchillo','das Messer'],['el cazo','der Topf (klein)'],['el mantel','die Tischdecke'],['la jarra','der Krug'],['cocer','kochen (in Wasser)'],['asar','braten (im Ofen), grillen'],['quemarse','anbrennen'],['frito / frita','frittiert'],['hervido / hervida','gekocht'],['crudo / cruda','roh'],['salado / salada','salzig'],['picante','scharf'],['amargo / amarga','bitter'],['soso / sosa','fade'],['el sabor','der Geschmack']]},
 {t:'match',q:'Ordne zu.',pairs:[['encender','einschalten'],['apagar','ausschalten'],['la bombilla','die Glühbirne'],['el tenedor','die Gabel'],['soso','fade']]},
 {t:'gap',q:'Si se rompe la bombilla, ___ (nehmen, Futur) la linterna.',a:['cogeremos|tomaremos|usaremos']},
 {t:'tr',de:'Wenn ich Zeit hätte, würde ich die Pflanzen gießen.',a:['Si tuviera tiempo, regaría las plantas.','Si tuviese tiempo, regaría las plantas.']}]});
P('u19',{id:'lx',title:'Vocabulario B1: medios, sociedad y cultura',desc:'Presse, Fernsehen, Politik, Kunst & Literatur',steps:[
 {t:'vocab',title:'Prensa y televisión',items:[['la noticia','die Nachricht'],['el comentario','der Kommentar'],['el periodismo','der Journalismus'],['el reportaje','die Reportage'],['el suplemento','die Beilage'],['la cartelera','das Kino-/Theaterprogramm'],['la emisora','der Radiosender'],['el locutor / la locutora','der Sprecher / die Sprecherin (Radio)'],['el episodio','die Folge'],['la telenovela','die Seifenoper'],['el documental','der Dokumentarfilm'],['los subtítulos','die Untertitel']]},
 {t:'vocab',title:'Sociedad y política',items:[['la nación','die Nation'],['la provincia','die Provinz'],['el parlamento','das Parlament'],['el ministerio','das Ministerium'],['la república','die Republik'],['la monarquía','die Monarchie'],['la democracia','die Demokratie'],['la dictadura','die Diktatur'],['la ley','das Gesetz'],['la independencia','die Unabhängigkeit'],['el progreso','der Fortschritt'],['la pobreza','die Armut'],['la riqueza','der Reichtum'],['el impuesto','die Steuer'],['la crisis','die Krise'],['la huelga','der Streik'],['el sindicato','die Gewerkschaft'],['el / la inmigrante','der Einwanderer / die Einwanderin'],['el / la emigrante','der Auswanderer / die Auswanderin'],['la población','die Bevölkerung']]},
 {t:'vocab',title:'Arte y literatura',items:[['la arquitectura','die Architektur'],['la escultura','die Skulptur'],['el escultor / la escultora','der Bildhauer / die Bildhauerin'],['el paisaje','die Landschaft'],['el retrato','das Porträt'],['la muralla','die Stadtmauer'],['la mezquita','die Moschee'],['el / la poeta','der Dichter / die Dichterin'],['el poema','das Gedicht'],['el / la novelista','der Romanautor / die Romanautorin'],['el traductor / la traductora','der Übersetzer / die Übersetzerin'],['el / la protagonista','die Hauptfigur'],['la biografía','die Biografie'],['la novela policiaca','der Krimi'],['la ciencia ficción','die Science-Fiction'],['la comedia','die Komödie'],['el drama','das Drama'],['la película de terror','der Horrorfilm'],['la orquesta','das Orchester'],['el compositor / la compositora','der Komponist / die Komponistin'],['la imaginación','die Fantasie']]},
 {t:'match',q:'Ordne zu.',pairs:[['la huelga','der Streik'],['el impuesto','die Steuer'],['los subtítulos','die Untertitel'],['el retrato','das Porträt'],['la ley','das Gesetz']]},
 {t:'mc',q:'Du siehst Filme gern im Original. Was suchst du?',opts:['una película con subtítulos','una telenovela doblada','un suplemento'],a:0},
 {t:'tr',de:'Ich glaube nicht, dass die Krise bald endet.',a:['No creo que la crisis termine pronto.','No creo que la crisis acabe pronto.']}]});
P('u20',{id:'lx',title:'Vocabulario B1: viajes, tráfico y estudios',desc:'Verkehr, Unterkunft, Behörden, Uni',steps:[
 {t:'vocab',title:'Tráfico y transporte',items:[['la autopista','die Autobahn'],['el atasco','der Stau'],['el carril bici','der Radweg'],['el / la peatón/peatona','der Fußgänger / die Fußgängerin'],['el semáforo','die Ampel'],['el túnel','der Tunnel'],['el puente','die Brücke; das lange Wochenende'],['el tranvía','die Straßenbahn'],['el andén','der Bahnsteig'],['el transbordo','das Umsteigen'],['la gasolinera','die Tankstelle'],['la gasolina','das Benzin'],['el maletero','der Kofferraum'],['el cinturón','der Sicherheitsgurt'],['el helicóptero','der Hubschrauber']]},
 {t:'vocab',title:'De viaje',items:[['el visado','das Visum'],['el crucero','die Kreuzfahrt'],['el hostal','die Pension (einfaches Hotel)'],['el conserje','der Portier, Hausmeister'],['la orilla','das Ufer'],['la sombrilla','der Sonnenschirm'],['las sandalias','die Sandalen'],['el montañero / la montañera','der Bergsteiger / die Bergsteigerin'],['la escalada','das Klettern']]},
 {t:'vocab',title:'Burocracia y estudios',items:[['la burocracia','die Bürokratie'],['solicitar','beantragen'],['la secretaría','das Sekretariat'],['matricularse','sich einschreiben'],['el campus','der Campus'],['la asignatura','das Fach'],['la carrera','das Studium'],['el bachillerato','das Abitur'],['el doctorado','die Promotion'],['los apuntes','die Mitschrift'],['subrayar','unterstreichen'],['el resumen','die Zusammenfassung'],['el esquema','die Übersicht, das Schema'],['corregir','korrigieren'],['la carpeta','der Ordner'],['la guardería','die Kita']]},
 {t:'match',q:'Ordne zu.',pairs:[['el atasco','der Stau'],['solicitar','beantragen'],['la asignatura','das Fach'],['el andén','der Bahnsteig'],['el visado','das Visum']]},
 {t:'gap',q:'Cuando ___ (llegar, du) a la estación, haz transbordo a la línea 3.',a:['llegues']},
 {t:'tr',de:'Wenn du dich einschreibst, bring den Pass mit.',a:['Cuando te matricules, trae el pasaporte.','Cuando te matricules, lleva el pasaporte.']}]});
P('u21',{id:'lx',title:'Vocabulario B1: comunicación y trabajo',desc:'Nachrichten, Computer, Büro & Projekte',steps:[
 {t:'vocab',title:'Mensajes y ordenador',items:[['el recado','die Nachricht (mündlich), Besorgung'],['el contestador','der Anrufbeantworter'],['el saldo','das Guthaben'],['el buzón','der Briefkasten'],['el / la remitente','der Absender / die Absenderin'],['el destinatario / la destinataria','der Empfänger / die Empfängerin'],['la posdata','das PS'],['adjuntar','anhängen'],['el teclado','die Tastatur'],['el ratón','die Maus'],['pulsar','drücken'],['pegar','einfügen; kleben'],['instalar','installieren'],['el navegador','der Browser'],['el buscador','die Suchmaschine'],['el antivirus','das Antivirenprogramm']]},
 {t:'vocab',title:'En el trabajo',items:[['el informe','der Bericht'],['el presupuesto','das Budget'],['el proyecto','das Projekt'],['el pedido','die Bestellung'],['atender a un cliente','einen Kunden bedienen'],['el usuario / la usuaria','der Nutzer / die Nutzerin'],['la formación','die Ausbildung / Schulung'],['la experiencia','die Erfahrung'],['colaborar','zusammenarbeiten'],['el compromiso','die Verlobung; die Verpflichtung'],['el ayudante / la ayudante','der Assistent / die Assistentin'],['el / la sustituto/a','die Vertretung'],['el bufete','die Anwaltskanzlei'],['el laboratorio','das Labor'],['el almacén','das Lager'],['el taller','die Werkstatt']]},
 {t:'match',q:'Ordne zu.',pairs:[['adjuntar','anhängen'],['el teclado','die Tastatur'],['el informe','der Bericht'],['el almacén','das Lager'],['el saldo','das Guthaben']]},
 {t:'mc',q:'Indirekte Rede: „Mándame el informe.“ → Mi jefa me pide que …',opts:['le mande el informe.','le mando el informe.','me manda el informe.'],a:0},
 {t:'tr',de:'Sie hat mir gesagt, dass sie den Bericht angehängt hat.',a:['Me ha dicho que ha adjuntado el informe.','Me dijo que había adjuntado el informe.']}]});
P('u22',{id:'lx',title:'Vocabulario B1: compras, comida y ocio',desc:'Einkaufen, Lebensmittel, Hobbys',steps:[
 {t:'vocab',title:'De compras',items:[['las rebajas','der Schlussverkauf'],['el descuento','der Rabatt'],['la garantía','die Garantie'],['la devolución','die Rückgabe'],['el catálogo','der Katalog'],['cobrar','kassieren'],['el carrito','der Einkaufswagen'],['la cesta','der Korb'],['caducado / caducada','abgelaufen'],['congelado / congelada','tiefgekühlt'],['la loncha','die Scheibe (Wurst, Käse)'],['el trozo','das Stück'],['ancho / ancha','weit'],['estrecho / estrecha','eng'],['el tacón','der Absatz'],['la zapatilla','der Turnschuh, Hausschuh'],['coser','nähen']]},
 {t:'vocab',title:'Alimentos',items:[['el embutido','die Wurstwaren'],['el chorizo','die Paprikawurst'],['el lomo','die Lende'],['la pechuga','die Brust (Geflügel)'],['la chuleta','das Kotelett'],['la berenjena','die Aubergine'],['el calabacín','die Zucchini'],['las espinacas','der Spinat'],['los guisantes','die Erbsen'],['las lentejas','die Linsen'],['los garbanzos','die Kichererbsen'],['la cereza','die Kirsche'],['la piña','die Ananas'],['la nata','die Sahne'],['desnatado / desnatada','entrahmt (fettarm)'],['el vinagre','der Essig'],['la mostaza','der Senf'],['la yema','das Eigelb'],['la magdalena','die Muffin-Art (spanisch)'],['el gazpacho','die kalte Gemüsesuppe'],['la croqueta','die Krokette'],['la manzanilla','der Kamillentee'],['la resaca','der Kater (nach Alkohol)']]},
 {t:'vocab',title:'Ocio',items:[['coleccionar','sammeln'],['el crucigrama','das Kreuzworträtsel'],['el aficionado / la aficionada','der Fan / die Liebhaberin'],['el concurso','der Wettbewerb, die Quizshow'],['el videojuego','das Videospiel'],['la consola','die Spielkonsole'],['el juguete','das Spielzeug'],['la lotería','die Lotterie'],['inscribirse','sich anmelden'],['el picnic','das Picknick'],['el / la espectador/a','der Zuschauer / die Zuschauerin'],['el escenario','die Bühne']]},
 {t:'match',q:'Ordne zu.',pairs:[['las rebajas','der Schlussverkauf'],['caducado','abgelaufen'],['la nata','die Sahne'],['las lentejas','die Linsen'],['el crucigrama','das Kreuzworträtsel']]},
 {t:'gap',q:'Busco unos pantalones que no ___ (sein, Subjuntivo) tan estrechos.',a:['sean']},
 {t:'tr',de:'Dieser Joghurt ist abgelaufen.',a:['Este yogur está caducado.','Este yogur ha caducado.']}]});
P('u23',{id:'lx',title:'Vocabulario B1: naturaleza y ciencia',desc:'Natur, Tiere, Wetter, Landwirtschaft, Wissenschaft',steps:[
 {t:'vocab',title:'Naturaleza y clima',items:[['el océano','der Ozean'],['el continente','der Kontinent'],['la península','die Halbinsel'],['el valle','das Tal'],['la selva','der Dschungel'],['el hemisferio','die Erdhalbkugel'],['húmedo / húmeda','feucht'],['seco / seca','trocken'],['despejado','klar (Himmel)'],['nublado','bewölkt'],['el granizo','der Hagel'],['el huracán','der Hurrikan'],['el terremoto','das Erdbeben'],['la hierba','das Gras'],['la rama','der Ast'],['la raíz','die Wurzel'],['el tronco','der Baumstamm']]},
 {t:'vocab',title:'Animales',items:[['el insecto','das Insekt'],['el ave','der Vogel (allgemein)'],['el animal doméstico','das Haustier'],['el conejo','das Kaninchen'],['la oveja','das Schaf'],['la gallina','das Huhn'],['el león','der Löwe'],['el tigre','der Tiger'],['el elefante','der Elefant'],['la serpiente','die Schlange']]},
 {t:'vocab',title:'Campo, industria y reciclaje',items:[['la agricultura','die Landwirtschaft'],['la ganadería','die Viehzucht'],['el campesino / la campesina','der Bauer / die Bäuerin'],['el tractor','der Traktor'],['el huerto','der Gemüsegarten'],['el cultivo','der Anbau'],['la industria','die Industrie'],['el petróleo','das Erdöl'],['el carbón','die Kohle'],['el ladrillo','der Ziegelstein'],['el vidrio','das Glas (Material)'],['el cartón','die Pappe'],['la pila','die Batterie'],['la capa de ozono','die Ozonschicht'],['conservar','erhalten, bewahren']]},
 {t:'vocab',title:'Ciencia',items:[['la ecología','die Ökologie'],['la biología','die Biologie'],['la física','die Physik'],['la química','die Chemie'],['el descubrimiento','die Entdeckung'],['el experimento','das Experiment'],['el / la veterinario/a','der Tierarzt / die Tierärztin'],['el / la astronauta','der Astronaut / die Astronautin'],['el satélite','der Satellit'],['sólido / sólida','fest'],['líquido / líquida','flüssig']]},
 {t:'match',q:'Ordne zu.',pairs:[['el terremoto','das Erdbeben'],['la pila','die Batterie'],['el vidrio','das Glas (Material)'],['la oveja','das Schaf'],['nublado','bewölkt']]},
 {t:'gap',q:'Es importante que ___ (wir recyceln) el vidrio y las pilas.',a:['reciclemos']},
 {t:'tr',de:'Es ist schade, dass so viele Wälder verschwinden.',a:['Es una pena que desaparezcan tantos bosques.']}]});
})();
