/* Vocabulario B1 – freiwillige Zusatzlektionen (Extras-Kachel, plus:true + ab:true: zählen nicht für Fortschritt und Tagesplan).
   Schließen die Lücken zur B1-Liste des Plan Curricular (Instituto Cervantes, „Nociones específicas B1“), passend zum Thema der Unidad.
   Abdeckung prüfen: python3 test/a1_check.py --kurs es --liste quellen/pcic_b1_es.json (lokal) */
(function(){
function P(uid,l){var u=COURSE.units.filter(function(x){return x.id===uid;})[0];if(u)u.lessons.push(Object.assign({ab:true,plus:true,icon:'📙'},l));}
P('u16',{id:'lx',title:'Vocabulario B1: cuerpo, salud y deporte',desc:'Körper, Arzt & Klinik, Ernährung, Sport',steps:[
 {t:'vocab',title:'El cuerpo',items:[['el músculo','der Muskel'],['el hueso','der Knochen'],['el corazón','das Herz'],['el pulmón','die Lunge'],['la cintura','die Taille'],['la barriga','der Bauch'],['el tobillo','der Knöchel'],['el codo','der Ellbogen'],['la postura','die Haltung']]},
 {t:'vocab',title:'Médicos y tratamientos',items:[['la clínica','die Klinik'],['el / la dentista','der Zahnarzt / die Zahnärztin'],['el cirujano / la cirujana','der Chirurg / die Chirurgin'],['el psicólogo / la psicóloga','der Psychologe / die Psychologin'],['ingresar en el hospital','ins Krankenhaus eingeliefert werden'],['el análisis de sangre','die Blutuntersuchung'],['la vacuna','der Impfstoff'],['el antibiótico','das Antibiotikum'],['la aspirina','das Aspirin'],['el termómetro','das Fieberthermometer'],['la tirita','das Pflaster'],['curar','heilen'],['agotado / agotada','erschöpft']]},
 {t:'vocab',title:'Alimentación',items:[['la alimentación','die Ernährung'],['equilibrado / equilibrada','ausgewogen'],['el alimento','das Nahrungsmittel'],['ligero / ligera','leicht (Essen)'],['la caloría','die Kalorie'],['la vitamina','das Vitamin'],['la proteína','das Eiweiß, Protein'],['diabético / diabética','zuckerkrank'],['hacer régimen','Diät machen'],['adelgazar','abnehmen'],['engordar','zunehmen']]},
 {t:'vocab',title:'Deporte',items:[['el / la deportista','der Sportler / die Sportlerin'],['el árbitro / la árbitra','der Schiedsrichter / die Schiedsrichterin'],['el ganador / la ganadora','der Gewinner / die Gewinnerin'],['empatar','unentschieden spielen'],['el balón','der Ball (groß)'],['la raqueta','der Schläger'],['el chándal','der Trainingsanzug'],['el atletismo','die Leichtathletik'],['el ciclismo','der Radsport'],['la natación','das Schwimmen'],['el esquí','das Skifahren'],['el boxeo','das Boxen']]},
 {t:'match',q:'Ordne zu.',pairs:[['el corazón','das Herz'],['adelgazar','abnehmen'],['la vacuna','der Impfstoff'],['empatar','unentschieden spielen'],['el codo','der Ellbogen']]},
 {t:'gap',q:'El médico me recomienda que haga una alimentación más ___ (ausgewogen) y que coma menos calorías.',a:['equilibrada']},
 {t:'tr',de:'Ich bin erschöpft, ich brauche Urlaub.',a:['Estoy agotado, necesito vacaciones.','Estoy agotada, necesito vacaciones.']}]});
P('u17',{id:'lx',title:'Vocabulario B1: carácter y etapas de la vida',desc:'Charakter, Gefühle, Lebensabschnitte, Feste',steps:[
 {t:'vocab',title:'Carácter',items:[['introvertido / introvertida','introvertiert'],['hablador / habladora','gesprächig'],['arrogante','arrogant'],['conservador / conservadora','konservativ'],['travieso / traviesa','frech (Kinder)'],['sensible','sensibel'],['paciente','geduldig'],['la paciencia','die Geduld'],['educado / educada','höflich, gut erzogen'],['maleducado / maleducada','unhöflich'],['distraído / distraída','zerstreut'],['el sentido del humor','der Humor'],['el optimismo','der Optimismus'],['el pesimismo','der Pessimismus'],['la actitud','die Einstellung'],['positivo / positiva','positiv']]},
 {t:'vocab',title:'Estados de ánimo',items:[['estresado / estresada','gestresst'],['deprimido / deprimida','deprimiert'],['asustado / asustada','erschrocken, verängstigt'],['aburrirse','sich langweilen'],['la tranquilidad','die Ruhe']]},
 {t:'vocab',title:'Etapas de la vida',items:[['la infancia','die Kindheit'],['la madurez','die Reife'],['la vejez','das Alter'],['envejecer','älter werden'],['adoptar','adoptieren'],['estar embarazada','schwanger sein'],['obedecer','gehorchen'],['tutear','duzen'],['la separación','die Trennung']]},
 {t:'vocab',title:'Fiestas y regalos',items:[['típico / típica','typisch'],['tradicional','traditionell'],['el disfraz','das Kostüm'],['felicitar','gratulieren'],['envolver un regalo','ein Geschenk einpacken'],['el abrazo','die Umarmung'],['el álbum de fotos','das Fotoalbum'],['la joya','das Schmuckstück'],['el collar','die Halskette'],['los pendientes','die Ohrringe'],['la pulsera','das Armband']]},
 {t:'match',q:'Ordne die Gegenteile zu.',pairs:[['educado','maleducado'],['introvertido','hablador'],['el optimismo','el pesimismo'],['la infancia','la vejez'],['aburrirse','divertirse']]},
 {t:'gap',q:'Cuando era pequeño era muy ___ (frech) y nunca ___ (gehorchte, Imperfecto) a mis padres.',a:['travieso','obedecía']},
 {t:'tr',de:'In Spanien duzt man sich fast immer.',a:['En España casi siempre se tutea.','En España la gente casi siempre se tutea.','En España casi siempre nos tuteamos.']}]});
P('u18',{id:'lx',title:'Vocabulario B1: casa, aparatos y cocina',desc:'Einrichtung, Geräte, Garten, Kochen',steps:[
 {t:'vocab',title:'Decoración y aparatos',items:[['la decoración','die Einrichtung, Deko'],['la alfombra','der Teppich'],['la cortina','der Vorhang'],['el florero','die Vase'],['el electrodoméstico','das Haushaltsgerät'],['el frigorífico','der Kühlschrank'],['el congelador','der Gefrierschrank'],['la cafetera','die Kaffeemaschine'],['el secador','der Föhn'],['el aparato','das Gerät'],['encender','einschalten'],['apagar','ausschalten'],['enchufar','einstecken'],['el enchufe','die Steckdose, der Stecker'],['el interruptor','der Schalter'],['la bombilla','die Glühbirne'],['la linterna','die Taschenlampe'],['el timbre','die Klingel'],['roto / rota','kaputt']]},
 {t:'vocab',title:'Bricolaje y jardín',items:[['el bricolaje','das Heimwerken'],['la herramienta','das Werkzeug'],['el destornillador','der Schraubenzieher'],['la jardinería','die Gartenarbeit'],['el césped','der Rasen'],['regar','gießen'],['soleado / soleada','sonnig'],['las afueras','der Stadtrand'],['la zona residencial','das Wohngebiet'],['la hipoteca','die Hypothek']]},
 {t:'vocab',title:'En la cocina',items:[['el tenedor','die Gabel'],['el cuchillo','das Messer'],['el cazo','der Topf (klein)'],['el mantel','die Tischdecke'],['la jarra','der Krug'],['cocer','kochen (in Wasser)'],['asar','braten (im Ofen), grillen'],['quemarse','anbrennen'],['frito / frita','frittiert'],['hervido / hervida','gekocht'],['crudo / cruda','roh'],['salado / salada','salzig'],['picante','scharf'],['amargo / amarga','bitter'],['soso / sosa','fade'],['el sabor','der Geschmack']]},
 {t:'match',q:'Ordne zu.',pairs:[['encender','einschalten'],['apagar','ausschalten'],['la bombilla','die Glühbirne'],['el tenedor','die Gabel'],['soso','fade']]},
 {t:'gap',q:'Si se rompe la bombilla, ___ (nehmen, Futur) la linterna.',a:['cogeremos|tomaremos|usaremos']},
 {t:'tr',de:'Wenn ich Zeit hätte, würde ich die Pflanzen gießen.',a:['Si tuviera tiempo, regaría las plantas.','Si tuviese tiempo, regaría las plantas.']}]});
P('u19',{id:'lx',title:'Vocabulario B1: medios, sociedad y cultura',desc:'Presse, Fernsehen, Politik, Kunst & Literatur',steps:[
 {t:'vocab',title:'Prensa y televisión',items:[['la noticia','die Nachricht'],['el comentario','der Kommentar'],['el periodismo','der Journalismus'],['el reportaje','die Reportage'],['el suplemento','die Beilage'],['la cartelera','das Kino-/Theaterprogramm'],['la emisora','der Radiosender'],['el locutor / la locutora','der Sprecher / die Sprecherin (Radio)'],['el episodio','die Folge'],['la telenovela','die Seifenoper'],['el documental','der Dokumentarfilm'],['los subtítulos','die Untertitel']]},
 {t:'vocab',title:'Sociedad y política',items:[['la nación','die Nation'],['la provincia','die Provinz'],['el parlamento','das Parlament'],['el ministerio','das Ministerium'],['la república','die Republik'],['la monarquía','die Monarchie'],['la democracia','die Demokratie'],['la dictadura','die Diktatur'],['la ley','das Gesetz'],['la independencia','die Unabhängigkeit'],['el progreso','der Fortschritt'],['la pobreza','die Armut'],['la riqueza','der Reichtum'],['el impuesto','die Steuer'],['la crisis','die Krise'],['la huelga','der Streik'],['el sindicato','die Gewerkschaft'],['el / la inmigrante','der Einwanderer / die Einwanderin'],['el / la emigrante','der Auswanderer / die Auswanderin'],['la población','die Bevölkerung']]},
 {t:'vocab',title:'Arte y literatura',items:[['la arquitectura','die Architektur'],['la escultura','die Skulptur'],['el escultor / la escultora','der Bildhauer / die Bildhauerin'],['el paisaje','die Landschaft'],['el retrato','das Porträt'],['la muralla','die Stadtmauer'],['la mezquita','die Moschee'],['el / la poeta','der Dichter / die Dichterin'],['el poema','das Gedicht'],['el / la novelista','der Romanautor / die Romanautorin'],['el traductor / la traductora','der Übersetzer / die Übersetzerin'],['el / la protagonista','die Hauptfigur'],['la biografía','die Biografie'],['la novela policiaca','der Krimi'],['la ciencia ficción','die Science-Fiction'],['la comedia','die Komödie'],['el drama','das Drama'],['la película de terror','der Horrorfilm'],['la orquesta','das Orchester'],['el compositor / la compositora','der Komponist / die Komponistin'],['la imaginación','die Fantasie']]},
 {t:'match',q:'Ordne zu.',pairs:[['la huelga','der Streik'],['el impuesto','die Steuer'],['los subtítulos','die Untertitel'],['el retrato','das Porträt'],['la ley','das Gesetz']]},
 {t:'mc',q:'Du siehst Filme gern im Original. Was suchst du?',opts:['una película con subtítulos','una telenovela doblada','un suplemento'],a:0},
 {t:'tr',de:'Ich glaube nicht, dass die Krise bald endet.',a:['No creo que la crisis termine pronto.','No creo que la crisis acabe pronto.']}]});
P('u20',{id:'lx',title:'Vocabulario B1: viajes, tráfico y estudios',desc:'Verkehr, Unterkunft, Behörden, Uni',steps:[
 {t:'vocab',title:'Tráfico y transporte',items:[['la autopista','die Autobahn'],['el atasco','der Stau'],['el carril bici','der Radweg'],['el / la peatón/peatona','der Fußgänger / die Fußgängerin'],['el semáforo','die Ampel'],['el túnel','der Tunnel'],['el puente','die Brücke; das lange Wochenende'],['el tranvía','die Straßenbahn'],['el andén','der Bahnsteig'],['el transbordo','das Umsteigen'],['la gasolinera','die Tankstelle'],['la gasolina','das Benzin'],['el maletero','der Kofferraum'],['el cinturón','der Sicherheitsgurt'],['el helicóptero','der Hubschrauber']]},
 {t:'vocab',title:'De viaje',items:[['el visado','das Visum'],['el crucero','die Kreuzfahrt'],['el hostal','die Pension (einfaches Hotel)'],['el conserje','der Portier, Hausmeister'],['la orilla','das Ufer'],['la sombrilla','der Sonnenschirm'],['las sandalias','die Sandalen'],['el montañero / la montañera','der Bergsteiger / die Bergsteigerin'],['la escalada','das Klettern']]},
 {t:'vocab',title:'Burocracia y estudios',items:[['la burocracia','die Bürokratie'],['solicitar','beantragen'],['la secretaría','das Sekretariat'],['matricularse','sich einschreiben'],['el campus','der Campus'],['la asignatura','das Fach'],['la carrera','das Studium'],['el bachillerato','das Abitur'],['el doctorado','die Promotion'],['los apuntes','die Mitschrift'],['subrayar','unterstreichen'],['el resumen','die Zusammenfassung'],['el esquema','die Übersicht, das Schema'],['corregir','korrigieren'],['la carpeta','der Ordner'],['la guardería','die Kita']]},
 {t:'match',q:'Ordne zu.',pairs:[['el atasco','der Stau'],['solicitar','beantragen'],['la asignatura','das Fach'],['el andén','der Bahnsteig'],['el visado','das Visum']]},
 {t:'gap',q:'Cuando ___ (llegar, du) a la estación, haz transbordo a la línea 3.',a:['llegues']},
 {t:'tr',de:'Wenn du dich einschreibst, bring den Pass mit.',a:['Cuando te matricules, trae el pasaporte.','Cuando te matricules, lleva el pasaporte.']}]});
P('u21',{id:'lx',title:'Vocabulario B1: comunicación y trabajo',desc:'Nachrichten, Computer, Büro & Projekte',steps:[
 {t:'vocab',title:'Mensajes y ordenador',items:[['el recado','die Nachricht (mündlich), Besorgung'],['el contestador','der Anrufbeantworter'],['el saldo','das Guthaben'],['el buzón','der Briefkasten'],['el / la remitente','der Absender / die Absenderin'],['el destinatario / la destinataria','der Empfänger / die Empfängerin'],['la posdata','das PS'],['adjuntar','anhängen'],['el teclado','die Tastatur'],['el ratón','die Maus'],['pulsar','drücken'],['pegar','einfügen; kleben'],['instalar','installieren'],['el navegador','der Browser'],['el buscador','die Suchmaschine'],['el antivirus','das Antivirenprogramm']]},
 {t:'vocab',title:'En el trabajo',items:[['el informe','der Bericht'],['el presupuesto','das Budget'],['el proyecto','das Projekt'],['el pedido','die Bestellung'],['atender a un cliente','einen Kunden bedienen'],['el usuario / la usuaria','der Nutzer / die Nutzerin'],['la formación','die Ausbildung / Schulung'],['la experiencia','die Erfahrung'],['colaborar','zusammenarbeiten'],['el compromiso','die Verlobung; die Verpflichtung'],['el ayudante / la ayudante','der Assistent / die Assistentin'],['el / la sustituto/a','die Vertretung'],['el bufete','die Anwaltskanzlei'],['el laboratorio','das Labor'],['el almacén','das Lager'],['el taller','die Werkstatt']]},
 {t:'match',q:'Ordne zu.',pairs:[['adjuntar','anhängen'],['el teclado','die Tastatur'],['el informe','der Bericht'],['el almacén','das Lager'],['el saldo','das Guthaben']]},
 {t:'mc',q:'Indirekte Rede: „Mándame el informe.“ → Mi jefa me pide que …',opts:['le mande el informe.','le mando el informe.','me manda el informe.'],a:0},
 {t:'tr',de:'Sie hat mir gesagt, dass sie den Bericht angehängt hat.',a:['Me ha dicho que ha adjuntado el informe.','Me dijo que había adjuntado el informe.']}]});
P('u22',{id:'lx',title:'Vocabulario B1: compras, comida y ocio',desc:'Einkaufen, Lebensmittel, Hobbys',steps:[
 {t:'vocab',title:'De compras',items:[['las rebajas','der Schlussverkauf'],['el descuento','der Rabatt'],['la garantía','die Garantie'],['la devolución','die Rückgabe'],['el catálogo','der Katalog'],['cobrar','kassieren'],['el carrito','der Einkaufswagen'],['la cesta','der Korb'],['caducado / caducada','abgelaufen'],['congelado / congelada','tiefgekühlt'],['la loncha','die Scheibe (Wurst, Käse)'],['el trozo','das Stück'],['ancho / ancha','weit'],['estrecho / estrecha','eng'],['el tacón','der Absatz'],['la zapatilla','der Turnschuh, Hausschuh'],['coser','nähen']]},
 {t:'vocab',title:'Alimentos',items:[['el embutido','die Wurstwaren'],['el chorizo','die Paprikawurst'],['el lomo','die Lende'],['la pechuga','die Brust (Geflügel)'],['la chuleta','das Kotelett'],['la berenjena','die Aubergine'],['el calabacín','die Zucchini'],['las espinacas','der Spinat'],['los guisantes','die Erbsen'],['las lentejas','die Linsen'],['los garbanzos','die Kichererbsen'],['la cereza','die Kirsche'],['la piña','die Ananas'],['la nata','die Sahne'],['desnatado / desnatada','entrahmt (fettarm)'],['el vinagre','der Essig'],['la mostaza','der Senf'],['la yema','das Eigelb'],['la magdalena','die Muffin-Art (spanisch)'],['el gazpacho','die kalte Gemüsesuppe'],['la croqueta','die Krokette'],['la manzanilla','der Kamillentee'],['la resaca','der Kater (nach Alkohol)']]},
 {t:'vocab',title:'Ocio',items:[['coleccionar','sammeln'],['el crucigrama','das Kreuzworträtsel'],['el aficionado / la aficionada','der Fan / die Liebhaberin'],['el concurso','der Wettbewerb, die Quizshow'],['el videojuego','das Videospiel'],['la consola','die Spielkonsole'],['el juguete','das Spielzeug'],['la lotería','die Lotterie'],['inscribirse','sich anmelden'],['el picnic','das Picknick'],['el / la espectador/a','der Zuschauer / die Zuschauerin'],['el escenario','die Bühne']]},
 {t:'match',q:'Ordne zu.',pairs:[['las rebajas','der Schlussverkauf'],['caducado','abgelaufen'],['la nata','die Sahne'],['las lentejas','die Linsen'],['el crucigrama','das Kreuzworträtsel']]},
 {t:'gap',q:'Busco unos pantalones que no ___ (sein, Subjuntivo) tan estrechos.',a:['sean']},
 {t:'tr',de:'Dieser Joghurt ist abgelaufen.',a:['Este yogur está caducado.','Este yogur ha caducado.']}]});
P('u23',{id:'lx',title:'Vocabulario B1: naturaleza y ciencia',desc:'Natur, Tiere, Wetter, Landwirtschaft, Wissenschaft',steps:[
 {t:'vocab',title:'Naturaleza y clima',items:[['el océano','der Ozean'],['el continente','der Kontinent'],['la península','die Halbinsel'],['el valle','das Tal'],['la selva','der Dschungel'],['el hemisferio','die Erdhalbkugel'],['húmedo / húmeda','feucht'],['seco / seca','trocken'],['despejado','klar (Himmel)'],['nublado','bewölkt'],['el granizo','der Hagel'],['el huracán','der Hurrikan'],['el terremoto','das Erdbeben'],['la hierba','das Gras'],['la rama','der Ast'],['la raíz','die Wurzel'],['el tronco','der Baumstamm']]},
 {t:'vocab',title:'Animales',items:[['el insecto','das Insekt'],['el ave','der Vogel (allgemein)'],['el animal doméstico','das Haustier'],['el conejo','das Kaninchen'],['la oveja','das Schaf'],['la gallina','das Huhn'],['el león','der Löwe'],['el tigre','der Tiger'],['el elefante','der Elefant'],['la serpiente','die Schlange']]},
 {t:'vocab',title:'Campo, industria y reciclaje',items:[['la agricultura','die Landwirtschaft'],['la ganadería','die Viehzucht'],['el campesino / la campesina','der Bauer / die Bäuerin'],['el tractor','der Traktor'],['el huerto','der Gemüsegarten'],['el cultivo','der Anbau'],['la industria','die Industrie'],['el petróleo','das Erdöl'],['el carbón','die Kohle'],['el ladrillo','der Ziegelstein'],['el vidrio','das Glas (Material)'],['el cartón','die Pappe'],['la pila','die Batterie'],['la capa de ozono','die Ozonschicht'],['conservar','erhalten, bewahren']]},
 {t:'vocab',title:'Ciencia',items:[['la ecología','die Ökologie'],['la biología','die Biologie'],['la física','die Physik'],['la química','die Chemie'],['el descubrimiento','die Entdeckung'],['el experimento','das Experiment'],['el / la veterinario/a','der Tierarzt / die Tierärztin'],['el / la astronauta','der Astronaut / die Astronautin'],['el satélite','der Satellit'],['sólido / sólida','fest'],['líquido / líquida','flüssig']]},
 {t:'match',q:'Ordne zu.',pairs:[['el terremoto','das Erdbeben'],['la pila','die Batterie'],['el vidrio','das Glas (Material)'],['la oveja','das Schaf'],['nublado','bewölkt']]},
 {t:'gap',q:'Es importante que ___ (wir recyceln) el vidrio y las pilas.',a:['reciclemos']},
 {t:'tr',de:'Es ist schade, dass so viele Wälder verschwinden.',a:['Es una pena que desaparezcan tantos bosques.']}]});
P('u23',{id:'lz',icon:'🎯',title:'Prueba DELE B1',desc:'Übungstest im DELE-Format',steps:[
 {t:'info',title:'Das DELE B1',html:`<p>Beim <b>DELE B1</b> werden die Texte länger und du sollst Meinungen, Gründe und Erfahrungen ausdrücken:</p>
 <table><tr><th>Teil</th><th>Dauer</th><th>Aufgaben</th></tr>
 <tr><td>Comprensión de lectura</td><td>70 Min.</td><td>5 Tareas mit je 6 Fragen: kurze Texte zuordnen, Erfahrungsbericht, Lücken in einem Artikel, Anzeigen, Briefe</td></tr>
 <tr><td>Comprensión auditiva</td><td>40 Min.</td><td>5 Tareas mit je 6 Fragen: Nachrichten, Gespräche, Radio, Interviews</td></tr>
 <tr><td>Expresión e interacción escritas</td><td>60 Min.</td><td>eine E-Mail/ein Brief (ca. 100–120 Wörter) und ein Text, z. B. Blog oder Erfahrungsbericht (ca. 130–150 Wörter)</td></tr>
 <tr><td>Expresión e interacción orales</td><td>15 Min. + 15 Min. Vorbereitung</td><td>kurzer Vortrag, Gespräch darüber, Foto beschreiben, Rollenspiel</td></tr></table>
 <p>Bestanden mit je <b>30 von 50 Punkten</b> in Lesen + Schreiben und Hören + Sprechen.</p>`},
 {t:'mc',kind:'Lectura · Tarea 1',q:'Personas y anuncios – Irene: «Me gustaría hacer algo útil los fines de semana, por ejemplo ayudar a personas mayores.» ¿Qué anuncio le interesa? a) Asociación Vecinos Unidos busca voluntarios para acompañar a mayores del barrio los sábados. b) Gimnasio Activa: clases de yoga para mayores de 60. c) Residencia El Pinar busca enfermero/a con experiencia, jornada completa.',opts:['a','b','c'],a:0},
 {t:'mc',kind:'Lectura · Tarea 1',q:'Personas y anuncios – Óscar: «Quiero mejorar mi inglés, pero no tengo dinero para clases.» a) Academia Speak Up: cursos intensivos, 300 € al mes. b) Intercambio de idiomas en la biblioteca: cada jueves, gratis, español–inglés. c) Viajes de estudios a Londres para estudiantes de bachillerato.',opts:['b','a','c'],a:0},
 {t:'read',kind:'Lectura · Tarea 2',title:'Mi año en Valparaíso',text:`Cuando terminé la carrera, decidí pasar un año en Chile antes de buscar trabajo. Al principio mis padres no estaban muy convencidos, pero al final me apoyaron. Llegué a Valparaíso en marzo, sin conocer a nadie, y los primeros días fueron duros: el acento chileno me parecía rapidísimo y no entendía la mitad de las cosas. Sin embargo, encontré trabajo como profesora de alemán en un instituto y poco a poco hice amigos. Lo que más me sorprendió fue la amabilidad de la gente: mis vecinos me invitaban a comer los domingos y me enseñaron a cocinar empanadas. Si tuviera que repetir la experiencia, lo haría sin dudarlo, aunque quizá elegiría otra época del año, porque el invierno allí es muy húmedo.`,de:`Als ich mein Studium beendet hatte, beschloss ich, ein Jahr in Chile zu verbringen, bevor ich mir Arbeit suche. Anfangs waren meine Eltern nicht sehr überzeugt, aber am Ende haben sie mich unterstützt. Ich kam im März in Valparaíso an, ohne jemanden zu kennen, und die ersten Tage waren hart: Der chilenische Akzent kam mir superschnell vor und ich verstand die Hälfte nicht. Trotzdem fand ich eine Stelle als Deutschlehrerin an einer Schule und fand nach und nach Freunde. Am meisten überraschte mich die Freundlichkeit der Leute: Meine Nachbarn luden mich sonntags zum Essen ein und brachten mir bei, Empanadas zu machen. Wenn ich die Erfahrung wiederholen müsste, würde ich es ohne zu zögern tun, auch wenn ich vielleicht eine andere Jahreszeit wählen würde, denn der Winter dort ist sehr feucht.`},
 {t:'mc',kind:'Lectura · Tarea 2',q:'Al principio, los padres de la autora …',opts:['no estaban seguros de que fuera buena idea.','le pagaron el viaje.','vivían en Chile.'],a:0},
 {t:'mc',kind:'Lectura · Tarea 2',q:'¿Qué fue lo más difícil al llegar?',opts:['entender el acento','encontrar trabajo','cocinar'],a:0},
 {t:'mc',kind:'Lectura · Tarea 2',q:'¿Qué cambiaría si repitiera la experiencia?',opts:['la época del año','la ciudad','el trabajo'],a:0},
 {t:'gap',kind:'Lectura · Tarea 3',q:'Artículo: Cada vez más jóvenes deciden compartir piso, no solo por motivos económicos, ___ (sondern auch) porque prefieren no vivir solos. ___ (Allerdings) la convivencia no siempre es fácil.',a:['sino también','Sin embargo|No obstante']},
 {t:'mc',kind:'Lectura · Tarea 4',q:'Carta de reclamación: «Les escribo porque el pasado 3 de mayo compré en su tienda online una cafetera que llegó rota. Llamé dos veces al servicio de atención al cliente, pero nadie me ha dado una solución.» – ¿Qué quiere probablemente la persona?',opts:['que le cambien la cafetera o le devuelvan el dinero','comprar otra cafetera más cara','trabajar en atención al cliente'],a:0},
 {t:'mc',kind:'Lectura · Tarea 5',q:'Elige la opción correcta: Me alegro de que ___ venir a la fiesta.',opts:['puedas','puedes','podrás'],a:0,why:'<i>alegrarse de que</i> + Subjuntivo.'},
 {t:'mc',kind:'Lectura · Tarea 5',q:'Elige la opción correcta: Cuando ___ a Madrid, te llamaré.',opts:['llegue','llegaré','llego'],a:0,why:'<i>cuando</i> mit Zukunftsbezug + Subjuntivo.'},
 {t:'read',hideText:true,kind:'Comprensión auditiva · Tarea 1',title:'Mensaje en el contestador',intro:'Escucha el mensaje.',text:`Hola, Jonas, soy Lucía. Te llamo porque al final no podemos quedar el viernes: me han cambiado el turno en el trabajo. ¿Qué te parece el sábado por la mañana? Podríamos ir al mercado de San Antonio y luego tomar algo. Si no te va bien, mándame un mensaje y lo dejamos para la semana que viene. ¡Un beso!`,de:`Hallo Jonas, hier ist Lucía. Ich rufe an, weil wir uns am Freitag doch nicht treffen können: Man hat mir die Schicht bei der Arbeit geändert. Wie wäre es mit Samstagvormittag? Wir könnten auf den Markt von Sant Antoni gehen und danach etwas trinken. Wenn es dir nicht passt, schick mir eine Nachricht und wir verschieben es auf nächste Woche. Kuss!`},
 {t:'mc',kind:'Comprensión auditiva · Tarea 1',q:'¿Por qué no pueden quedar el viernes?',opts:['Lucía tiene otro turno de trabajo.','Jonas está enfermo.','El mercado está cerrado.'],a:0},
 {t:'read',hideText:true,kind:'Comprensión auditiva · Tarea 2',title:'Entrevista en la radio',intro:'Escucha la entrevista con una cocinera.',text:`– Marta, usted abrió su restaurante hace cinco años. ¿Cómo empezó todo? – Pues, la verdad, por casualidad. Yo trabajaba en una oficina y cocinaba solo para mis amigos. Un día un amigo me propuso participar en un concurso de cocina de la tele, y gané. Con el premio y un préstamo del banco abrí el restaurante. – ¿Y qué es lo más difícil? – Sin duda, los horarios. Trabajo casi todos los fines de semana y apenas veo a mi familia. Pero no lo cambiaría por nada.`,de:`– Marta, Sie haben Ihr Restaurant vor fünf Jahren eröffnet. Wie hat alles angefangen? – Ehrlich gesagt, durch Zufall. Ich arbeitete in einem Büro und kochte nur für meine Freunde. Eines Tages schlug mir ein Freund vor, bei einem Kochwettbewerb im Fernsehen mitzumachen, und ich gewann. Mit dem Preisgeld und einem Bankkredit eröffnete ich das Restaurant. – Und was ist das Schwierigste? – Ohne Zweifel die Arbeitszeiten. Ich arbeite fast jedes Wochenende und sehe meine Familie kaum. Aber ich würde es gegen nichts eintauschen.`},
 {t:'mc',kind:'Comprensión auditiva · Tarea 2',q:'¿Cómo consiguió Marta el dinero para el restaurante?',opts:['con un premio y un préstamo','vendiendo su piso','gracias a su familia'],a:0},
 {t:'mc',kind:'Comprensión auditiva · Tarea 2',q:'Para Marta, lo más difícil es …',opts:['el horario de trabajo','encontrar cocineros','la competencia'],a:0},
 {t:'read',hideText:true,kind:'Comprensión auditiva · Tarea 3',title:'Noticia',intro:'Escucha la noticia.',text:`El Ayuntamiento de Barcelona ha anunciado que a partir de septiembre el transporte público será gratuito para los menores de dieciséis años. La medida quiere reducir el uso del coche y la contaminación en la ciudad. Según el alcalde, también se ampliarán los carriles bici en los barrios del norte.`,de:`Das Rathaus von Barcelona hat angekündigt, dass der öffentliche Nahverkehr ab September für unter Sechzehnjährige kostenlos sein wird. Die Maßnahme soll die Autonutzung und die Luftverschmutzung in der Stadt verringern. Laut dem Bürgermeister werden außerdem die Radwege in den nördlichen Vierteln ausgebaut.`},
 {t:'mc',kind:'Comprensión auditiva · Tarea 3',q:'¿Qué cambiará en septiembre?',opts:['Los jóvenes no pagarán el transporte público.','Se prohibirán los coches.','El metro funcionará toda la noche.'],a:0},
 {t:'free',kind:'Expresión escrita · Tarea 1',task:'Una amiga española te escribe: quiere estudiar un semestre en Alemania y te pide consejo. Contéstale (100–120 palabras): salúdala, recomiéndale una ciudad y explica por qué, dale dos consejos prácticos (alojamiento, idioma, dinero…) y despídete.',hint:'¡Hola, …! Qué bien que … Te recomiendo que vayas a … porque … Además, es importante que … Yo en tu lugar … Un abrazo, …',focus:'Ratschläge mit Subjuntivo (te recomiendo que, es importante que), Konditional (yo en tu lugar …), Konnektoren',model:'¡Hola, Clara!\n¡Qué bien que quieras estudiar en Alemania! Te recomiendo que vayas a Heidelberg: es una ciudad universitaria muy bonita, no es demasiado grande y hay muchos estudiantes internacionales. Además, está cerca de Fráncfort, así que es fácil viajar. Es importante que busques alojamiento pronto, porque las habitaciones en pisos compartidos vuelan. Yo en tu lugar haría un curso de alemán antes de ir, aunque en la universidad mucha gente habla inglés. Y abre una cuenta en un banco alemán: muchas tiendas pequeñas solo aceptan efectivo o tarjeta de débito.\n¡Ya me contarás!\nUn abrazo,\nJonas'},
 {t:'free',kind:'Expresión escrita · Tarea 2',task:'Escribe una entrada de blog (130–150 palabras): «Un día que cambió mi vida». Cuenta qué pasó, dónde estabas, cómo te sentiste y qué aprendiste.',hint:'Hace … años … Estaba … cuando … Al principio me sentí … Ese día aprendí que … Desde entonces …',focus:'Vergangenheitszeiten (Indefinido, Imperfecto, Pluscuamperfecto), Gefühle, Konnektoren',model:'Hace tres años, cuando todavía vivía en Alemania, decidí presentarme a una beca para estudiar en Barcelona. No había salido nunca de casa más de dos semanas y tenía muchos nervios. El día que recibí el correo con la respuesta estaba en el tren. Al principio no me lo podía creer: ¡me la habían dado! Me sentí feliz, pero también tenía un poco de miedo, porque sabía que todo iba a cambiar. Los primeros meses en Barcelona fueron difíciles: no entendía a la gente cuando hablaba rápido y echaba de menos a mi familia. Sin embargo, poco a poco hice amigos y empecé a sentirme en casa. Ese día aprendí que a veces hay que arriesgarse. Desde entonces intento decir que sí a las oportunidades, aunque me den miedo.'},
 {t:'free',kind:'Expresión oral · Tarea 1-2',task:'Presentación (2–3 minutos) + conversación: «El teletrabajo». Was sind Vor- und Nachteile? Was ist deine eigene Erfahrung? Wie wird es in Zukunft sein? Bereite auch Antworten auf Rückfragen vor (z. B. ¿Trabajarías siempre desde casa?).',hint:'Por un lado … Por otro lado … En mi caso … Creo que en el futuro … No creo que …',focus:'Meinung (creo que / no creo que + Subj.), Konnektoren, Futur, Konditional',model:'Voy a hablar del teletrabajo. Por un lado, tiene muchas ventajas: no pierdes tiempo en el transporte y puedes organizar mejor tu día. Por otro lado, a veces te sientes solo y es difícil separar el trabajo de la vida privada. En mi caso, trabajo dos días desde casa y tres en la oficina, y me parece la mejor solución. Creo que en el futuro casi todas las empresas tendrán un modelo mixto, pero no creo que la oficina desaparezca, porque necesitamos el contacto con los compañeros.'},
 {t:'free',kind:'Expresión oral · Tarea 3',task:'Descripción de una fotografía: 📷 Eine Familie (Eltern, zwei Kinder, Großmutter) sitzt an einem langen Tisch im Freien, es gibt Paella, alle lachen, im Hintergrund ein Garten. Beschreibe das Foto und sag, was du denkst: Was feiern sie? Wie fühlen sie sich? Erinnert es dich an etwas?',hint:'En la foto se ve … Parece que … Seguramente están celebrando … Me recuerda a …',focus:'parecer, seguramente/quizá, estar + Gerundium, Erinnerungen (me recuerda a)',model:'En la foto se ve a una familia comiendo al aire libre. Hay unos padres, dos niños y una señora mayor, que seguramente es la abuela. En el centro de la mesa hay una paella enorme. Parece que están celebrando algo, quizá un cumpleaños, porque todos están riéndose. Detrás hay un jardín con árboles. Me recuerda a las comidas de los domingos en casa de mis abuelos.'},
 {t:'dialog',kind:'Expresión oral · Tarea 4',place:'Agencia de viajes',title:'Situación simulada: reclamar un viaje',scene:'Du hast eine Reise gebucht, aber das Hotel war ganz anders als im Katalog. Der Prüfer spielt den Angestellten.',lines:[
  {n:'Empleado',es:'Buenos días, ¿en qué puedo ayudarle?',de:'Guten Tag, wie kann ich Ihnen helfen?'},
  {you:true,opts:[{es:'Buenos días. Vengo a hacer una reclamación: el hotel no era como en el catálogo.',ok:true},{es:'Buenos días. Quiero que me reservas un hotel.',ok:false,why:'Du willst dich beschweren. (Und nach <i>quiero que</i> steht der Subjuntivo: <i>reserve</i>.)'}]},
  {n:'Empleado',es:'Vaya, lo siento. ¿Qué problema hubo exactamente?',de:'Oh, das tut mir leid. Was genau war das Problem?'},
  {you:true,opts:[{es:'La habitación no tenía vistas al mar y la piscina estaba cerrada toda la semana.',ok:true},{es:'La habitación no tiene vistas al mar y la piscina está cerrada mañana.',ok:false,why:'Die Reise ist vorbei: beschreibe im Imperfecto (<i>tenía, estaba</i>).'}]},
  {n:'Empleado',es:'Entiendo. ¿Qué solución le parecería justa?',de:'Verstehe. Welche Lösung fänden Sie gerecht?'},
  {you:true,opts:[{es:'Me gustaría que me devolvieran una parte del dinero.',ok:true},{es:'Me gusta que me devuelven el dinero.',ok:false,why:'Höflicher Wunsch: <i>me gustaría que</i> + Subjuntivo Imperfecto (<i>devolvieran</i>).'}]}]},
 {t:'info',title:'¡Enhorabuena! 🎉',html:`<p>Damit hast du alle Teile des <b>DELE B1</b> geübt. Das B1 ist oft das Niveau, das Unis und Arbeitgeber verlangen – Termine unter <span class="es-t">examenes.cervantes.es</span>.</p>`}]});
})();
