/* Vocabulario B2 – zusätzliche Pflichtlektionen am Ende der Unidad (für Lernende, die schon weiter sind, erscheinen sie unter „Nachholen“).
   Schließen die Lücken zur B2-Liste des Plan Curricular (Instituto Cervantes, „Nociones específicas B2“), passend zum Thema der Unidad. */
(function(){
function P(uid,l){var u=COURSE.units.filter(function(x){return x.id===uid;})[0];if(u)u.lessons.push(l);}
P('u24',{id:'lx',title:'Vocabulario B2: dinero, consumo y vivienda',desc:'Finanzen, Steuern, Wohnen, Haushalt',steps:[
 {t:'vocab',title:'Dinero y economía',items:[['Hacienda','das Finanzamt'],['la declaración de la renta','die Steuererklärung'],['la financiación','die Finanzierung'],['la nómina','die Gehaltsabrechnung'],['el anticipo','der Vorschuss'],['la prestación','die (Sozial-)Leistung'],['el subsidio','die Unterstützung (staatlich)'],['gratis','gratis, kostenlos'],['la tarjeta de fidelidad','die Kundenkarte'],['la comercialización','die Vermarktung'],['la promoción','die Werbeaktion'],['la propaganda','die Werbung, Propaganda'],['el lanzamiento','die Markteinführung'],['el contrarreembolso','die Nachnahme'],['el repartidor / la repartidora','der Lieferant / die Lieferantin']]},
 {t:'vocab',title:'Vivienda',items:[['inmobiliario / inmobiliaria','Immobilien-'],['la constructora','das Bauunternehmen'],['trasladarse','umziehen (beruflich)'],['el ático','die Dachwohnung, das Penthouse'],['la buhardilla','die Mansarde'],['el administrador de fincas','der Hausverwalter'],['acogedor / acogedora','gemütlich, einladend'],['lujoso / lujosa','luxuriös'],['espacioso / espaciosa','geräumig'],['la fontanería','die Klempnerei, Sanitärinstallation'],['la carpintería','die Schreinerei'],['la urbanización','die Wohnsiedlung'],['el vecindario','die Nachbarschaft'],['ajardinado / ajardinada','begrünt, mit Gärten']]},
 {t:'vocab',title:'Tareas domésticas',items:[['la limpieza','die Reinigung, Sauberkeit'],['la escoba','der Besen'],['la fregona','der Wischmopp'],['el trapo','der Lappen'],['el detergente','das Waschmittel, Spülmittel'],['el suavizante','der Weichspüler'],['la suciedad','der Schmutz'],['el adorno','die Dekoration'],['cálido / cálida','warm, gemütlich'],['tenue','gedämpft (Licht)']]},
 {t:'match',q:'Ordne zu.',pairs:[['Hacienda','das Finanzamt'],['la nómina','die Gehaltsabrechnung'],['el ático','die Dachwohnung, das Penthouse'],['la fregona','der Wischmopp'],['espacioso','geräumig']]},
 {t:'gap',q:'Si ganara más, me ___ (comprar) un ático espacioso en el centro.',a:['compraría']},
 {t:'tr',de:'Wenn ich im Lotto gewinnen würde, würde ich keine Steuererklärung mehr machen.',a:['Si me tocara la lotería, no haría más la declaración de la renta.','Si ganara la lotería, no haría más la declaración de la renta.','Si me tocara la lotería, ya no haría la declaración de la renta.']}]});
P('u25',{id:'lx',title:'Vocabulario B2: trabajo y empresa',desc:'Verträge, Arbeitszeit, Qualifikation, Industrie',steps:[
 {t:'vocab',title:'Contrato y condiciones',items:[['contratado / contratada','angestellt'],['interino / interina','befristet (vertretungsweise)'],['el contrato indefinido','der unbefristete Vertrag'],['el contrato temporal','der befristete Vertrag'],['el / la directivo/a','die Führungskraft'],['el / la desempleado/a','der / die Arbeitslose'],['la cláusula','die Klausel'],['la cotización','der Sozialversicherungsbeitrag'],['la jubilación anticipada','der Vorruhestand'],['el día laborable','der Werktag'],['el día festivo','der Feiertag'],['reivindicar','fordern, einfordern'],['la referencia','die Referenz']]},
 {t:'vocab',title:'Cualidades profesionales',items:[['cualificado / cualificada','qualifiziert'],['especializado / especializada','spezialisiert'],['manual','handwerklich, manuell'],['intelectual','geistig'],['competente','kompetent'],['capaz','fähig'],['incapaz','unfähig'],['perezoso / perezosa','faul'],['la profesionalidad','die Professionalität'],['la función','die Aufgabe, Funktion'],['redactar','verfassen'],['distribuir','verteilen, vertreiben']]},
 {t:'vocab',title:'Industria',items:[['la fabricación','die Herstellung'],['la gestión','die Verwaltung, das Management'],['la revolución industrial','die industrielle Revolution'],['el sector textil','die Textilbranche'],['la industria siderúrgica','die Stahlindustrie'],['el aparejador / la aparejadora','der Bauleiter / die Bauleiterin'],['el barco pesquero','das Fischerboot']]},
 {t:'match',q:'Ordne zu.',pairs:[['el contrato indefinido','der unbefristete Vertrag'],['el día festivo','der Feiertag'],['redactar','verfassen'],['perezoso','faul'],['la gestión','die Verwaltung, das Management']]},
 {t:'gap',q:'Mi jefa quería que ___ (yo, redactar) el informe antes del viernes.',a:['redactara|redactase']},
 {t:'tr',de:'Sie haben mir einen unbefristeten Vertrag angeboten.',a:['Me han ofrecido un contrato indefinido.','Me ofrecieron un contrato indefinido.']}]});
P('u26',{id:'lx',title:'Vocabulario B2: cuerpo y salud',desc:'Körper, Krankheiten, Behandlung, Körperpflege',steps:[
 {t:'vocab',title:'El cuerpo',items:[['la frente','die Stirn'],['la mejilla','die Wange'],['la barbilla','das Kinn'],['la ceja','die Augenbraue'],['la pestaña','die Wimper'],['la uña','der Nagel'],['el hígado','die Leber'],['el riñón','die Niere'],['el intestino','der Darm'],['el esqueleto','das Skelett'],['la columna vertebral','die Wirbelsäule'],['la articulación','das Gelenk'],['la arteria','die Arterie'],['el tendón','die Sehne'],['la saliva','der Speichel'],['el sudor','der Schweiß'],['la arruga','die Falte'],['la cicatriz','die Narbe'],['la estatura','die Körpergröße'],['sordo / sorda','taub'],['mudo / muda','stumm']]},
 {t:'vocab',title:'Enfermedades y síntomas',items:[['el diagnóstico','die Diagnose'],['diagnosticar','diagnostizieren'],['padecer','leiden an'],['la diabetes','die Diabetes'],['la bronquitis','die Bronchitis'],['la depresión','die Depression'],['la tensión alta','der Bluthochdruck'],['el colesterol','das Cholesterin'],['el infarto','der Herzinfarkt'],['la ansiedad','die Angst(störung)'],['el catarro','die Erkältung'],['contagioso / contagiosa','ansteckend'],['contagiar','anstecken'],['hereditario / hereditaria','erblich'],['leve','leicht (Krankheit)'],['el desmayo','die Ohnmacht'],['la náusea','die Übelkeit'],['el escalofrío','der Schüttelfrost'],['el malestar','das Unwohlsein'],['el cansancio','die Müdigkeit'],['la debilidad','die Schwäche'],['alérgico / alérgica','allergisch']]},
 {t:'vocab',title:'Tratamiento',items:[['el / la especialista','der Facharzt / die Fachärztin'],['el ambulatorio','das Ärztezentrum'],['el / la pediatra','der Kinderarzt / die Kinderärztin'],['el traumatólogo / la traumatóloga','der Orthopäde / die Orthopädin'],['hospitalizar','ins Krankenhaus einweisen'],['la inyección','die Spritze'],['la pomada','die Salbe'],['el calmante','das Beruhigungs-/Schmerzmittel'],['el analgésico','das Schmerzmittel'],['el prospecto','der Beipackzettel'],['la dosis','die Dosis'],['la ecografía','der Ultraschall'],['la escayola','der Gips'],['el empaste','die Zahnfüllung'],['el botiquín','der Verbandskasten'],['la camilla','die Trage, Liege'],['perjudicial','schädlich'],['beneficioso / beneficiosa','nützlich, gesund']]},
 {t:'vocab',title:'Cuidado personal',items:[['el maquillaje','das Make-up'],['el rímel','die Wimperntusche'],['la laca','das Haarspray'],['el masaje','die Massage'],['la sauna','die Sauna'],['el balneario','das Kurbad, Thermalbad'],['la crema hidratante','die Feuchtigkeitscreme'],['graso / grasa','fettig'],['la mancha','der Fleck'],['recortar','nachschneiden, kürzen']]},
 {t:'match',q:'Ordne zu.',pairs:[['la ceja','die Augenbraue'],['el riñón','die Niere'],['contagioso','ansteckend'],['el prospecto','der Beipackzettel'],['la pomada','die Salbe']]},
 {t:'gap',q:'Aunque el catarro ___ (ser) leve, es mejor que te quedes en casa.',a:['sea']},
 {t:'tr',de:'Obwohl ich wenig schlafe, bin ich nicht müde.',a:['Aunque duermo poco, no estoy cansado.','Aunque duermo poco, no estoy cansada.','A pesar de que duermo poco, no estoy cansado.','A pesar de que duermo poco, no estoy cansada.']}]});
P('u27',{id:'lx',title:'Vocabulario B2: política, justicia y medios',desc:'Wahlen, Justiz, Kriminalität, Presse',steps:[
 {t:'vocab',title:'Política',items:[['el diputado / la diputada','der / die Abgeordnete'],['el / la diplomático/a','der Diplomat / die Diplomatin'],['el dictador / la dictadora','der Diktator / die Diktatorin'],['el / la votante','der Wähler / die Wählerin'],['el referéndum','das Referendum'],['la urna','die Wahlurne'],['la abstención','die Wahlenthaltung'],['convocar elecciones','Wahlen ansetzen'],['autonómico / autonómica','regional (autonome Region)'],['municipal','kommunal, städtisch'],['constitucional','verfassungsmäßig'],['estatal','staatlich'],['legislativo / legislativa','gesetzgebend'],['nacionalista','nationalistisch'],['progresista','fortschrittlich'],['totalitario / totalitaria','totalitär']]},
 {t:'vocab',title:'Justicia y delito',items:[['judicial','gerichtlich'],['el tribunal','das Gericht'],['penal','Straf-'],['el / la testigo','der Zeuge / die Zeugin'],['el acusado / la acusada','der / die Angeklagte'],['el defensor / la defensora','der Verteidiger / die Verteidigerin'],['el / la delincuente','der / die Kriminelle'],['el delito','die Straftat'],['la denuncia','die Anzeige'],['denunciar','anzeigen'],['interrogar','verhören'],['la coartada','das Alibi'],['la vigilancia','die Überwachung'],['el inspector / la inspectora','der Inspektor / die Inspektorin'],['el / la agente','der / die Polizist(in)'],['la falsificación','die Fälschung'],['la agresión','der Angriff'],['la mafia','die Mafia'],['la droga','die Droge']]},
 {t:'vocab',title:'Medios',items:[['el dato','die Angabe, das Datum'],['fiable','zuverlässig'],['la actualidad','das Zeitgeschehen'],['la censura','die Zensur'],['el / la corresponsal','der Korrespondent / die Korrespondentin'],['el redactor / la redactora','der Redakteur / die Redakteurin'],['la edición','die Ausgabe'],['suscribirse','abonnieren'],['el / la oyente','der Hörer / die Hörerin'],['el / la telespectador/a','der Fernsehzuschauer / die Fernsehzuschauerin'],['el reportero / la reportera','der Reporter / die Reporterin'],['zapear','zappen'],['la crítica','die Kritik'],['confidencial','vertraulich']]},
 {t:'match',q:'Ordne zu.',pairs:[['la urna','die Wahlurne'],['el / la testigo','der Zeuge / die Zeugin'],['la coartada','das Alibi'],['la censura','die Zensur'],['zapear','zappen']]},
 {t:'gap',q:'El acusado fue ___ (interrogar) por la policía durante tres horas.',a:['interrogado']},
 {t:'tr',de:'Es wird gesagt, dass die Wahlen im Mai angesetzt werden.',a:['Se dice que las elecciones se convocarán en mayo.','Se dice que convocarán las elecciones en mayo.','Dicen que las elecciones se convocarán en mayo.']}]});
P('u28',{id:'lx',title:'Vocabulario B2: familia, relaciones y fiestas',desc:'Verwandtschaft, Beziehungen, Feiern',steps:[
 {t:'vocab',title:'Familia',items:[['el / la cónyuge','der Ehepartner / die Ehepartnerin'],['el cuñado / la cuñada','der Schwager / die Schwägerin'],['el suegro / la suegra','der Schwiegervater / die Schwiegermutter'],['el yerno','der Schwiegersohn'],['la nuera','die Schwiegertochter'],['el bisabuelo / la bisabuela','der Urgroßvater / die Urgroßmutter'],['los mellizos','die (zweieiigen) Zwillinge'],['adoptivo / adoptiva','Adoptiv-'],['el huérfano / la huérfana','die Waise'],['heredar','erben'],['el testamento','das Testament'],['la maternidad','die Mutterschaft'],['la paternidad','die Vaterschaft']]},
 {t:'vocab',title:'Relaciones',items:[['íntimo / íntima','eng, vertraut'],['amistoso / amistosa','freundschaftlich'],['amoroso / amorosa','Liebes-, liebevoll'],['el / la amante','der Geliebte / die Geliebte'],['el prometido / la prometida','der Verlobte / die Verlobte'],['seducir','verführen'],['relacionarse','Kontakte pflegen'],['reñir','streiten, schimpfen'],['afectuoso / afectuosa','herzlich, liebevoll'],['cordial','herzlich, freundlich'],['caluroso / calurosa','herzlich (Empfang)'],['la comprensión','das Verständnis'],['injusto / injusta','ungerecht'],['prudente','vorsichtig, besonnen'],['la imprudencia','die Unvorsichtigkeit']]},
 {t:'vocab',title:'Celebraciones',items:[['el bautizo','die Taufe'],['el banquete','das Festessen'],['la celebración','die Feier'],['solemne','feierlich'],['el funeral','die Trauerfeier'],['conmemorar','gedenken'],['brindar','anstoßen'],['el brindis','der Trinkspruch'],['desenvolver','auspacken'],['el desfile','der Umzug, die Parade'],['la juerga','die Party, das Feiern']]},
 {t:'match',q:'Ordne zu.',pairs:[['el yerno','der Schwiegersohn'],['heredar','erben'],['el bautizo','die Taufe'],['brindar','anstoßen'],['reñir','streiten, schimpfen']]},
 {t:'gap',q:'Si mi cuñado no ___ (beber, Pluscuamp. Subj.) tanto, no habría reñido con mi hermana.',a:['hubiera bebido|hubiese bebido']},
 {t:'tr',de:'Wenn ich es gewusst hätte, wäre ich zur Taufe gekommen.',a:['Si lo hubiera sabido, habría venido al bautizo.','Si lo hubiese sabido, habría venido al bautizo.','Si lo hubiera sabido, hubiera venido al bautizo.']}]});
P('u29',{id:'lx',title:'Vocabulario B2: compras y viajes',desc:'Geschäft, Kleidung, Essen, Reisen & Verkehr',steps:[
 {t:'vocab',title:'Comercio y ropa',items:[['el establecimiento','das Geschäft, die Einrichtung'],['la mercancía','die Ware'],['la clientela','die Kundschaft'],['la etiqueta','das Etikett'],['el escaparate','das Schaufenster'],['el complemento','das Accessoire'],['el conjunto','das Outfit, Ensemble'],['el albornoz','der Bademantel'],['el camisón','das Nachthemd'],['el hilo','der Faden'],['la cremallera','der Reißverschluss'],['la percha','der Kleiderbügel'],['estampado / estampada','gemustert'],['arrugado / arrugada','zerknittert'],['encoger','einlaufen (Kleidung)'],['la tintorería','die Reinigung'],['ajustado / ajustada','eng anliegend'],['flojo / floja','locker, schlaff']]},
 {t:'vocab',title:'Comer y beber',items:[['sabroso / sabrosa','schmackhaft'],['exquisito / exquisita','köstlich'],['comestible','essbar'],['podrido / podrida','verfault'],['el apetito','der Appetit'],['la digestión','die Verdauung'],['el refresco','das Erfrischungsgetränk'],['el licor','der Likör'],['el agua del grifo','das Leitungswasser'],['el sacacorchos','der Korkenzieher'],['el abrelatas','der Dosenöffner'],['las almejas','die Venusmuscheln'],['los mejillones','die Miesmuscheln'],['los langostinos','die Garnelen (groß)'],['el bacalao','der Kabeljau, Stockfisch'],['las legumbres','die Hülsenfrüchte'],['las almendras','die Mandeln'],['las nueces','die Walnüsse'],['la harina','das Mehl'],['la levadura','die Hefe'],['integral','Vollkorn-'],['a la brasa','gegrillt (über Glut)'],['rallar','reiben'],['trocear','in Stücke schneiden'],['rebozar','panieren'],['el autoservicio','die Selbstbedienung'],['tapear','Tapas essen gehen']]},
 {t:'vocab',title:'Viajes y tráfico',items:[['el itinerario','die Reiseroute'],['el trayecto','die Strecke'],['atravesar','durchqueren'],['anular','stornieren'],['extraviar','verlieren (Gepäck)'],['el callejero','der Stadtplan'],['la clase preferente','die Business-Klasse'],['el vestíbulo','die Eingangshalle'],['acampar','zelten'],['la autovía','die Schnellstraße'],['el peaje','die Maut'],['la curva','die Kurve'],['la rotonda','der Kreisverkehr'],['el bache','das Schlagloch'],['la aduana','der Zoll'],['el pasajero / la pasajera','der / die Reisende'],['el vagón','der Waggon'],['arrancar','anfahren, starten'],['acelerar','beschleunigen'],['frenar','bremsen'],['el intermitente','der Blinker'],['el claxon','die Hupe'],['ceder el paso','Vorfahrt gewähren'],['el pinchazo','die Reifenpanne'],['la grúa','der Abschleppwagen; der Kran'],['la pieza de repuesto','das Ersatzteil'],['la reparación','die Reparatur']]},
 {t:'match',q:'Ordne zu.',pairs:[['la cremallera','der Reißverschluss'],['el peaje','die Maut'],['la rotonda','der Kreisverkehr'],['el sacacorchos','der Korkenzieher'],['frenar','bremsen']]},
 {t:'mc',q:'Formelle Beschwerde: „Me dirijo a ustedes para ___ el retraso de mi pedido.“',opts:['reclamar','tapear','acampar'],a:0},
 {t:'tr',de:'Ich möchte meine Reservierung stornieren.',a:['Quisiera anular mi reserva.','Me gustaría anular mi reserva.','Quiero anular mi reserva.']}]});
P('u30',{id:'lx',title:'Vocabulario B2: carácter, emociones y ocio',desc:'Charakter, Gefühle, Spiel & Sport, Freizeit',steps:[
 {t:'vocab',title:'Carácter',items:[['la ambición','der Ehrgeiz'],['ambicioso / ambiciosa','ehrgeizig'],['la arrogancia','die Arroganz'],['la constancia','die Beständigkeit'],['la cobardía','die Feigheit'],['la valentía','der Mut'],['el egoísmo','der Egoismus'],['la generosidad','die Großzügigkeit'],['la puntualidad','die Pünktlichkeit'],['la responsabilidad','die Verantwortung'],['la sinceridad','die Ehrlichkeit'],['la timidez','die Schüchternheit'],['la ternura','die Zärtlichkeit'],['callado / callada','schweigsam'],['discreto / discreta','diskret, zurückhaltend'],['tierno / tierna','zärtlich'],['apasionado / apasionada','leidenschaftlich'],['solidario / solidaria','solidarisch'],['brusco / brusca','schroff'],['acomplejado / acomplejada','mit Komplexen']]},
 {t:'vocab',title:'Emociones',items:[['la admiración','die Bewunderung'],['la angustia','die Angst, Beklemmung'],['el temor','die Furcht'],['la tristeza','die Traurigkeit'],['animado / animada','gut gelaunt, lebhaft'],['fascinado / fascinada','fasziniert'],['satisfecho / satisfecha','zufrieden'],['sorprendido / sorprendida','überrascht'],['apenado / apenada','betrübt'],['disgustado / disgustada','verstimmt'],['dolido / dolida','gekränkt'],['resignado / resignada','resigniert'],['furioso / furiosa','wütend'],['histérico / histérica','hysterisch'],['la ilusión','die Vorfreude, Hoffnung'],['detestar','verabscheuen']]},
 {t:'vocab',title:'Juegos y deporte',items:[['el pasatiempo','der Zeitvertreib'],['el parque temático','der Themenpark'],['entretener','unterhalten'],['el / la coleccionista','der Sammler / die Sammlerin'],['el rompecabezas','das Puzzle'],['barajar','mischen (Karten)'],['el turno','die Reihe (dran sein)'],['el azar','der Zufall'],['el columpio','die Schaukel'],['el tobogán','die Rutsche'],['el campeonato','die Meisterschaft'],['la liga','die Liga'],['el estadio','das Stadion'],['el empate','das Unentschieden'],['el triunfo','der Triumph'],['la competición','der Wettkampf'],['la lesión','die Verletzung'],['clasificarse','sich qualifizieren'],['la medalla','die Medaille'],['la taquilla','die Kasse (Kino/Theater)'],['la butaca','der Sitz (Kino/Theater)'],['el estreno','die Premiere'],['inaugurar','eröffnen']]},
 {t:'match',q:'Ordne zu.',pairs:[['la valentía','der Mut'],['la ilusión','die Vorfreude, Hoffnung'],['el estreno','die Premiere'],['el empate','das Unentschieden'],['callado','schweigsam']]},
 {t:'gap',q:'Cuando perdió la final, se ___ (ponerse) furioso.',a:['puso']},
 {t:'tr',de:'Er ist sehr ehrgeizig geworden.',a:['Se ha vuelto muy ambicioso.','Se volvió muy ambicioso.']}]});
P('u31',{id:'lx',title:'Vocabulario B2: educación, ciencia, sociedad y medio ambiente',desc:'Bildung, Wissenschaft, Gesellschaft, Kultur, Natur',steps:[
 {t:'vocab',title:'Educación',items:[['bilingüe','zweisprachig'],['laico / laica','konfessionslos'],['obligatorio / obligatoria','verpflichtend'],['optativo / optativa','wahlweise, Wahl-'],['la educación primaria','die Grundschulbildung'],['la educación secundaria','die Sekundarstufe'],['presencial','in Präsenz'],['virtual','online, virtuell'],['el expediente académico','das Notenblatt'],['el aprendizaje','das Lernen'],['memorizar','auswendig lernen'],['reflexionar','nachdenken'],['deducir','folgern'],['la evaluación','die Bewertung'],['examinarse','eine Prüfung ablegen'],['sobresaliente','sehr gut (Note)'],['notable','gut (Note)'],['la licenciatura','das Hochschulstudium (Abschluss)'],['la especialidad','das Fachgebiet'],['la filología','die Philologie'],['la síntesis','die Zusammenfassung, Synthese'],['el rotulador','der Filzstift'],['la grapadora','der Tacker'],['la diapositiva','die Folie']]},
 {t:'vocab',title:'Ciencia',items:[['la investigación','die Forschung'],['el investigador / la investigadora','der Forscher / die Forscherin'],['la hipótesis','die Hypothese'],['la molécula','das Molekül'],['la célula','die Zelle'],['genético / genética','genetisch'],['la estadística','die Statistik'],['el porcentaje','der Prozentsatz'],['la cifra','die Zahl, Ziffer'],['el ángulo','der Winkel'],['horizontal','waagerecht'],['vertical','senkrecht'],['el átomo','das Atom'],['el oxígeno','der Sauerstoff'],['el microscopio','das Mikroskop'],['la galaxia','die Galaxie'],['el eclipse','die Finsternis']]},
 {t:'vocab',title:'Sociedad y cultura',items:[['la discriminación','die Diskriminierung'],['la tolerancia','die Toleranz'],['la convivencia','das Zusammenleben'],['la cooperación','die Zusammenarbeit'],['la explotación','die Ausbeutung'],['la marginación','die Ausgrenzung'],['discapacitado / discapacitada','behindert'],['la minoría','die Minderheit'],['étnico / étnica','ethnisch'],['la creatividad','die Kreativität'],['la inspiración','die Inspiration'],['contemporáneo / contemporánea','zeitgenössisch'],['abstracto / abstracta','abstrakt'],['la fachada','die Fassade'],['el mármol','der Marmor'],['el óleo','das Ölgemälde'],['el relato','die Erzählung'],['el narrador / la narradora','der Erzähler / die Erzählerin'],['la tragedia','die Tragödie'],['el / la guionista','der Drehbuchautor / die Drehbuchautorin'],['el rodaje','die Dreharbeiten']]},
 {t:'vocab',title:'Naturaleza y medio ambiente',items:[['la cordillera','das Gebirge'],['la llanura','die Ebene'],['la cascada','der Wasserfall'],['la laguna','die Lagune, der kleine See'],['el golfo','der Golf'],['costero / costera','Küsten-'],['el trueno','der Donner'],['el relámpago','der Blitz'],['la nevada','der Schneefall'],['templado / templada','mild, gemäßigt'],['el mamífero','das Säugetier'],['el reptil','das Reptil'],['venenoso / venenosa','giftig'],['el arbusto','der Strauch'],['el ecosistema','das Ökosystem'],['la desertización','die Wüstenbildung'],['la catástrofe','die Katastrophe'],['el efecto invernadero','der Treibhauseffekt'],['la energía eólica','die Windenergie'],['radiactivo / radiactiva','radioaktiv'],['transgénico / transgénica','gentechnisch verändert'],['preservar','bewahren']]},
 {t:'match',q:'Ordne zu.',pairs:[['la investigación','die Forschung'],['la convivencia','das Zusammenleben'],['el trueno','der Donner'],['optativo','wahlweise, Wahl-'],['preservar','bewahren']]},
 {t:'mc',q:'Diskursmarker: „Los datos son claros; ___, el gobierno no ha hecho nada.“',opts:['no obstante','es decir','por ejemplo'],a:0},
 {t:'tr',de:'Es ist wahrscheinlich, dass der Treibhauseffekt mehr Katastrophen verursacht.',a:['Es probable que el efecto invernadero cause más catástrofes.','Es probable que el efecto invernadero provoque más catástrofes.']}]});
P('u31',{id:'lz',title:'Prueba DELE B2',desc:'Übungstest im DELE-Format',steps:[
 {t:'info',title:'Das DELE B2',html:`<p>Das <b>DELE B2</b> prüft, ob du dich sicher und differenziert ausdrücken kannst – auch zu abstrakten Themen:</p>
 <table><tr><th>Teil</th><th>Dauer</th><th>Aufgaben</th></tr>
 <tr><td>Comprensión de lectura</td><td>70 Min.</td><td>4 Tareas, 36 Fragen: längere Texte, Meinungsartikel, Lücken mit Sätzen, Grammatik im Kontext</td></tr>
 <tr><td>Comprensión auditiva</td><td>40 Min.</td><td>5 Tareas mit je 6 Fragen: Gespräche, Radiobeiträge, Vorträge, Interviews</td></tr>
 <tr><td>Expresión e interacción escritas</td><td>80 Min.</td><td>2 Texte: ein Brief/eine E-Mail zu einem gehörten Text und ein Meinungstext oder Bericht (je ca. 150–180 Wörter)</td></tr>
 <tr><td>Expresión e interacción orales</td><td>20 Min. + 20 Min. Vorbereitung</td><td>Vorschläge zu einem Problem bewerten, eine Situation auf einem Foto beschreiben, Umfragedaten kommentieren</td></tr></table>
 <p>Bestanden mit je <b>30 von 50 Punkten</b> in Lesen + Schreiben und Hören + Sprechen.</p>`},
 {t:'read',kind:'Lectura · Tarea 1',title:'La semana laboral de cuatro días',text:`Desde hace dos años, una empresa de software de Valencia trabaja solo cuatro días a la semana sin reducir los sueldos. Al principio, la dirección temía que la productividad bajara, pero los resultados han sorprendido incluso a los más escépticos: los proyectos se entregan a tiempo, las bajas por enfermedad han disminuido un treinta por ciento y apenas hay rotación de personal. «La gente llega descansada el lunes y se concentra más», explica la directora de recursos humanos.
No obstante, el modelo no está exento de dificultades. Los clientes esperan respuestas cinco días a la semana, por lo que la plantilla se organiza en turnos para que siempre haya alguien disponible. Además, algunos empleados reconocen que la presión durante los cuatro días es mayor. Los expertos coinciden en que la fórmula funciona mejor en sectores donde se mide el resultado y no las horas, y advierten de que no puede aplicarse sin más a hospitales o comercios.`,de:`Seit zwei Jahren arbeitet ein Softwareunternehmen in Valencia nur vier Tage pro Woche, ohne die Gehälter zu kürzen. Anfangs befürchtete die Geschäftsführung, dass die Produktivität sinken würde, aber die Ergebnisse haben selbst die größten Skeptiker überrascht: Die Projekte werden pünktlich abgeliefert, die Krankmeldungen sind um dreißig Prozent zurückgegangen und es gibt kaum Personalfluktuation. „Die Leute kommen am Montag ausgeruht und konzentrieren sich besser“, erklärt die Personalleiterin.
Allerdings ist das Modell nicht ohne Schwierigkeiten. Die Kunden erwarten an fünf Tagen pro Woche Antworten, deshalb organisiert sich die Belegschaft in Schichten, damit immer jemand erreichbar ist. Außerdem geben einige Mitarbeitende zu, dass der Druck an den vier Tagen größer ist. Fachleute sind sich einig, dass die Formel in Branchen am besten funktioniert, in denen das Ergebnis und nicht die Stunden gemessen wird, und warnen, dass sie sich nicht einfach auf Krankenhäuser oder den Handel übertragen lässt.`},
 {t:'mc',kind:'Lectura · Tarea 1',q:'Al principio, la dirección de la empresa …',opts:['tenía miedo de que se trabajara menos','quería bajar los sueldos','estaba convencida del éxito'],a:0},
 {t:'mc',kind:'Lectura · Tarea 1',q:'Según el texto, ¿cómo resuelven el problema de los clientes?',opts:['con turnos entre los empleados','contratando a más personal','abriendo solo cuatro días'],a:0},
 {t:'mc',kind:'Lectura · Tarea 1',q:'Los expertos opinan que el modelo …',opts:['no sirve igual para todos los sectores','debería ser obligatorio','solo funciona en hospitales'],a:0},
 {t:'mc',kind:'Lectura · Tarea 2',q:'Cuatro personas opinan sobre vivir en el campo. ¿Quién echa de menos la oferta cultural? A) «Desde que vivo en el pueblo duermo mejor y gasto menos.» B) «Lo único malo es que el cine más cercano está a cuarenta kilómetros y casi nunca hay conciertos.» C) «Teletrabajo, así que la distancia no me afecta.» D) «Mis hijos tienen más libertad aquí que en la ciudad.»',opts:['B','A','C','D'],a:0},
 {t:'mc',kind:'Lectura · Tarea 3',q:'Completa el texto con el fragmento adecuado: «Muchos jóvenes vuelven a casa de sus padres tras terminar la universidad. ______. Por eso, algunos ayuntamientos ofrecen alquileres más baratos para menores de treinta años.»',opts:['El precio de los pisos se ha disparado y los sueldos de los primeros empleos son bajos','Les encanta cocinar con sus padres los fines de semana','Las universidades han cerrado sus residencias de verano'],a:0},
 {t:'mc',kind:'Lectura · Tarea 4',q:'Elige la opción correcta: Si me lo ___ antes, habría podido ayudarte.',opts:['hubieras dicho','dijeras','habrías dicho'],a:0},
 {t:'mc',kind:'Lectura · Tarea 4',q:'Elige la opción correcta: Por mucho que ___, no conseguirás convencerle.',opts:['insistas','insistes','insistirás'],a:0},
 {t:'mc',kind:'Lectura · Tarea 4',q:'Elige la opción correcta: Se fue sin que nadie se ___ cuenta.',opts:['diera','dio','daba'],a:0},
 {t:'read',hideText:true,kind:'Comprensión auditiva · Tarea 1',title:'Conversación en una inmobiliaria',intro:'Escucha la conversación.',text:`– Buenos días, llamo por el ático de la calle Valencia. ¿Sigue disponible? – Sí, aunque ya hay dos personas interesadas. Son ochenta metros, muy luminoso, con terraza. – ¿Y el precio incluye los gastos de comunidad? – No, son unos sesenta euros aparte. Además, el propietario pide dos meses de fianza. – Vaya, es un poco más de lo que esperaba. ¿Se podría negociar? – Puedo preguntarle, pero no le prometo nada.`,de:`– Guten Tag, ich rufe wegen der Dachwohnung in der Calle Valencia an. Ist sie noch frei? – Ja, aber es gibt schon zwei Interessenten. Achtzig Quadratmeter, sehr hell, mit Terrasse. – Und sind die Nebenkosten im Preis inbegriffen? – Nein, das sind etwa sechzig Euro extra. Außerdem verlangt der Eigentümer zwei Monatsmieten Kaution. – Oh, das ist etwas mehr, als ich erwartet hatte. Könnte man verhandeln? – Ich kann ihn fragen, aber ich verspreche nichts.`},
 {t:'mc',kind:'Comprensión auditiva · Tarea 1',q:'¿Qué no está incluido en el precio?',opts:['los gastos de comunidad','la terraza','la fianza de un mes'],a:0},
 {t:'read',hideText:true,kind:'Comprensión auditiva · Tarea 2',title:'Entrevista a una investigadora',intro:'Escucha la entrevista.',text:`– Doctora Ruiz, su equipo ha estudiado el efecto de las pantallas en el sueño de los adolescentes. ¿Qué han descubierto? – Que el problema no es tanto la luz de la pantalla como el contenido. Un adolescente que ve un vídeo relajante se duerme casi igual que uno que lee un libro. Pero si está en redes sociales o jugando, el cerebro se activa y tarda mucho más en dormirse. – ¿Qué recomienda a las familias? – Más que prohibir, acordar normas: por ejemplo, dejar el móvil fuera del dormitorio una hora antes de acostarse.`,de:`– Frau Dr. Ruiz, Ihr Team hat untersucht, wie sich Bildschirme auf den Schlaf von Jugendlichen auswirken. Was haben Sie herausgefunden? – Dass das Problem weniger das Licht des Bildschirms ist als der Inhalt. Ein Jugendlicher, der ein entspannendes Video schaut, schläft fast genauso schnell ein wie einer, der ein Buch liest. Aber wenn er in sozialen Netzwerken ist oder spielt, wird das Gehirn aktiviert und er braucht viel länger zum Einschlafen. – Was empfehlen Sie den Familien? – Eher als zu verbieten, Regeln zu vereinbaren: zum Beispiel das Handy eine Stunde vor dem Schlafengehen außerhalb des Schlafzimmers zu lassen.`},
 {t:'mc',kind:'Comprensión auditiva · Tarea 2',q:'Según la investigadora, lo que más afecta al sueño es …',opts:['el contenido que se consume','la luz de la pantalla','leer libros'],a:0},
 {t:'mc',kind:'Comprensión auditiva · Tarea 2',q:'¿Qué aconseja a las familias?',opts:['acordar normas en lugar de prohibir','quitar el móvil a los hijos','comprar libros electrónicos'],a:0},
 {t:'free',kind:'Expresión escrita · Tarea 1',task:'Has escuchado en la radio que tu ayuntamiento quiere convertir un parque del barrio en un aparcamiento. Escribe una carta al ayuntamiento (150–180 palabras): preséntate, expresa tu desacuerdo, explica por qué el parque es importante para el barrio y propón una alternativa.',hint:'Estimados señores: Me dirijo a ustedes para … Considero que … ya que … Además, … Por todo ello, les propongo que … Atentamente, …',focus:'formeller Brief, Argumentation, Konnektoren (ya que, además, por todo ello), Subjuntivo nach proponer/pedir que',model:'Estimados señores:\nMe dirijo a ustedes como residente en el barrio de Gràcia para expresar mi desacuerdo con el proyecto de convertir el parque de la plaza del Sol en un aparcamiento.\nConsidero que el parque es uno de los pocos espacios verdes del barrio, ya que la mayoría de las calles son estrechas y no tienen árboles. Además, es un punto de encuentro para familias, personas mayores y jóvenes, que lo utilizan a diario para pasear, hacer deporte o simplemente charlar. Eliminarlo empeoraría la calidad de vida y aumentaría el tráfico en una zona ya bastante contaminada.\nEntiendo que hay pocas plazas de aparcamiento, pero creo que existen alternativas mejores, como mejorar el transporte público o construir un aparcamiento subterráneo bajo el mercado.\nPor todo ello, les propongo que organicen una consulta con los vecinos antes de tomar una decisión definitiva.\nAtentamente,\nJonas Gross'},
 {t:'free',kind:'Expresión escrita · Tarea 2',task:'Escribe un artículo de opinión para un blog (150–180 palabras): «¿Deberían las ciudades prohibir los coches en el centro?». Presenta argumentos a favor y en contra y da tu opinión.',hint:'Hoy en día … Por un lado, … Por otro lado, … Sin embargo, … En mi opinión, … En definitiva, …',focus:'Argumentieren, Diskursmarker (por un lado, sin embargo, en definitiva), Meinung mit Indikativ/Subjuntivo',model:'Cada vez más ciudades europeas se plantean cerrar el centro a los coches. ¿Es una buena idea?\nPor un lado, las ventajas son evidentes: menos contaminación, menos ruido y calles más seguras para peatones y ciclistas. Además, los comercios del centro suelen beneficiarse, porque la gente pasea con más tranquilidad. Por otro lado, no todo el mundo puede renunciar al coche: las personas mayores, quienes viven en las afueras sin buen transporte público o los repartidores dependen de él.\nEn mi opinión, la solución no es prohibir sin más, sino hacerlo de forma gradual y ofrecer alternativas reales: autobuses frecuentes, aparcamientos en las afueras y permisos especiales para quien los necesite. No creo que una medida así funcione si se impone sin escuchar a los vecinos.\nEn definitiva, un centro sin coches puede mejorar mucho la vida en la ciudad, siempre que nadie se quede atrás.'},
 {t:'free',kind:'Expresión oral · Tarea 1',task:'Valorar propuestas: In einer Stadt gibt es zu viel Müll auf den Straßen. Vorschläge: a) höhere Bußgelder, b) mehr Mülleimer und Recyclingcontainer, c) Aufklärungskampagnen in Schulen, d) Pfand auf Flaschen und Dosen. Bewerte die Vorschläge (Vor- und Nachteile) und sag, welcher dir am sinnvollsten erscheint.',hint:'La primera propuesta me parece … porque … Sin embargo, … Yo combinaría … Lo más eficaz sería …',focus:'Bewerten, Konditional, Subjuntivo nach me parece bien que / no creo que',model:'Me parece bien que se pongan multas más altas, pero no creo que sea suficiente, porque es difícil controlar a todo el mundo. Poner más papeleras y contenedores es necesario, aunque si la gente no tiene conciencia, seguirá tirando la basura al suelo. Por eso, yo combinaría las campañas en los colegios con un sistema de depósito para botellas y latas: los niños aprenden pronto y, si te devuelven dinero por cada envase, todo el mundo los recicla.'},
 {t:'free',kind:'Expresión oral · Tarea 2',task:'Situación en una fotografía: 📷 Ein Flughafen-Schalter, ein Mann diskutiert aufgeregt mit einer Angestellten, auf der Anzeigetafel steht „CANCELADO“, Koffer daneben. Beschreibe die Situation, stell Vermutungen an (Was ist passiert? Was sagen sie? Wie geht es weiter?) und erzähl, ob dir so etwas schon passiert ist.',hint:'En la foto se ve … Parece que … Seguramente … Puede que … A mí una vez …',focus:'Vermutungen (habrá, sería, puede que + Subj.), Vergangenheitszeiten',model:'En la foto se ve el mostrador de una compañía aérea. Un hombre de unos cuarenta años habla muy nervioso con una empleada. En la pantalla pone «cancelado», así que seguramente le han cancelado el vuelo. Puede que tenga una reunión importante o que vaya a perder una conexión. La empleada parece tranquila; probablemente le está ofreciendo otro vuelo o una noche de hotel. A mí una vez me pasó algo parecido en Madrid: tuve que dormir en el aeropuerto y llegué un día tarde.'},
 {t:'free',kind:'Expresión oral · Tarea 3',task:'Comentar una encuesta: „¿Cómo te informas de la actualidad?“ – redes sociales 45 %, televisión 25 %, prensa digital 20 %, radio 7 %, prensa en papel 3 %. Kommentiere die Daten: Was überrascht dich? Wie ist es bei dir? Welche Folgen hat das?',hint:'Según la encuesta, … Me llama la atención que … En mi caso, … Esto puede tener consecuencias como …',focus:'Zahlen & Prozente, me sorprende / me llama la atención que + Subj., Vergleiche',model:'Según la encuesta, casi la mitad de la gente se informa por las redes sociales, mientras que solo un tres por ciento lee la prensa en papel. Me llama la atención que la radio tenga tan poco peso, porque en España siempre ha sido muy popular. En mi caso, leo la prensa digital por la mañana y escucho algún pódcast. Creo que informarse solo por redes es peligroso, ya que es fácil encontrar noticias falsas y solo ves opiniones parecidas a la tuya.'},
 {t:'info',title:'¡Enhorabuena! 🎉',html:`<p>Damit hast du alle Teile des <b>DELE B2</b> geübt. Das B2 wird von vielen Universitäten in Spanien als Sprachnachweis verlangt – Termine unter <span class="es-t">examenes.cervantes.es</span>.</p>`}]});
})();
