/* Vocabulario C1 – zusätzliche Pflichtlektionen am Ende der Unidad (für Lernende, die schon weiter sind, erscheinen sie unter „Nachholen“).
   Schließen die Lücken zur C1-Liste des Plan Curricular (Instituto Cervantes, „Nociones específicas C1“), passend zum Thema der Unidad. */
(function(){
function P(uid,l){var u=COURSE.units.filter(function(x){return x.id===uid;})[0];if(u)u.lessons.push(l);}
P('u32',{id:'lx',title:'Vocabulario C1: personalidad, relaciones y medios',desc:'Charakterzüge, Familie & Beziehungen, Nachrichten & Medien',steps:[
 {t:'vocab',title:'Personalidad',items:[['la hospitalidad','die Gastfreundschaft'],['la prepotencia','die Überheblichkeit'],['la discreción','die Diskretion'],['la austeridad','die Genügsamkeit, Sparsamkeit'],['la humildad','die Bescheidenheit'],['la indiferencia','die Gleichgültigkeit'],['la vulnerabilidad','die Verletzlichkeit'],['el coraje','der Mut; die Wut'],['versátil','vielseitig'],['frívolo / frívola','oberflächlich, leichtfertig'],['íntegro / íntegra','integer, rechtschaffen'],['hipocondriaco / hipocondriaca','hypochondrisch'],['altruista','selbstlos'],['caradura','unverschämt, dreist'],['afable','umgänglich, freundlich'],['colérico / colérica','jähzornig'],['visceral','aus dem Bauch heraus, heftig'],['impertinente','frech, unverschämt'],['chulo / chula','angeberisch; cool (ugs.)'],['intransigente','unnachgiebig'],['el escrúpulo','die Skrupel'],['el afán','das Bestreben, der Eifer'],['asumir','übernehmen; akzeptieren'],['afrontar','sich stellen, bewältigen'],['gafe','Pechvogel (ugs.)']]},
 {t:'vocab',title:'Familia y relaciones',items:[['el padrastro','der Stiefvater'],['la madrastra','die Stiefmutter'],['el padrino','der Pate'],['la madrina','die Patin'],['el antepasado','der Vorfahr'],['el / la pariente','der / die Verwandte (entfernt)'],['la dinastía','die Dynastie'],['el árbol genealógico','der Stammbaum'],['la familia monoparental','die Familie mit einem Elternteil'],['sobreproteger','überbehüten'],['malcriar','verwöhnen (falsch erziehen)'],['consentir','verwöhnen; erlauben'],['contradecir','widersprechen'],['desafiar','herausfordern'],['regañar','schimpfen, tadeln'],['inseparable','unzertrennlich'],['el anfitrión / la anfitriona','der Gastgeber / die Gastgeberin'],['el huésped / la huésped','der Gast (übernachtend)'],['duradero / duradera','dauerhaft'],['esporádico / esporádica','gelegentlich'],['tormentoso / tormentosa','stürmisch'],['el idilio','die Romanze'],['estrechar lazos','die Bande festigen'],['el apretón de manos','der Händedruck'],['el rencor','der Groll'],['la frialdad','die Kälte (im Umgang)'],['merecer','verdienen']]},
 {t:'vocab',title:'Información y medios',items:[['el comunicado','die Mitteilung, Verlautbarung'],['notificar','benachrichtigen'],['manifestar','äußern, bekunden'],['contrastar','abgleichen, überprüfen'],['difundir','verbreiten'],['desvelar','enthüllen'],['la malicia','die Bosheit, Hinterlist'],['la primicia','die Erstmeldung, der Scoop'],['polémico / polémica','umstritten'],['impactante','schockierend, eindrucksvoll'],['la exclusiva','die Exklusivmeldung'],['hojear','durchblättern'],['la audiencia','die Einschaltquote; die Zuhörerschaft'],['conmovedor / conmovedora','bewegend'],['desgarrador / desgarradora','herzzerreißend'],['emitir','ausstrahlen, senden'],['retransmitir','übertragen'],['el / la internauta','der Internetnutzer / die Internetnutzerin'],['el pirata informático','der Hacker']]},
 {t:'match',q:'Ordne zu.',pairs:[['la humildad','die Bescheidenheit'],['el padrino','der Pate'],['desvelar','enthüllen'],['el rencor','der Groll'],['versátil','vielseitig']]},
 {t:'gap',q:'Siento que ___ (tú, estar) tan cansado; deberías descansar. (sentir = bedauern → Subjuntivo)',a:['estés']},
 {t:'tr',de:'Die Tatsache, dass er so unnachgiebig ist, macht alles schwieriger.',a:['El hecho de que sea tan intransigente lo hace todo más difícil.','El hecho de que sea tan intransigente hace todo más difícil.']}]});
P('u33',{id:'lx',title:'Vocabulario C1: cuerpo, mesa y ocio',desc:'Körper (auch ugs.), Essen & Trinken, Ausgehen',steps:[
 {t:'vocab',title:'El cuerpo',items:[['la pata','das Bein (ugs.); die Pfote'],['la napia','die Nase (ugs.)'],['el vientre','der Bauch, Unterleib'],['el ombligo','der Bauchnabel'],['el puño','die Faust'],['la palma de la mano','die Handfläche'],['el pulgar','der Daumen'],['el cráneo','der Schädel'],['la vértebra','der Wirbel'],['el páncreas','die Bauchspeicheldrüse'],['el tímpano','das Trommelfell'],['las ojeras','die Augenringe'],['las pecas','die Sommersprossen'],['la caspa','die Schuppen (Haare)'],['rechoncho / rechoncha','pummelig'],['regordete / regordeta','rundlich'],['esquelético / esquelética','spindeldürr'],['robusto / robusta','kräftig'],['corpulento / corpulenta','beleibt, stämmig'],['peludo / peluda','behaart'],['canoso / canosa','grauhaarig'],['parpadear','blinzeln'],['tiritar','zittern (vor Kälte)'],['estremecerse','erschauern'],['encogerse de hombros','mit den Schultern zucken'],['fruncir el ceño','die Stirn runzeln'],['agarrar','packen, festhalten'],['recostarse','sich zurücklehnen']]},
 {t:'vocab',title:'Comer y beber',items:[['tragón / tragona','verfressen (ugs.)'],['glotón / glotona','gefräßig'],['empalagoso / empalagosa','zu süß; aufdringlich'],['insípido / insípida','geschmacklos, fade'],['saborear','genießen, kosten'],['la golosina','die Süßigkeit'],['la chuchería','die Nascherei'],['la acelga','der Mangold'],['la col','der Kohl'],['las alubias','die Bohnen'],['la pepita','der Kern (Obst)'],['el gajo','die Spalte (Orange)'],['la rodaja','die Scheibe (rund)'],['sofreír','andünsten'],['saltear','kurz anbraten'],['escurrir','abtropfen lassen'],['moler','mahlen'],['catar','verkosten'],['sobrio / sobria','nüchtern'],['ebrio / ebria','betrunken'],['abstemio / abstemia','abstinent'],['espumoso / espumosa','schäumend, Schaum-'],['descorchar','entkorken'],['la vajilla','das Geschirr'],['la cubertería','das Besteck'],['la cucharilla','der Teelöffel'],['el cucharón','die Schöpfkelle'],['el colador','das Sieb'],['la tasca','die Kneipe'],['el chiringuito','die Strandbar'],['la taberna','die Taverne'],['el entrante','die Vorspeise'],['los percebes','die Entenmuscheln'],['la codorniz','die Wachtel']]},
 {t:'vocab',title:'Salir y divertirse',items:[['trasnochar','die Nacht durchmachen'],['vaguear','faulenzen'],['ocioso / ociosa','untätig, müßig'],['desenfrenado / desenfrenada','zügellos'],['concurrido / concurrida','gut besucht'],['el / la hincha','der Fan (Sport)'],['el forofo / la forofa','der fanatische Anhänger'],['el títere','die Handpuppe'],['la marioneta','die Marionette'],['los malabares','die Jonglierkunst']]},
 {t:'match',q:'Ordne zu.',pairs:[['las pecas','die Sommersprossen'],['parpadear','blinzeln'],['abstemio','abstinent'],['el chiringuito','die Strandbar'],['trasnochar','die Nacht durchmachen']]},
 {t:'mc',q:'„Estoy hasta las narices de este ruido.“ bedeutet …',opts:['Ich habe die Nase voll von diesem Lärm.','Der Lärm tut mir in der Nase weh.','Ich höre den Lärm kaum.'],a:0},
 {t:'tr',de:'Gestern haben wir die Nacht durchgemacht und heute faulenzen wir.',a:['Ayer trasnochamos y hoy vagueamos.','Ayer trasnochamos y hoy estamos vagueando.']}]});
P('u34',{id:'lx',title:'Vocabulario C1: trabajo, banca y comercio',desc:'Arbeitsleben, Kündigung, Gehalt, Bank, Handel',steps:[
 {t:'vocab',title:'El trabajo',items:[['el asalariado / la asalariada','der Arbeitnehmer / die Arbeitnehmerin'],['el operario / la operaria','der Arbeiter / die Arbeiterin (Fabrik)'],['el / la aprendiz','der Lehrling'],['el / la aspirante','der Bewerber / die Bewerberin'],['el / la suplente','die Vertretung'],['vitalicio / vitalicia','auf Lebenszeit'],['desempeñar un cargo','ein Amt ausüben'],['el / la ejecutivo/a','die Führungskraft'],['la labor','die Arbeit, Tätigkeit'],['el quehacer','die Aufgabe, Beschäftigung'],['gratificante','erfüllend, lohnend'],['absorbente','fordernd, vereinnahmend'],['remunerado / remunerada','bezahlt'],['precario / precaria','prekär'],['delegar','delegieren'],['desbordar','überfordern, überlaufen'],['minucioso / minuciosa','gründlich'],['riguroso / rigurosa','streng, genau'],['la dimisión','der Rücktritt'],['la destitución','die Amtsenthebung'],['destituir','absetzen'],['el cese','die Entlassung, Beendigung'],['la vacante','die freie Stelle'],['subcontratar','an Subunternehmer vergeben'],['el sueldo bruto','das Bruttogehalt'],['el sueldo neto','das Nettogehalt'],['el salario mínimo interprofesional','der gesetzliche Mindestlohn'],['la retribución','die Vergütung'],['el acoso laboral','das Mobbing am Arbeitsplatz'],['incumplir','nicht einhalten'],['prorrogar','verlängern'],['congelar el sueldo','das Gehalt einfrieren'],['el año sabático','das Sabbatjahr'],['la excedencia','die Freistellung, Elternzeit'],['afiliarse','beitreten (Gewerkschaft)'],['emprendedor / emprendedora','unternehmerisch'],['eficiente','effizient']]},
 {t:'vocab',title:'Banca y comercio',items:[['el banquero / la banquera','der Banker / die Bankerin'],['la entidad bancaria','das Kreditinstitut'],['la sucursal','die Filiale'],['el aval','die Bürgschaft'],['el extracto de cuenta','der Kontoauszug'],['el / la fabricante','der Hersteller'],['el encargado / la encargada','der Verantwortliche, Filialleiter'],['el proveedor / la proveedora','der Lieferant'],['la denominación de origen','die geschützte Herkunftsbezeichnung'],['comercializar','vermarkten'],['subastar','versteigern'],['fidelizar','an sich binden (Kunden)'],['traspasar','(Geschäft) übergeben, ablösen'],['la liquidación','der Ausverkauf'],['el lote','die Partie, das Los'],['el mostrador','die Theke'],['el estante','das Regal(brett)'],['desembolsar','auslegen, zahlen'],['costear','finanzieren, bestreiten'],['aplazar','verschieben'],['agilizar','beschleunigen'],['malgastar','verschwenden'],['la fecha de caducidad','das Haltbarkeitsdatum']]},
 {t:'match',q:'Ordne zu.',pairs:[['dimitir','zurücktreten, kündigen'],['la vacante','die freie Stelle'],['el sueldo neto','das Nettogehalt'],['la sucursal','die Filiale'],['subastar','versteigern']]},
 {t:'gap',q:'Te prestaré el dinero con tal de que me lo ___ (devolver) antes de junio.',a:['devuelvas']},
 {t:'tr',de:'Falls sie das Gehalt einfrieren, trete ich zurück.',a:['En caso de que congelen el sueldo, dimitiré.','En caso de que congelen el sueldo, dimito.']}]});
P('u35',{id:'lx',title:'Vocabulario C1: cultura, fiestas, moda y hogar',desc:'Veranstaltungen, Sport, Feste, Mode, Einrichtung',steps:[
 {t:'vocab',title:'Espectáculos y competiciones',items:[['el certamen','der Wettbewerb (Kunst)'],['el recital','der Liederabend, die Lesung'],['la grada','die Tribüne'],['el palco','die Loge'],['presenciar','beiwohnen, miterleben'],['acudir','hingehen, erscheinen'],['antológico / antológica','legendär; Retrospektiv-'],['itinerante','Wander- (Ausstellung)'],['la proyección','die Vorführung'],['el torneo','das Turnier'],['el trofeo','die Trophäe'],['el podio','das Siegertreppchen'],['el adversario / la adversaria','der Gegner / die Gegnerin'],['la derrota','die Niederlage'],['empedernido / empedernida','unverbesserlich, eingefleischt'],['amateur','Amateur-']]},
 {t:'vocab',title:'Fiestas y actos',items:[['la inauguración','die Eröffnung'],['la clausura','der Abschluss (Veranstaltung)'],['la conmemoración','das Gedenken'],['las fiestas patronales','das Patronatsfest'],['navideño / navideña','weihnachtlich'],['el / la aguafiestas','der Spielverderber / die Spielverderberin'],['la comunión','die Kommunion'],['presidir','vorsitzen, leiten'],['el pésame','das Beileid'],['la enhorabuena','der Glückwunsch']]},
 {t:'vocab',title:'Moda',items:[['la pasarela','der Laufsteg'],['escotado / escotada','ausgeschnitten'],['ceñido / ceñida','eng anliegend'],['holgado / holgada','weit, locker'],['bordado / bordada','bestickt'],['de gala','festlich, Gala-'],['el dobladillo','der Saum'],['el imperdible','die Sicherheitsnadel']]},
 {t:'vocab',title:'Casa y decoración',items:[['colonial','im Kolonialstil'],['minimalista','minimalistisch'],['el tono pastel','der Pastellton'],['mate','matt'],['empapelar','tapezieren'],['el hueco','die Lücke, Nische'],['el rincón','die Ecke (innen)'],['la mecedora','der Schaukelstuhl'],['la vitrina','die Vitrine'],['el estor','das Rollo'],['el visillo','die Gardine'],['el palacete','die Villa, das kleine Palais'],['la mansión','die Villa'],['la chabola','die Baracke, Hütte (Elendsviertel)'],['la choza','die Hütte'],['la morada','die Behausung']]},
 {t:'match',q:'Ordne zu.',pairs:[['el pésame','das Beileid'],['la pasarela','der Laufsteg'],['la derrota','die Niederlage'],['empapelar','tapezieren'],['el aguafiestas','der Spielverderber / die Spielverderberin']]},
 {t:'gap',q:'Fue en el palco ___ (wo) conocí a mi pareja. (Spaltsatz)',a:['donde']},
 {t:'tr',de:'Das Gute an der Ausstellung ist, dass sie wandert.',a:['Lo bueno de la exposición es que es itinerante.']}]});
P('u36',{id:'lx',title:'Vocabulario C1: salud, técnica y construcción',desc:'Medizin, Fachbereiche, Bau & Haushalt, Telefon & Technik',steps:[
 {t:'vocab',title:'Enfermedades',items:[['el contagio','die Ansteckung'],['la curación','die Heilung'],['la recaída','der Rückfall'],['la convalecencia','die Genesungszeit'],['la epidemia','die Epidemie'],['la ludopatía','die Spielsucht'],['la anorexia','die Magersucht'],['la anemia','die Blutarmut'],['la úlcera','das Geschwür'],['la hernia','der Bruch (Hernie)'],['el lumbago','der Hexenschuss'],['la fractura','der Knochenbruch'],['el esguince','die Verstauchung'],['la inflamación','die Entzündung'],['la infección','die Infektion'],['cicatrizar','vernarben, heilen'],['el chichón','die Beule'],['el picor','der Juckreiz'],['el trastorno','die Störung'],['punzante','stechend'],['aliviar','lindern'],['remitir','nachlassen (Schmerz)'],['agravarse','sich verschlimmern'],['desmayarse','ohnmächtig werden'],['inconsciente','bewusstlos']]},
 {t:'vocab',title:'Medicina',items:[['la terapia','die Therapie'],['la neurología','die Neurologie'],['la pediatría','die Kinderheilkunde'],['la radiología','die Radiologie'],['la geriatría','die Altersmedizin'],['la dermatología','die Dermatologie'],['la psiquiatría','die Psychiatrie'],['la fisioterapia','die Physiotherapie'],['donar','spenden'],['el órgano','das Organ'],['eficaz','wirksam'],['preventivo / preventiva','vorbeugend'],['el comprimido','die Tablette'],['la cápsula','die Kapsel'],['la píldora','die Pille'],['ingerir','einnehmen'],['la prótesis','die Prothese'],['el implante','das Implantat']]},
 {t:'vocab',title:'Construcción y hogar',items:[['el hormigón','der Beton'],['el yeso','der Gips (Bau)'],['la grieta','der Riss'],['el parqué','das Parkett'],['la moqueta','der Teppichboden'],['derribar','abreißen'],['edificar','bauen'],['rehabilitar','sanieren'],['el casero / la casera','der Vermieter / die Vermieterin'],['desinfectar','desinfizieren'],['frotar','reiben, schrubben'],['aclarar','ausspülen; klären'],['la lejía','das Bleichmittel'],['la bayeta','das Wischtuch'],['el estropajo','der Topfschwamm'],['centrifugar','schleudern'],['el mantenimiento','die Wartung'],['la pieza de recambio','das Ersatzteil'],['la gama','die Produktpalette']]},
 {t:'vocab',title:'Telefonía y técnica',items:[['el auricular','der Hörer; der Kopfhörer'],['inalámbrico / inalámbrica','kabellos'],['la antena parabólica','die Satellitenschüssel'],['la centralita','die Telefonzentrale'],['la telefonía','die Telefonie'],['el abonado / la abonada','der Teilnehmer / die Teilnehmerin (Abo)'],['la intranet','das Intranet']]},
 {t:'match',q:'Ordne zu.',pairs:[['la recaída','der Rückfall'],['el esguince','die Verstauchung'],['la grieta','der Riss'],['el inquilino','der Mieter'],['inalámbrico','kabellos']]},
 {t:'gap',q:'Por muy eficaz que ___ (ser) el tratamiento, necesitarás reposo.',a:['sea']},
 {t:'tr',de:'Obwohl der Schmerz nachgelassen hat, gehe ich zur Physiotherapie.',a:['Aunque el dolor ha remitido, voy a fisioterapia.','Si bien el dolor ha remitido, voy a fisioterapia.','Aunque el dolor ha remitido, voy a ir a fisioterapia.']}]});
P('u37',{id:'lx',title:'Vocabulario C1: educación, administración y tráfico',desc:'Bildung & Uni, Behörden, Sicherheit, Soziales, Verkehr & Reisen',steps:[
 {t:'vocab',title:'Educación',items:[['el conservatorio','das Konservatorium'],['el rectorado','das Rektorat'],['el decanato','das Dekanat'],['el decano / la decana','der Dekan / die Dekanin'],['el / la docente','die Lehrkraft'],['el pedagogo / la pedagoga','der Pädagoge / die Pädagogin'],['el discípulo / la discípula','der Schüler, Jünger'],['el becario / la becaria','der Stipendiat; der Praktikant'],['el repetidor / la repetidora','der Sitzenbleiber'],['el claustro','das Lehrerkollegium'],['la asignatura troncal','das Pflichtfach'],['la titulación','der Abschluss'],['el cursillo','der Kurzlehrgang'],['el fracaso escolar','das Schulversagen'],['convalidar','anerkennen (Abschluss)'],['cursar','belegen, studieren'],['acreditar','nachweisen, akkreditieren'],['sancionar','bestrafen'],['expulsar','verweisen, ausschließen'],['la novatada','der Erstsemesterstreich'],['hacer novillos','schwänzen'],['la pedagogía','die Pädagogik'],['el empollón / la empollona','der Streber / die Streberin'],['el novato / la novata','der Neuling'],['lúdico / lúdica','spielerisch'],['asimilar','verarbeiten, aufnehmen'],['empollar','büffeln'],['la calificación','die Note, Bewertung'],['puntuar','bewerten, Punkte vergeben'],['la recuperación','die Nachprüfung'],['la tesina','die Abschlussarbeit'],['el archivador','der Aktenordner'],['el proyector','der Beamer']]},
 {t:'vocab',title:'Administración y seguridad',items:[['expedir','ausstellen (Dokument)'],['denegar','ablehnen'],['sellar','abstempeln'],['residir','wohnhaft sein'],['el seudónimo','das Pseudonym'],['el apodo','der Spitzname'],['enviudar','verwitwen'],['el control de alcoholemia','die Alkoholkontrolle'],['el arresto','die Festnahme'],['la detención','die Verhaftung'],['el interrogatorio','das Verhör'],['desactivar','entschärfen'],['el artefacto explosivo','der Sprengsatz'],['los antecedentes penales','die Vorstrafen'],['la sospecha','der Verdacht'],['el voluntariado','die Freiwilligenarbeit'],['la inserción laboral','die Eingliederung ins Arbeitsleben'],['la prevención','die Vorbeugung'],['el asesoramiento jurídico','die Rechtsberatung'],['acoger','aufnehmen'],['excluir','ausschließen'],['el vertedero','die Mülldeponie'],['el alumbrado público','die Straßenbeleuchtung'],['el alcantarillado','die Kanalisation'],['el suministro','die Versorgung']]},
 {t:'vocab',title:'Tráfico y viajes',items:[['el arcén','der Seitenstreifen'],['el muelle','der Kai'],['el embarcadero','die Anlegestelle'],['la furgoneta','der Lieferwagen'],['el todoterreno','der Geländewagen'],['el descapotable','das Cabrio'],['el volante','das Lenkrad'],['el retrovisor','der Rückspiegel'],['el embrague','die Kupplung'],['el acelerador','das Gaspedal'],['la maniobra','das Manöver'],['el adelantamiento','das Überholen'],['derrapar','ins Schleudern geraten'],['patinar','rutschen'],['el frenazo','die Vollbremsung'],['la carrocería','die Karosserie'],['remolcar','abschleppen'],['temerario / temeraria','leichtsinnig'],['infringir','verstoßen gegen'],['naufragar','Schiffbruch erleiden'],['el chaleco salvavidas','die Rettungsweste'],['el camarote','die Kabine (Schiff)'],['el copiloto / la copiloto','der Beifahrer; der Kopilot'],['el paracaídas','der Fallschirm'],['la brújula','der Kompass'],['la cantimplora','die Feldflasche'],['la navaja','das Taschenmesser'],['veranear','die Sommerferien verbringen'],['la insolación','der Sonnenstich'],['escarpado / escarpada','steil, schroff'],['trepar','klettern']]},
 {t:'match',q:'Ordne zu.',pairs:[['hacer novillos','schwänzen'],['convalidar','anerkennen (Abschluss)'],['el arcén','der Seitenstreifen'],['la avería','die Panne, der Defekt'],['denegar','ablehnen']]},
 {t:'mc',q:'Konnektor im Essay: „Los datos son prometedores. ___, conviene no sacar conclusiones precipitadas.“',opts:['Ahora bien','Por ende','A saber'],a:0},
 {t:'tr',de:'Man hat mir das Visum verweigert; dennoch werde ich es erneut beantragen.',a:['Me han denegado el visado; no obstante, volveré a solicitarlo.','Me denegaron el visado; no obstante, volveré a solicitarlo.','Me han denegado el visado; sin embargo, volveré a solicitarlo.']}]});
P('u37',{id:'lz',title:'Prueba DELE C1',desc:'Übungstest im DELE-Format',steps:[
 {t:'info',title:'Das DELE C1',html:`<p>Auf C1 werden Fertigkeiten kombiniert: Du hörst oder liest etwas und musst es schriftlich oder mündlich weiterverarbeiten (Mediation):</p>
 <table><tr><th>Teil</th><th>Dauer</th><th>Aufgaben</th></tr>
 <tr><td>Comprensión de lectura y uso de la lengua</td><td>90 Min.</td><td>5 Tareas, 40 Fragen: lange Texte, fehlende Absätze, Wortschatz und Grammatik im Kontext</td></tr>
 <tr><td>Comprensión auditiva y uso de la lengua</td><td>50 Min.</td><td>4 Tareas, 30 Fragen: Vorträge, Gespräche, Interviews</td></tr>
 <tr><td>Expresión e interacción escritas, mediación</td><td>80 Min.</td><td>einen gehörten Vortrag schriftlich zusammenfassen und bewerten; einen Text zu einem Thema schreiben (Bericht, Brief, Artikel)</td></tr>
 <tr><td>Expresión e interacción orales, mediación</td><td>20 Min. + 20 Min. Vorbereitung</td><td>Monolog zu einem Thema, Gespräch darüber, Verhandeln in einer Alltagssituation</td></tr></table>
 <p>Jeder Teil hat 25 Punkte; das genaue Bestehenskriterium steht in der Guía des Instituto Cervantes.</p>`},
 {t:'read',kind:'Lectura · Tarea 1',title:'El elogio de la lentitud',text:`Vivimos instalados en la prisa. Contestamos correos mientras comemos, escuchamos pódcasts a velocidad doble y medimos el éxito de un día por la cantidad de tareas tachadas. Sin embargo, en los últimos años ha cobrado fuerza un movimiento que reivindica justo lo contrario: hacer menos cosas, pero hacerlas bien.
Sus defensores no proponen abandonar la vida moderna, sino recuperar el control sobre el tiempo. Cocinar sin mirar el reloj, leer un libro entero sin interrupciones o pasear sin rumbo fijo serían, según ellos, pequeños actos de resistencia frente a una cultura que confunde estar ocupado con ser productivo. Ahora bien, los críticos advierten de que la lentitud se ha convertido también en un producto de lujo: no todo el mundo puede permitirse un retiro de fin de semana sin móvil ni rechazar horas extra.
Quizá la clave no esté en elegir entre rapidez y lentitud, sino en recuperar la capacidad de decidir qué merece nuestra atención plena y qué puede hacerse deprisa sin remordimientos.`,de:`Wir haben uns in der Eile eingerichtet. Wir beantworten E-Mails beim Essen, hören Podcasts mit doppelter Geschwindigkeit und messen den Erfolg eines Tages an der Zahl der abgehakten Aufgaben. In den letzten Jahren hat jedoch eine Bewegung an Kraft gewonnen, die genau das Gegenteil fordert: weniger tun, das aber gut.
Ihre Verfechter schlagen nicht vor, das moderne Leben aufzugeben, sondern die Kontrolle über die Zeit zurückzugewinnen. Ohne Blick auf die Uhr kochen, ein ganzes Buch ohne Unterbrechung lesen oder ziellos spazieren gehen wären ihnen zufolge kleine Akte des Widerstands gegen eine Kultur, die Beschäftigtsein mit Produktivität verwechselt. Kritiker warnen allerdings, dass Langsamkeit auch zu einem Luxusprodukt geworden ist: Nicht jeder kann sich ein Wochenende ohne Handy leisten oder Überstunden ablehnen.
Vielleicht liegt der Schlüssel nicht darin, zwischen Schnelligkeit und Langsamkeit zu wählen, sondern die Fähigkeit zurückzugewinnen zu entscheiden, was unsere volle Aufmerksamkeit verdient und was ohne Gewissensbisse schnell erledigt werden kann.`},
 {t:'mc',kind:'Lectura · Tarea 1',q:'Según el texto, los defensores de la lentitud …',opts:['quieren recuperar el control sobre su tiempo','proponen abandonar la tecnología','creen que estar ocupado es productivo'],a:0},
 {t:'mc',kind:'Lectura · Tarea 1',q:'¿Qué critican algunos del movimiento?',opts:['que no está al alcance de todos','que es demasiado rápido','que prohíbe las horas extra'],a:0},
 {t:'mc',kind:'Lectura · Tarea 1',q:'¿Cuál es la conclusión del autor?',opts:['Hay que saber elegir a qué dedicar atención plena.','Siempre es mejor ir despacio.','La rapidez es imprescindible hoy en día.'],a:0},
 {t:'mc',kind:'Lectura · Tarea 4',q:'Uso de la lengua: No es que no ___ ayudarte, es que no tengo tiempo.',opts:['quiera','quiero','querré'],a:0,why:'<i>no es que</i> + Subjuntivo.'},
 {t:'mc',kind:'Lectura · Tarea 4',q:'Uso de la lengua: Tomaron la decisión sin ___ en cuenta las consecuencias.',opts:['tener','tenido','que tengan'],a:0},
 {t:'mc',kind:'Lectura · Tarea 5',q:'Uso de la lengua – elige la palabra adecuada: El informe es muy ___: no se le escapa ningún detalle.',opts:['minucioso','precario','frívolo'],a:0},
 {t:'mc',kind:'Lectura · Tarea 5',q:'Uso de la lengua – elige la palabra adecuada: Tras la operación, necesitará un largo periodo de ___.',opts:['convalecencia','convivencia','conveniencia'],a:0},
 {t:'read',hideText:true,kind:'Comprensión auditiva · Tarea 1',title:'Conferencia sobre el teletrabajo',intro:'Escucha el fragmento de una conferencia.',text:`Buenas tardes. Cuando hablamos de teletrabajo solemos centrarnos en la flexibilidad, pero los datos de nuestro estudio apuntan a un fenómeno menos visible: la desconexión digital. Un treinta y ocho por ciento de los encuestados reconoce que contesta mensajes de trabajo fuera de su horario al menos tres veces por semana. Y lo más preocupante es que la mayoría no lo percibe como un problema, sino como algo normal. Por eso defendemos que la desconexión no puede depender solo de la voluntad individual: las empresas deben establecer normas claras, como no enviar correos a partir de cierta hora.`,de:`Guten Tag. Wenn wir über Homeoffice sprechen, konzentrieren wir uns meist auf die Flexibilität, aber die Daten unserer Studie weisen auf ein weniger sichtbares Phänomen hin: das digitale Abschalten. Achtunddreißig Prozent der Befragten geben zu, mindestens dreimal pro Woche außerhalb der Arbeitszeit auf berufliche Nachrichten zu antworten. Und am besorgniserregendsten ist, dass die meisten das nicht als Problem wahrnehmen, sondern als etwas Normales. Deshalb vertreten wir die Ansicht, dass Abschalten nicht nur vom individuellen Willen abhängen darf: Die Unternehmen müssen klare Regeln aufstellen, zum Beispiel ab einer bestimmten Uhrzeit keine E-Mails mehr zu verschicken.`},
 {t:'mc',kind:'Comprensión auditiva · Tarea 1',q:'¿Qué es lo que más preocupa a la conferenciante?',opts:['que la mayoría vea normal contestar fuera de horario','que se trabaje menos en casa','que las empresas prohíban el teletrabajo'],a:0},
 {t:'mc',kind:'Comprensión auditiva · Tarea 1',q:'¿Qué propone?',opts:['normas claras por parte de las empresas','que cada trabajador decida solo','eliminar el correo electrónico'],a:0},
 {t:'free',kind:'Expresión escrita · Tarea 1 (mediación)',task:'Mediación: Fasse die Konferenz über das digitale Abschalten (Hörtext oben) für den Newsletter deiner Firma zusammen (ca. 150 Wörter): Hauptaussage, Daten, Vorschlag – und ergänze eine eigene kurze Bewertung.',hint:'En la conferencia se abordó … Según los datos, … Lo más llamativo es que … Por ello, la ponente propone … A mi juicio, …',focus:'zusammenfassen und umformulieren, indirekte Rede, Konnektoren, eigene Bewertung',model:'En la conferencia se abordó un aspecto poco visible del teletrabajo: la dificultad para desconectar. Según los datos presentados, el 38 % de los encuestados contesta mensajes de trabajo fuera de su horario al menos tres veces por semana. Lo más llamativo, sin embargo, es que la mayoría no lo considera un problema, sino algo normal. Por ello, la ponente defendió que la desconexión no puede quedar en manos de cada trabajador y propuso que las empresas establezcan normas claras, como no enviar correos a partir de cierta hora. A mi juicio, la propuesta es acertada, aunque solo funcionará si los propios directivos dan ejemplo; de lo contrario, nadie se atreverá a no responder.'},
 {t:'free',kind:'Expresión escrita · Tarea 2',task:'Escribe un artículo de opinión (220–250 palabras) para una revista universitaria: «¿Debería la universidad ser gratuita para todos?». Argumenta, matiza y llega a una conclusión.',hint:'Si bien … · Por muy … que … · Cabe señalar que … · Ahora bien, … · En definitiva, …',focus:'C1-Konnektoren, Konzessivsätze, Hervorhebung, Register',model:'La gratuidad de la enseñanza universitaria es uno de esos debates que reaparecen cada vez que sube el precio de la matrícula. Si bien la idea resulta atractiva, conviene analizarla con algo más de detenimiento.\nPor un lado, una universidad gratuita garantizaría que el talento, y no la cuenta bancaria de la familia, decidiera quién estudia. Cabe señalar que en varios países europeos este modelo funciona desde hace décadas sin que la calidad se haya resentido. Por otro lado, la gratuidad total implica que también quienes podrían pagar sin dificultad reciban esa ayuda, financiada con los impuestos de todos, incluidos quienes nunca pisarán una facultad.\nAhora bien, por muy costoso que sea el sistema, el verdadero obstáculo para muchos estudiantes no es tanto la matrícula como el coste de vivir fuera de casa durante cuatro o cinco años. Por eso, más que una gratuidad indiscriminada, me parece más justo un sistema de becas generoso que cubra también el alojamiento y la manutención.\nEn definitiva, lo importante no es que la universidad sea gratis para todos, sino que nadie con capacidad tenga que renunciar a ella por motivos económicos.'},
 {t:'free',kind:'Expresión oral · Tarea 1-2',task:'Monólogo (3–5 minutos) + entrevista: «La inteligencia artificial en la educación». Bereite eine strukturierte Präsentation vor (Einleitung, 2–3 Argumente, Beispiele, Fazit) und Antworten auf mögliche Rückfragen (¿Prohibiría usted el uso de la IA en los exámenes?).',hint:'Me gustaría centrarme en … En primer lugar … Un ejemplo claro sería … No obstante … Para concluir …',focus:'Struktur, Diskursmarker, Hypothesen, Nuancen',model:'Me gustaría centrarme en cómo la inteligencia artificial está transformando la educación. En primer lugar, ofrece la posibilidad de adaptar el aprendizaje a cada alumno: un programa puede detectar en qué se equivoca alguien y proponerle ejercicios específicos. Un ejemplo claro serían las aplicaciones de idiomas que corrigen la pronunciación al instante. No obstante, también plantea riesgos evidentes, como que los estudiantes deleguen en la máquina tareas que deberían aprender a hacer por sí mismos. Para concluir, creo que no se trata de prohibir, sino de enseñar a usarla con criterio.'},
 {t:'dialog',kind:'Expresión oral · Tarea 3',place:'Asociación de vecinos',title:'Negociación: el presupuesto de la fiesta del barrio',scene:'Du und ein Nachbar habt 1.000 € für das Straßenfest. Er will alles für ein Konzert ausgeben; du findest Aktivitäten für Kinder und ältere Leute wichtig. Verhandelt einen Kompromiss.',lines:[
  {n:'Vecino',es:'Yo lo tengo claro: con mil euros podemos traer a un grupo bastante conocido. Eso atraería a muchísima gente.',de:'Für mich ist es klar: Mit tausend Euro können wir eine ziemlich bekannte Band holen. Das würde sehr viele Leute anziehen.'},
  {you:true,opts:[{es:'Entiendo tu punto de vista, pero si nos lo gastamos todo en el concierto, los niños y los mayores se quedarían sin actividades.',ok:true},{es:'No. El concierto es una idea fatal.',ok:false,why:'Auf C1 erwartet man diplomatisches Verhandeln: erst Verständnis zeigen, dann widersprechen.'}]},
  {n:'Vecino',es:'Bueno, pero los niños se divierten con cualquier cosa. ¿Qué propones?',de:'Na ja, aber Kinder amüsieren sich mit allem Möglichen. Was schlägst du vor?'},
  {you:true,opts:[{es:'¿Qué te parece si dedicamos seiscientos euros al concierto y el resto a un taller infantil y una merienda para los mayores?',ok:true},{es:'Propongo que tú pagas el concierto.',ok:false,why:'<i>propongo que</i> + Subjuntivo – und ein konstruktiver Kompromiss wäre besser.'}]},
  {n:'Vecino',es:'Mmm… Con seiscientos el grupo que quería no viene, pero podríamos buscar uno local.',de:'Hmm… Mit sechshundert kommt die Band, die ich wollte, nicht, aber wir könnten eine lokale suchen.'},
  {you:true,opts:[{es:'Me parece una solución estupenda; además, apoyaríamos a músicos del barrio.',ok:true},{es:'Vale, pues haz lo que quieras.',ok:false,why:'Schließe die Verhandlung positiv ab und begründe die Einigung.'}]}]},
 {t:'info',title:'¡Enhorabuena! 🎉',html:`<p>Damit hast du alle Teile des <b>DELE C1</b> geübt. C1 zeigt, dass du Spanisch auch beruflich und akademisch souverän nutzt – Termine unter <span class="es-t">examenes.cervantes.es</span>.</p>`}]});
})();
