window.PLACEMENT=[
/* u0 */
{u:'u0',t:'mc',q:'Es 9:00 Uhr morgens. Du begrüßt die Professorin:',opts:['Buenos días.','Buenas tardes.','Buenas noches.'],a:0},
{u:'u0',t:'mc',q:'Formell: „Wie heißen Sie?“',opts:['¿Cómo se llama usted?','¿Cómo te llamas?','¿Cómo está usted?'],a:0},
{u:'u0',t:'mc',q:'Eine Frau freut sich, dich kennenzulernen. Sie sagt:',opts:['Encantada.','Encantado.','Hasta luego.'],a:0},
{u:'u0',t:'mc',q:'In welchem Wort ist das u stumm?',opts:['guitarra','Uruguay','agua'],a:0},
/* u1 */
{u:'u1',t:'mc',q:'___ ciudades de España',opts:['las','los','la'],a:0},
{u:'u1',t:'gap',q:'– ¿De dónde ___ (tú)? – ___ de Alemania.',a:['eres','soy']},
{u:'u1',t:'gap',q:'Nosotros ___ (hablar) inglés y español.',a:['hablamos']},
{u:'u1',t:'mc',q:'– No hablo chino. – Ich auch nicht:',opts:['Yo tampoco.','Yo también.','Yo sí.'],a:0},
/* u2 */
{u:'u2',t:'mc',q:'„Ich bin 24 Jahre alt.“',opts:['Tengo 24 años.','Soy 24 años.','Estoy 24 años.'],a:0},
{u:'u2',t:'gap',q:'Mis padres ___ (vivir) en Alemania.',a:['viven']},
{u:'u2',t:'mc',q:'Du stellst Laia vor:',opts:['Esta es Laia.','Este es Laia.','Estos son Laia.'],a:0},
{u:'u2',t:'mc',q:'„@“ heißt auf Spanisch …',opts:['arroba','punto','guion'],a:0},
/* u3 */
{u:'u3',t:'mc',q:'Barcelona ___ en Cataluña.',opts:['está','es','hay'],a:0},
{u:'u3',t:'mc',q:'A mí me ___ los idiomas.',opts:['gustan','gusta','gusto'],a:0},
{u:'u3',t:'gap',q:'Mis hermanas son muy ___ (simpático).',a:['simpáticas']},
{u:'u3',t:'mc',q:'„ihre Eltern“ (von Ana):',opts:['sus padres','su padres','suyos padres'],a:0},
/* u4 */
{u:'u4',t:'gap',q:'Yo no ___ (poder) comer carne, soy vegetariano.',a:['puedo']},
{u:'u4',t:'mc',q:'14:30 Uhr – ¿Qué hora es?',opts:['Son las dos y media.','Es la dos y media.','Son las tres menos media.'],a:0},
{u:'u4',t:'mc',q:'Im Restaurant: „Und zu trinken?“',opts:['¿Y para beber?','¿Y por beber?','¿Y a beber?'],a:0},
{u:'u4',t:'mc',q:'– ¿Quién compra el pan? – Yo ___ compro.',opts:['lo','la','le'],a:0},
/* u5 */
{u:'u5',t:'mc',q:'En Barcelona ___ muchos museos.',opts:['hay','están','es'],a:0},
{u:'u5',t:'gap',q:'Mañana yo ___ (ir) a la universidad en metro.',a:['voy']},
{u:'u5',t:'mc',q:'„Gehen Sie geradeaus.“',opts:['Siga todo recto.','Gira a la izquierda.','Está cerca.'],a:0},
{u:'u5',t:'mc',q:'Vamos ___ aeropuerto.',opts:['al','a el','en el'],a:0},
/* u6 */
{u:'u6',t:'gap',q:'Esta semana ___ (yo, trabajar) mucho. (Perfekt)',a:['he trabajado']},
{u:'u6',t:'mc',q:'Partizip von „hacer“:',opts:['hecho','hacido','hizo'],a:0},
{u:'u6',t:'mc',q:'– Me encanta la playa. – (Dir auch.)',opts:['A mí también.','Yo también.','A mí tampoco.'],a:0},
{u:'u6',t:'gap',q:'¿___ (tú, estar) alguna vez en México? (Perfekt)',a:['has estado']},
/* u7 */
{u:'u7',t:'gap',q:'Normalmente me ___ (levantarse) a las siete.',a:['levanto']},
{u:'u7',t:'mc',q:'¿Qué estás ___? – Estoy escribiendo un informe.',opts:['haciendo','hacer','hecho'],a:0},
{u:'u7',t:'mc',q:'Luis trabaja ___ horas ___ Pedro. (genauso viele)',opts:['tantas … como','más … que','tanto … como'],a:0},
{u:'u7',t:'mc',q:'„Kannst du Französisch?“ (Fähigkeit)',opts:['¿Sabes francés?','¿Puedes francés?','¿Conoces francés?'],a:0},
/* u8 */
{u:'u8',t:'gap',q:'El lunes ___ ___ visitar a un cliente. (ir a + Inf., yo)',a:['voy','a']},
{u:'u8',t:'mc',q:'Wetter: „Es ist heiß.“',opts:['Hace calor.','Es calor.','Está calor.'],a:0},
{u:'u8',t:'mc',q:'¿Te parece si quedamos a las diez? – Zusagen:',opts:['Vale, de acuerdo.','Lo siento, no puedo.','Mejor el viernes.'],a:0},
{u:'u8',t:'mc',q:'Ich kenne die Gründerin:',opts:['Conozco a la fundadora.','Conozco la fundadora.','Sé a la fundadora.'],a:0}
,
/* zusätzliche Fragen (Pool) – pro Test werden je Unidad 4 zufällig gezogen */
{u:'u0',t:'mc',q:'„Bis morgen!“',opts:['¡Hasta mañana!','¡Hasta luego!','¡Buenas noches!'],a:0},
{u:'u0',t:'mc',q:'Wie spricht man „j“ in „jamón“?',opts:['wie ch in „Sache“','wie j in „ja“','wie dsch'],a:0},
{u:'u1',t:'mc',q:'Plural von „la ciudad“:',opts:['las ciudades','las ciudads','los ciudades'],a:0},
{u:'u1',t:'gap',q:'¿Vosotros ___ (ser) de Barcelona?',a:['sois']},
{u:'u2',t:'gap',q:'Nosotros ___ (aprender) español.',a:['aprendemos']},
{u:'u2',t:'mc',q:'Weibliche Form von „el programador“:',opts:['la programadora','la programador','la programadera'],a:0},
{u:'u3',t:'gap',q:'¿Cómo ___ (estar) tus padres?',a:['están']},
{u:'u3',t:'mc',q:'Der Vater meiner Mutter ist mein …',opts:['abuelo','tío','primo'],a:0},
{u:'u4',t:'gap',q:'Nosotros ___ (querer) un café.',a:['queremos']},
{u:'u4',t:'mc',q:'„Man kann mit Karte zahlen.“',opts:['Se puede pagar con tarjeta.','Puede pagar con tarjeta se.','Se pueden pagar con tarjeta.'],a:0},
{u:'u5',t:'mc',q:'El hotel está ___ museo. (neben)',opts:['al lado del','al lado de el','a lado del'],a:0},
{u:'u5',t:'gap',q:'Para ir a la feria ___ ___ tomar el metro. (du musst)',a:['tienes','que']},
{u:'u6',t:'mc',q:'„Die Heizung funktioniert nicht.“',opts:['No funciona la calefacción.','No funcionan la calefacción.','La calefacción no funcionan.'],a:0},
{u:'u6',t:'gap',q:'Todavía no ___ ___ (yo, ver) la Sagrada Família.',a:['he','visto']},
{u:'u7',t:'gap',q:'¿A qué hora ___ ___ (tú, acostarse)?',a:['te','acuestas']},
{u:'u7',t:'mc',q:'„Bevor ich frühstücke, dusche ich.“',opts:['Me ducho antes de desayunar.','Me ducho antes desayuno.','Me ducho antes que desayunar.'],a:0},
{u:'u8',t:'mc',q:'Diese Schuhe (hier bei mir):',opts:['estos zapatos','esos zapatos','estas zapatos'],a:0},
{u:'u8',t:'gap',q:'¿Qué ___ ___ hacer (tú) el sábado? (ir a + Inf.)',a:['vas','a']},
{u:'u9',t:'gap',q:'Cuando ___ (ser, yo) pequeño, ___ (vivir) en un pueblo.',a:['era','vivía']},
{u:'u9',t:'mc',q:'Imperfekt von „ir“ (nosotros):',opts:['íbamos','ibamos','fuimos'],a:0},
{u:'u9',t:'mc',q:'La cocina ___ equipada.',opts:['está','es','hay'],a:0},
{u:'u9',t:'mc',q:'„Man muss eine Kaution zahlen.“',opts:['Hay que pagar una fianza.','Hay pagar una fianza.','Tiene que pagar una fianza se.'],a:0},
{u:'u9',t:'gap',q:'Antes en mi barrio ___ (haber) muchas tiendas pequeñas.',a:['había']},
{u:'u9',t:'mc',q:'„Die Hälfte der Studierenden …“',opts:['La mitad de los estudiantes …','El medio de los estudiantes …','La media de estudiantes …'],a:0},
{u:'u10',t:'gap',q:'Ayer ___ (yo, trabajar) hasta las ocho.',a:['trabajé']},
{u:'u10',t:'mc',q:'Indefinido von „hacer“ (él):',opts:['hizo','hació','hice'],a:0},
{u:'u10',t:'mc',q:'En 2025 ___ tres meses en Londres.',opts:['estuve','he estado','estaba'],a:0},
{u:'u10',t:'gap',q:'El año pasado mis padres ___ (ir) a México.',a:['fueron']},
{u:'u10',t:'mc',q:'Hoy ___ mucho. (heute – noch nicht vorbei)',opts:['he trabajado','trabajé','trabajaba'],a:0},
{u:'u10',t:'mc',q:'„Ich bin bereit zu reisen.“',opts:['Estoy dispuesto a viajar.','Soy dispuesto a viajar.','Tengo dispuesto a viajar.'],a:0}
];
